#!/usr/bin/env python3
"""LAYER 2 of the LEAN.md Sec6 discipline for the SYMBOLIC coordinates.

    check_star_coords.py --coords <starcoords.txt> --lean <StarForall*.lean>
                         [--points 0,1,2] [--sample N] [--fresh <side>]
    check_star_coords.py --coords <starcoords.txt> --manifest <MANIFEST-*.sha256>

The first form checks the SINGLE-FILE layout, the second the MODULAR one.  They
differ only in arm B, and only in what is on disk to compare against: the
candidate's base module is ~16 MB and deliberately does not ship (Sec12.7), so
there arm B regenerates every module and compares SHA-256 against the committed
manifest -- the same bytes -- and additionally hashes from disk any module that
IS committed beside it (the ~780-byte per-point shards).  Arm C likewise reads
the regenerated base rather than a committed one.  The `--points` spec used for
the regeneration comes from the manifest's own `# points` line, not from the
caller, because regenerating at a different spec produces a different module set
and would make both a red and a green meaningless.

Four arms, each able to fail on ONE digit, and one of them able to fail on a
COMPLETE-LOOKING file that is missing a coordinate:

  A  ALGEBRAIC  -- re-derive the cleared residual in exact rational arithmetic at
     `N` integer `n` and require it identically zero.  Does not trust the
     engine's verdict line, and does not trust `star_forall_to_lean.py`'s own
     gate: this recomputes from the DUMP.

  B  BYTE-IDENTITY -- regenerate the Lean from the dump and require the bytes to
     match the committed file.  Catches a hand edit anywhere, including inside a
     271-digit literal.

  C  CONTAINMENT -- the dump carries exactly `dx + 1` certificate coefficients and
     `J + 1` recurrence coefficients, labelled in order; and the emitted Lean
     carries exactly `dx + 1` entries in `xCoeffs` and one `al<j>` per `j`.  A
     PER-ITEM check does not establish that the ENUMERATION was complete -- the
     measured cost of assuming it does was a fault invisible at 1 of 3 sample
     points (Sec13.7).  This arm is separate for that reason and only that one.

  D  FRESH (optional) -- re-run the engine and compare field for field.  Off by
     default because a candidate solve is ~23 minutes.

Exit 0 = all requested arms pass.  Exit 1 = at least one arm RED.
"""

import argparse
import glob
import hashlib
import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import star_coords_lib as scl  # noqa: E402
import star_forall_to_lean as sft  # noqa: E402
import star_lib  # noqa: E402


def arm_algebraic(c, xnum, atil, npts, D):
    bad = []
    for n in range(npts):
        r = sft.residual_at(c, xnum, atil, n)
        if not star_lib.is_zero(r):
            bad.append(n)
    proof = npts > D
    print("A ALGEBRAIC : %d point(s) checked, %d nonzero — %s%s"
          % (npts, len(bad), "PASS" if not bad else "RED (n = %s)" % bad[:5],
             "" if proof else "  [SAMPLE ONLY: %d <= D = %d, not a proof over Q[n]]" % (npts, D)))
    return not bad


def arm_bytes(coords_path, lean_path, points_arg):
    with tempfile.TemporaryDirectory() as td:
        regen = os.path.join(td, os.path.basename(lean_path))
        # `--emit-only` skips the generator's own residual gate, deliberately: this
        # arm is about the BYTES, arm A has already re-verified the mathematics
        # from the same dump, and re-running the gate here would double the cost of
        # the one expensive thing in the checker.
        rc = subprocess.call(
            [sys.executable, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                          "star_forall_to_lean.py"),
             "--coords", coords_path, "--out", regen, "--points", points_arg,
             "--emit-only"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if rc != 0 or not os.path.exists(regen):
            print("B BYTE-IDENT: RED — the generator refused to emit")
            return False
        with open(regen, "rb") as f:
            a = f.read()
        with open(lean_path, "rb") as f:
            b = f.read()
        ok = a == b
        print("B BYTE-IDENT: %s (%d vs %d bytes)"
              % ("PASS" if ok else "RED — regenerated bytes differ", len(a), len(b)))
        return ok


def arm_bytes_modular(manifest_path, committed_dir, regen_dir):
    """Arm B for the MODULAR layout: regenerate every module, hash, compare.

    The base module is ~16 MB of engine data at candidate scale and deliberately
    does NOT ship (zeta2-star-b1.md Sec12.7: derived Lean of that size is
    regenerated, not committed; Sec13.6 already applies the same manifest
    instrument to the 71.8 MB of grid receipts).  What ships is this manifest, and
    comparing SHA-256 is comparing the same bytes -- a flipped digit anywhere,
    including inside a 271-digit literal, changes the hash.

    The committed SHARD files ARE small enough to ship, so they are hashed FROM
    DISK against the same manifest: that is the arm that catches a hand edit to a
    file a reader can actually see.
    """
    want = {}
    with open(manifest_path) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.split()
            if len(parts) != 3:
                print("B BYTE-IDENT: RED — malformed manifest line %r" % line)
                return False
            want[parts[1]] = (parts[0], int(parts[2]))
    got = {}
    regen_manifest = os.path.join(regen_dir, "regen.sha256")
    if not os.path.exists(regen_manifest):
        print("B BYTE-IDENT: RED — the generator refused to emit")
        return False
    with open(regen_manifest) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            p = line.split()
            got[p[1]] = (p[0], int(p[2]))
    bad = []
    for name, (h, _sz) in want.items():
        if name not in got:
            bad.append("%s NOT REGENERATED" % name)
        elif got[name][0] != h:
            bad.append("%s hash %s != %s" % (name, got[name][0][:12], h[:12]))
    for name in got:
        if name not in want:
            bad.append("%s regenerated but ABSENT from the manifest" % name)
    # The committed SHARDS, hashed from disk against the same manifest -- the arm
    # that catches a hand edit to a file a reader can actually see.
    on_disk = 0
    for name in sorted(want):
        p = os.path.join(committed_dir, name)
        if not os.path.exists(p):
            continue
        on_disk += 1
        h = hashlib.sha256()
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        if h.hexdigest() != want[name][0]:
            bad.append("committed %s does not match the manifest" % name)
    ok = not bad
    print("B BYTE-IDENT: %s (%d module(s) in the manifest, %d regenerated, "
          "%d committed on disk and hashed)%s"
          % ("PASS" if ok else "RED", len(want), len(got), on_disk,
             "" if ok else " — " + "; ".join(bad[:4])))
    return ok


def arm_containment(c, lean_path):
    nx = c.dx + 1
    ok = True
    if len(c.coords) != nx + c.J + 1:
        ok = False
    with open(lean_path) as f:
        text = f.read()
    # `xCoeffs` is either one bracketed list of literal lists (the `ring` encoding: one list per
    # line, the generator's own discipline) or, under the `literal` encoding adopted in Sec17.7,
    # a list of NAMES `[xc0, xc1, ...]` each defined as its own `noncomputable def xcK`.  In the
    # named form the count is the names, and containment additionally requires every named list
    # to be DEFINED in the base — a name with no definition is a missing coordinate wearing an
    # identifier.
    start = text.find("noncomputable def xCoeffs")
    end = text.find("\n\n", start)
    body = text[start:end]
    entries = body.count("[(") + body.count("[((")
    if start >= 0 and "xc0" in body:
        names = [tok.strip() for tok in body[body.find("[") + 1:body.rfind("]")].split(",")]
        names = [n for n in names if n]
        undefined = [n for n in names if ("noncomputable def %s " % n) not in text]
        got_x = len(names) if not undefined else -1
    else:
        got_x = body.count("\n   [") + 1 if start >= 0 else 0
    missing_al = [j for j in range(c.J + 1) if ("noncomputable def al%d" % j) not in text]
    ok = ok and got_x == nx and not missing_al
    print("C CONTAINMENT: dump %d coords (dx+1=%d, J+1=%d); Lean xCoeffs %d entries; "
          "missing al %s — %s"
          % (len(c.coords), nx, c.J + 1, got_x, missing_al or "none", "PASS" if ok else "RED"))
    del entries
    return ok


def arm_fresh(coords_path, side, binary):
    with tempfile.TemporaryDirectory() as td:
        fresh = os.path.join(td, "fresh.txt")
        rc = subprocess.call([binary, "starcoords", side, "--out", fresh],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if rc != 0 or not os.path.exists(fresh):
            print("D FRESH     : RED — the engine run failed")
            return False
        a = scl.parse_coords(coords_path)
        b = scl.parse_coords(fresh)
        ok = (a.dx == b.dx and a.J == b.J and len(a.coords) == len(b.coords)
              and all(x["A"] == y["A"] and x["B"] == y["B"]
                      for x, y in zip(a.coords, b.coords))
              and a.fac == b.fac)
        print("D FRESH     : %s" % ("PASS" if ok else "RED — a field differs"))
        return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--coords", required=True)
    ap.add_argument("--lean", help="single-file layout: the committed .lean to check")
    ap.add_argument("--manifest",
                    help="MODULAR layout: the committed SHA-256 manifest of the emitted "
                         "modules.  Arm B regenerates them and compares hashes, and any "
                         "module also committed beside the manifest is hashed from disk.")
    ap.add_argument("--points", default="0,1,2")
    ap.add_argument("--sample", type=int, default=-1,
                    help="points for arm A; default D+1, which makes it a proof over Q[n]")
    ap.add_argument("--fresh", default=None, help="side name; re-runs the engine (arm D)")
    ap.add_argument("--binary", default="build/mb_pipeline")
    ap.add_argument("--skip-bytes", action="store_true")
    args = ap.parse_args()
    if bool(args.lean) == bool(args.manifest):
        print("check_star_coords: give exactly one of --lean (single file) or --manifest "
              "(modular)", file=sys.stderr)
        return 2

    try:
        c, L, xnum, atil, D, _g = sft.build(args.coords)
    except ValueError as e:
        # `parse_coords` REFUSES a dump whose coordinate enumeration is incomplete,
        # so a missing coordinate reaches here as an exception rather than as a
        # failed arm. Report it as arm C's red — a checker that dies on the
        # corruption it exists to find still has to SAY which arm found it.
        print("C CONTAINMENT: RED — %s" % e)
        print("check_star_coords: FAILED")
        return 1
    print("side=%s dx=%d J=%d coords=%d D=%d" % (c.side, c.dx, c.J, len(c.coords), D))
    npts = D + 1 if args.sample < 0 else args.sample
    ok = arm_algebraic(c, xnum, atil, npts, D)
    if args.lean:
        ok = arm_containment(c, args.lean) and ok
        if not args.skip_bytes:
            ok = arm_bytes(args.coords, args.lean, args.points) and ok
    else:
        # MODULAR: regenerate ONCE into a scratch tree and let arms B and C read
        # the same regenerated base.  Arm C must inspect the object that carries
        # `xCoeffs`, and at candidate scale that object deliberately does not
        # ship (see `arm_bytes_modular`), so it is regenerated rather than read
        # from the repo -- and arm B is what pins that the regeneration is the
        # committed one.
        # The point spec comes from the MANIFEST, not from the caller: regenerating
        # at a different spec produces a different module set, so a caller who
        # guessed would get a red that means nothing (or, in a falsifier, a green
        # restore control that means nothing).
        pts = sft.manifest_points(args.manifest)
        if pts is None:
            print("B BYTE-IDENT: manifest carries no `# points` line; using --points %s"
                  % args.points)
            pts = args.points
        elif pts != args.points:
            print("note: regenerating at the manifest's own --points %s (not the requested %s)"
                  % (pts, args.points))
        # The ENCODING too (2026-09-11): a `# encoding kernel` manifest lists `K<n>` shards,
        # which only that arm of the generator writes.
        enc = sft.manifest_encoding(args.manifest)
        # And whether the ASSEMBLY was emitted (2026-09-14).  A manifest that LISTS
        # `<stem>Assemble.lean` and is regenerated without `--assemble` fails arm B with a
        # missing file, and that red says nothing about any byte — the same failure mode the
        # `# points` and `# encoding` lines were added for, a third time.
        asm = sft.manifest_assemble(args.manifest)
        with tempfile.TemporaryDirectory() as td:
            cmd = [sys.executable, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                "star_forall_to_lean.py"),
                   "--coords", args.coords, "--emit-modules", td, "--points", pts,
                   "--h0-encoding", enc,
                   "--manifest", os.path.join(td, "regen.sha256"), "--emit-only"]
            if asm:
                cmd.append("--assemble")
            rc = subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            bases = sorted(glob.glob(os.path.join(td, "*Base.lean")))
            if rc != 0 or not bases:
                print("C CONTAINMENT: RED — the generator produced no base module")
                print("B BYTE-IDENT: RED — the generator refused to emit")
                ok = False
            else:
                ok = arm_containment(c, bases[0]) and ok
                if not args.skip_bytes:
                    ok = arm_bytes_modular(args.manifest,
                                           os.path.dirname(os.path.abspath(args.manifest)),
                                           td) and ok
    if args.fresh:
        ok = arm_fresh(args.coords, args.fresh, args.binary) and ok
    print("check_star_coords: %s" % ("ALL PASS" if ok else "FAILED"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
