/-
L7-MIDDLE M6 AS A MODULE — Lemma 9's contour move, importable BESIDE the `L7MidM5` module.

Same bytes as `L7MidM6.lean`'s and the capstone's M6 section (all three are `m6_glue.lean`),
different substrate: this one sits on `import L7MidM5` instead of re-embedding M123/M4, so a
consumer may import it together with `Zeta2L7IdHinge`/`Zeta2L7IdSplit`/`Zeta2L7IdMoment`, which
all import `L7MidM5`.  Row L7ID obligation 5 (`Zeta2L7IdContour.lean`) is the consumer, and it
is the reason this artifact exists: with only the two pre-existing copies, `L7MidM6.lemma9` and
`Zeta2L7IdSplit.Hn_eq_PpolArm_add_ResidArm` cannot appear in one elaboration.

GENERATED by tools/lean_consolidate.py from
  ./m6_glue.lean
-- edit that, not this file, and re-run the generator.  `--check` fails if this file has
drifted from it.
-/
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Complex
import Mathlib.Analysis.Complex.CauchyIntegral
import Mathlib.Analysis.Complex.Exponential
import L7MidM5


/-! # L7-middle M6 — Lemma 9, the contour move

`zeta2-l7-middle.md` §7 row M6, built on M0's `kernel_collapse`, M2's `Hn` / `Hn_eq_kernel_form`
/ `differentiableOn_Hn` and M4's `Pi_n_pos`.  `zeta2-l7-proof.md` §5 Lemma 9:

> For every `n ≥ 1` the integrals of `H_n` over the lines `Re t = −4n−1/2` and `Re t = −σ̃n−1/2`
> (both upward) are EQUAL.

**Two halves of that lemma were already deleted by earlier rows, and this file does not rebuild
them.**  The POLE CENSUS is gone: `zeta2-l7-middle.md` §3b defines `H_n` in the reflected form, so
`L7MidM123.differentiableOn_Hn` is differentiability on the CLOSED strip with no residue count and
no removable-singularity theorem.  The `1/(2q̃)`-separation of the left line from `ℤ` is gone too
(§3a): nothing here is divided by `sin` except inside an identity that carries `Im t ≠ 0`, which is
true on the whole of both lines except a null set — and in fact the identity is only ever used at
`|Im t| ≥ 1`.

**What survives is the DECAY half, and it takes the RATIONAL representation** — the design's §3f
records the measured absence that forces this: current Mathlib has no `|Γ(x+iy)|` decay estimate as
`|y| → ∞`, so the reflected form (seven numerator `Γ`'s beating one denominator `Γ` against
`e^{π|y|}` from `sin`) cannot be bounded at all.  Converting the eight `Γ`'s to a ratio of
POLYNOMIALS removes every `Γ` from the estimate, and the polynomial is Mathlib's `ascPochhammer`
(`Complex.Gamma_add_nat_div_Gamma_eq`) — the **seventh** time in this program that a step priced as
new construction was already in the library (`skills/LEAN.md` §2).

**The mechanism is stated separately from `H_n`** (`line_integral_eq_of_exp_decay`, §7): any `f`
holomorphic on a closed vertical strip and `O(e^{−c|Im|})` there has equal integrals over the two
boundary lines.  That is the whole of "rectangle Cauchy + `T → ∞`", and it knows nothing about
`Γ`, `σ̃` or `n`.  §8–§10 supply the two inputs for `H_n`.
-/

namespace L7MidM6

open Complex Filter MeasureTheory
open L7MidM123 Zeta2SupScheme

/-! ## §1. Two name-free monotonicity helpers

Both are one-liners in principle; they are written out by induction because the library names for
them (`pow_le_pow_left`, `one_le_pow₀`) have drifted repeatedly and `gcongr` emits a variable
number of side goals here (`skills/LEAN.md` §8). -/

/-- `x ≤ y` with `0 ≤ x` gives `x^k ≤ y^k`. -/
theorem pow_mono_base {x y : ℝ} (hx : 0 ≤ x) (hxy : x ≤ y) : ∀ k : ℕ, x ^ k ≤ y ^ k := by
  intro k
  induction k with
  | zero => simp
  | succ k ih =>
      rw [pow_succ, pow_succ]
      exact mul_le_mul ih hxy hx (le_trans (pow_nonneg hx k) ih)

/-! ## §2. The ascending Pochhammer, as a function, with two-sided norm bounds -/

/-- `(z)_m = z (z+1) ⋯ (z+m−1)`, the value of Mathlib's `ascPochhammer` at `z`.  This is the
"rational representation" of `zeta2-l7-proof.md` Lemma 9's `R_n`: each `Γ`-ratio
`Γ(t+a)/Γ(t+b)` with `a ≥ b` natural is one of these. -/
noncomputable def asc (m : ℕ) (z : ℂ) : ℂ := (ascPochhammer ℂ m).eval z

/-- `(z)_0 = 1`. -/
theorem asc_zero (z : ℂ) : asc 0 z = 1 := by simp [asc]

/-- `(z)_{m+1} = (z)_m · (z + m)`. -/
theorem asc_succ (m : ℕ) (z : ℂ) : asc (m + 1) z = asc m z * (z + m) := by
  simp [asc, ascPochhammer_succ_right]

/-- Crude upper bound `‖(z)_m‖ ≤ (‖z‖ + m)^m`.  Crude is the point: Lemma 9 needs polynomial
growth against `e^{−2πT}`, and any polynomial loses. -/
theorem norm_asc_le (m : ℕ) (z : ℂ) : ‖asc m z‖ ≤ (‖z‖ + m) ^ m := by
  induction m with
  | zero => simp [asc_zero]
  | succ m ih =>
      have h1 : ‖z + (m : ℂ)‖ ≤ ‖z‖ + m := by
        refine le_trans (norm_add_le _ _) ?_
        simp
      calc ‖asc (m + 1) z‖ = ‖asc m z‖ * ‖z + (m : ℂ)‖ := by rw [asc_succ, norm_mul]
        _ ≤ (‖z‖ + m) ^ m * (‖z‖ + m) :=
            mul_le_mul ih h1 (norm_nonneg _) (by positivity)
        _ = (‖z‖ + (m : ℝ)) ^ (m + 1) := by ring
        _ ≤ (‖z‖ + ((m : ℝ) + 1)) ^ (m + 1) := by
              refine pow_mono_base (by positivity) ?_ _
              linarith
        _ = (‖z‖ + ((m + 1 : ℕ) : ℝ)) ^ (m + 1) := by push_cast; ring

/-- Crude lower bound in the right half-plane, `(Re z)^m ≤ ‖(z)_m‖`.  This is what replaces the
write-up's `|t+k| ≥ 15n+1−σ̃n−1/2 ≥ 9n` denominator estimate, and it needs no separation
argument — only `Re z ≥ 0`, which the strip supplies with `9n + 1/2` to spare. -/
theorem re_pow_le_norm_asc (m : ℕ) {z : ℂ} (hz : 0 ≤ z.re) : z.re ^ m ≤ ‖asc m z‖ := by
  induction m with
  | zero => simp [asc_zero]
  | succ m ih =>
      have h1 : z.re ≤ ‖z + (m : ℂ)‖ := by
        refine le_trans ?_ (Complex.re_le_norm _)
        simp only [Complex.add_re, Complex.natCast_re]
        linarith [Nat.cast_nonneg (α := ℝ) m]
      calc z.re ^ (m + 1) = z.re ^ m * z.re := by ring
        _ ≤ ‖asc m z‖ * ‖z + (m : ℂ)‖ := mul_le_mul ih h1 hz (norm_nonneg _)
        _ = ‖asc (m + 1) z‖ := by rw [asc_succ, norm_mul]

/-! ## §3. `Γ(z + m) = (z)_m · Γ(z)` off the real axis

**MEASURED FIND, not a build** (`skills/LEAN.md` §2): `Complex.Gamma_add_nat_div_Gamma_eq` is
Mathlib's, and it is exactly `zeta2-l7-proof.md` Lemma 9's `Γ(t+a)/Γ(t+b) = ∏_{k=b}^{a−1}(t+k)`.
The only work is discharging its side condition, and `Im z ≠ 0` does it in two lines. -/

/-- `Γ(z) ≠ 0` off the real axis. -/
theorem Gamma_ne_zero_of_im_ne_zero {z : ℂ} (hz : z.im ≠ 0) : Complex.Gamma z ≠ 0 :=
  Complex.Gamma_ne_zero (fun m hm => hz (by rw [hm]; simp))

/-- The Γ-ratio identity, in the product form Lemma 9 needs. -/
theorem Gamma_shift_nat (m : ℕ) {z : ℂ} (hz : z.im ≠ 0) :
    Complex.Gamma (z + m) = asc m z * Complex.Gamma z := by
  have hne : ∀ k : ℕ, z ≠ -(k : ℂ) := fun k hk => hz (by rw [hk]; simp)
  have h := Complex.Gamma_add_nat_div_Gamma_eq (n := m) z hne
  rw [div_eq_iff (Complex.Gamma_ne_zero hne)] at h
  exact h

/-! ## §4. `‖sin z‖` from below — the mirror of `L7Mid.norm_sin_le_cosh`

`zeta2-l7-middle.md` §3f measured the absence: Mathlib has no `‖Complex.sin z‖` bound of any kind,
in either direction.  `norm_sin_le_cosh` (M0) built the upper one; this is the lower one, and it
is the `|sin πt| ≥ sinh πT ≥ e^{πT}(1−e^{−2π})/2` step of Lemma 9 with `4` in place of the sharp
constant `2/(1−e^{−2π})`. -/

/-- `e^{|Im z|} ≤ 4 ‖sin z‖` once `|Im z| ≥ 1`. -/
theorem exp_abs_im_le_four_mul_norm_sin {z : ℂ} (h : 1 ≤ |z.im|) :
    Real.exp |z.im| ≤ 4 * ‖Complex.sin z‖ := by
  have ha : ‖Complex.exp (-z * Complex.I)‖ = Real.exp z.im := by
    rw [Complex.norm_exp]; congr 1; simp [Complex.neg_re, Complex.mul_re]
  have hb : ‖Complex.exp (z * Complex.I)‖ = Real.exp (-z.im) := by
    rw [Complex.norm_exp]; congr 1; simp [Complex.mul_re]
  have hs : ‖Complex.sin z‖
      = ‖Complex.exp (-z * Complex.I) - Complex.exp (z * Complex.I)‖ / 2 := by
    rw [Complex.sin, norm_div, norm_mul, Complex.norm_I, mul_one]
    norm_num
  have key : |Real.exp z.im - Real.exp (-z.im)|
      ≤ ‖Complex.exp (-z * Complex.I) - Complex.exp (z * Complex.I)‖ := by
    rw [← ha, ← hb]; exact abs_norm_sub_norm_le _ _
  have h2 : (2 : ℝ) ≤ Real.exp 2 := by linarith [Real.add_one_le_exp (2 : ℝ)]
  rcases le_total 0 z.im with hy | hy
  · rw [abs_of_nonneg hy] at h ⊢
    have hstep : 2 * Real.exp (-z.im) ≤ Real.exp z.im := by
      calc 2 * Real.exp (-z.im) ≤ Real.exp 2 * Real.exp (-z.im) := by
            nlinarith [Real.exp_pos (-z.im)]
        _ = Real.exp (2 - z.im) := by rw [← Real.exp_add]; ring_nf
        _ ≤ Real.exp z.im := Real.exp_le_exp.mpr (by linarith)
    rw [abs_of_nonneg (by linarith [Real.exp_pos (-z.im)] :
      (0 : ℝ) ≤ Real.exp z.im - Real.exp (-z.im))] at key
    rw [hs]; linarith
  · rw [abs_of_nonpos hy] at h ⊢
    have hstep : 2 * Real.exp z.im ≤ Real.exp (-z.im) := by
      calc 2 * Real.exp z.im ≤ Real.exp 2 * Real.exp z.im := by
            nlinarith [Real.exp_pos z.im]
        _ = Real.exp (2 + z.im) := by rw [← Real.exp_add]
        _ ≤ Real.exp (-z.im) := Real.exp_le_exp.mpr (by linarith)
    rw [abs_of_nonpos (by linarith [Real.exp_pos z.im] :
      Real.exp z.im - Real.exp (-z.im) ≤ 0)] at key
    rw [hs]; linarith

/-! ## §5. `x^k ≤ k! e^x` — polynomial growth becomes a pure exponential

This is the step that keeps the whole estimate free of `n`-dependent polynomial bookkeeping: the
`(T + cn)^{27n}` of `zeta2-l7-proof.md` Lemma 9 is absorbed into a constant times `e^{|Im t|}`,
leaving `e^{−5|Im t|}` after the kernel's `e^{−6|Im t|}`.  The `2π` of the write-up is spent down
to `6 < 2π` via `π > 3`, and one unit of that is spent here. -/

/-- `x^k ≤ k! · e^x` for `x ≥ 0`. -/
theorem pow_le_factorial_mul_exp (k : ℕ) {x : ℝ} (hx : 0 ≤ x) :
    x ^ k ≤ (Nat.factorial k : ℝ) * Real.exp x := by
  have hk : (0 : ℝ) < (Nat.factorial k : ℝ) := by exact_mod_cast Nat.factorial_pos k
  have h2 : x ^ k / (Nat.factorial k : ℝ) ≤ Real.exp x := Real.pow_div_factorial_le_exp x hx k
  calc x ^ k = x ^ k / (Nat.factorial k : ℝ) * (Nat.factorial k : ℝ) := by field_simp
    _ ≤ Real.exp x * (Nat.factorial k : ℝ) := mul_le_mul_of_nonneg_right h2 (le_of_lt hk)
    _ = (Nat.factorial k : ℝ) * Real.exp x := by ring

/-! ## §6. Integrability from exponential decay -/

/-- `y ↦ e^{−c|y|}` is integrable on all of ℝ for `c > 0`. -/
theorem integrable_exp_neg_mul_abs {c : ℝ} (hc : 0 < c) :
    Integrable (fun y : ℝ => Real.exp (-c * |y|)) := by
  rw [← integrableOn_univ, ← Set.Iic_union_Ioi (a := (0 : ℝ))]
  refine IntegrableOn.union ?_ ?_
  · refine (integrableOn_exp_mul_Iic (a := c) hc 0).congr_fun ?_ measurableSet_Iic
    intro y hy
    simp only [Set.mem_Iic] at hy
    show Real.exp (c * y) = Real.exp (-c * |y|)
    rw [abs_of_nonpos hy]; congr 1; ring
  · refine (integrableOn_exp_mul_Ioi (a := -c) (by linarith) 0).congr_fun ?_ measurableSet_Ioi
    intro y hy
    simp only [Set.mem_Ioi] at hy
    show Real.exp (-c * y) = Real.exp (-c * |y|)
    rw [abs_of_nonneg (le_of_lt hy)]

/-- A continuous `f : ℝ → ℂ` dominated by `K e^{−c|y|}` OUTSIDE `[−1, 1]` is integrable.

The compact core is handled by `IsCompact.exists_bound_of_continuousOn`, not by the decay bound.
That split is what lets the decay hypothesis start at `|y| ≥ 1` — which it must, since the bound
runs through `1/‖sin‖` and that blows up at `y = 0` on any line whose real part is an integer.
`H_n` itself is perfectly finite there (`L7MidM123.Hn_defined_at_integer`); it is the ESTIMATE,
not the function, that needs `|y| ≥ 1`. -/
theorem integrable_of_exp_decay {f : ℝ → ℂ} (hf : Continuous f) {K c : ℝ} (hc : 0 < c)
    (hK : ∀ y : ℝ, 1 ≤ |y| → ‖f y‖ ≤ K * Real.exp (-c * |y|)) :
    Integrable f := by
  obtain ⟨C, hC⟩ := (isCompact_Icc (a := (-1 : ℝ)) (b := 1)).exists_bound_of_continuousOn
    hf.continuousOn
  set A : ℝ := max (C * Real.exp c) (max K 0) with hA
  have hbound : ∀ y : ℝ, ‖f y‖ ≤ A * Real.exp (-c * |y|) := by
    intro y
    rcases le_or_gt 1 |y| with hy | hy
    · refine le_trans (hK y hy) ?_
      have hKA : K ≤ A := le_trans (le_max_left K 0) (le_max_right _ _)
      exact mul_le_mul_of_nonneg_right hKA (Real.exp_pos _).le
    · have hmem : y ∈ Set.Icc (-1 : ℝ) 1 := by
        rw [abs_lt] at hy; exact ⟨le_of_lt hy.1, le_of_lt hy.2⟩
      have hCy : ‖f y‖ ≤ C := hC y hmem
      have hC0 : 0 ≤ C := le_trans (norm_nonneg _) hCy
      have h1 : Real.exp (-c) ≤ Real.exp (-c * |y|) := by
        refine Real.exp_le_exp.mpr ?_
        nlinarith [abs_nonneg y, le_of_lt hy]
      calc ‖f y‖ ≤ C := hCy
        _ = C * Real.exp c * Real.exp (-c) := by
            rw [mul_assoc, ← Real.exp_add]; norm_num
        _ ≤ C * Real.exp c * Real.exp (-c * |y|) :=
            mul_le_mul_of_nonneg_left h1 (by positivity)
        _ ≤ A * Real.exp (-c * |y|) :=
            mul_le_mul_of_nonneg_right (le_max_left _ _) (Real.exp_pos _).le
  refine Integrable.mono' (g := fun y : ℝ => A * Real.exp (-c * |y|))
    ((integrable_exp_neg_mul_abs hc).const_mul A) hf.aestronglyMeasurable ?_
  exact Filter.Eventually.of_forall hbound

/-! ## §7. THE CONTOUR-MOVE ENGINE — Lemma 9's mechanism, isolated from `H_n` -/

/-- **Lemma 9, stated for any `f` with the two properties it actually uses.**

If `f` is holomorphic on the CLOSED vertical strip `xL ≤ Re z ≤ xR` and satisfies
`‖f z‖ ≤ K e^{−c|Im z|}` there once `|Im z| ≥ 1`, then its integrals over the two boundary lines
are EQUAL.

This is `zeta2-l7-proof.md` §5's proof with the `H_n`-specific parts removed:
`Complex.integral_boundary_rect_eq_zero_of_differentiableOn` on `[xL, xR] × [−T, T]`, the two
horizontal segments bounded by `K e^{−cT}·(xR − xL)` and squeezed to `0`, and the truncated
verticals converging to the full line integrals because §6 makes each line integrand integrable.

Stating it this way is deliberate: nothing in it mentions `Γ`, `σ̃` or `n`, so the row's analysis
is separable from its arithmetic, and a future row that moves a different contour reuses it. -/
theorem line_integral_eq_of_exp_decay {f : ℂ → ℂ} {xL xR K c : ℝ}
    (hxLR : xL ≤ xR) (hc : 0 < c)
    (hd : DifferentiableOn ℂ f {z : ℂ | xL ≤ z.re ∧ z.re ≤ xR})
    (hdec : ∀ z : ℂ, xL ≤ z.re → z.re ≤ xR → 1 ≤ |z.im| →
      ‖f z‖ ≤ K * Real.exp (-c * |z.im|)) :
    (∫ y : ℝ, f ((xL : ℂ) + (y : ℂ) * Complex.I))
      = ∫ y : ℝ, f ((xR : ℂ) + (y : ℂ) * Complex.I) := by
  set S : Set ℂ := {z : ℂ | xL ≤ z.re ∧ z.re ≤ xR} with hS
  have hlineL : ∀ y : ℝ, ((xL : ℂ) + (y : ℂ) * Complex.I) ∈ S := by
    intro y; constructor <;> simp [hxLR]
  have hlineR : ∀ y : ℝ, ((xR : ℂ) + (y : ℂ) * Complex.I) ∈ S := by
    intro y; constructor <;> simp [hxLR]
  have hcL : Continuous (fun y : ℝ => f ((xL : ℂ) + (y : ℂ) * Complex.I)) :=
    hd.continuousOn.comp_continuous (by fun_prop) hlineL
  have hcR : Continuous (fun y : ℝ => f ((xR : ℂ) + (y : ℂ) * Complex.I)) :=
    hd.continuousOn.comp_continuous (by fun_prop) hlineR
  have hiL : Integrable (fun y : ℝ => f ((xL : ℂ) + (y : ℂ) * Complex.I)) := by
    refine integrable_of_exp_decay (K := K) hcL hc (fun y hy => ?_)
    have h1 : ((xL : ℂ) + (y : ℂ) * Complex.I).re = xL := by simp
    have h2 : ((xL : ℂ) + (y : ℂ) * Complex.I).im = y := by simp
    have hh := hdec _ (by rw [h1]) (by rw [h1]; exact hxLR) (by rw [h2]; exact hy)
    rwa [h2] at hh
  have hiR : Integrable (fun y : ℝ => f ((xR : ℂ) + (y : ℂ) * Complex.I)) := by
    refine integrable_of_exp_decay (K := K) hcR hc (fun y hy => ?_)
    have h1 : ((xR : ℂ) + (y : ℂ) * Complex.I).re = xR := by simp
    have h2 : ((xR : ℂ) + (y : ℂ) * Complex.I).im = y := by simp
    have hh := hdec _ (by rw [h1]; exact hxLR) (by rw [h1]) (by rw [h2]; exact hy)
    rwa [h2] at hh
  have hrect : ∀ T : ℝ, Complex.I *
      ((∫ y : ℝ in (-T)..T, f ((xR : ℂ) + (y : ℂ) * Complex.I))
        - ∫ y : ℝ in (-T)..T, f ((xL : ℂ) + (y : ℂ) * Complex.I))
      = (∫ x : ℝ in xL..xR, f ((x : ℂ) + ((T : ℝ) : ℂ) * Complex.I))
        - ∫ x : ℝ in xL..xR, f ((x : ℂ) + ((-T : ℝ) : ℂ) * Complex.I) := by
    intro T
    set zz : ℂ := (xL : ℂ) - (T : ℂ) * Complex.I with hzz
    set ww : ℂ := (xR : ℂ) + (T : ℂ) * Complex.I with hww
    have hzre : zz.re = xL := by simp [hzz]
    have hzim : zz.im = -T := by simp [hzz]
    have hwre : ww.re = xR := by simp [hww]
    have hwim : ww.im = T := by simp [hww]
    have hsub : DifferentiableOn ℂ f (Set.uIcc zz.re ww.re ×ℂ Set.uIcc zz.im ww.im) := by
      refine hd.mono ?_
      rw [hzre, hwre, Set.uIcc_of_le hxLR]
      intro u hu
      rw [Complex.mem_reProdIm] at hu
      exact ⟨hu.1.1, hu.1.2⟩
    have h := Complex.integral_boundary_rect_eq_zero_of_differentiableOn f zz ww hsub
    rw [hzre, hzim, hwre, hwim] at h
    simp only [smul_eq_mul, Complex.ofReal_neg] at h ⊢
    linear_combination h
  have hhoriz : ∀ s : ℝ, 1 ≤ |s| →
      ‖(∫ x : ℝ in xL..xR, f ((x : ℂ) + ((s : ℝ) : ℂ) * Complex.I))‖
        ≤ (K * Real.exp (-c * |s|)) * |xR - xL| := by
    intro s hs
    refine intervalIntegral.norm_integral_le_of_norm_le_const (fun x hx => ?_)
    rw [Set.uIoc_of_le hxLR] at hx
    have h1 : ((x : ℂ) + ((s : ℝ) : ℂ) * Complex.I).re = x := by simp
    have h2 : ((x : ℂ) + ((s : ℝ) : ℂ) * Complex.I).im = s := by simp
    have hh := hdec _ (by rw [h1]; exact le_of_lt hx.1) (by rw [h1]; exact hx.2)
      (by rw [h2]; exact hs)
    rwa [h2] at hh
  have hexp : Tendsto (fun T : ℝ => Real.exp (-c * T)) atTop (nhds 0) :=
    Real.tendsto_exp_atBot.comp
      (Filter.tendsto_id.const_mul_atTop_of_neg (show -c < 0 by linarith))
  have hgo : Tendsto (fun T : ℝ => K * Real.exp (-c * T) * |xR - xL|) atTop (nhds 0) := by
    have h := (hexp.const_mul K).mul_const |xR - xL|
    simpa using h
  have hHT : Tendsto (fun T : ℝ => ∫ x : ℝ in xL..xR, f ((x : ℂ) + ((T : ℝ) : ℂ) * Complex.I))
      atTop (nhds 0) := by
    refine squeeze_zero_norm' ?_ hgo
    filter_upwards [eventually_ge_atTop (1 : ℝ)] with T hT
    have h := hhoriz T (by rw [abs_of_nonneg (by linarith : (0 : ℝ) ≤ T)]; exact hT)
    rwa [abs_of_nonneg (by linarith : (0 : ℝ) ≤ T)] at h
  have hHB : Tendsto (fun T : ℝ => ∫ x : ℝ in xL..xR, f ((x : ℂ) + ((-T : ℝ) : ℂ) * Complex.I))
      atTop (nhds 0) := by
    refine squeeze_zero_norm' ?_ hgo
    filter_upwards [eventually_ge_atTop (1 : ℝ)] with T hT
    have h := hhoriz (-T) (by rw [abs_neg, abs_of_nonneg (by linarith : (0 : ℝ) ≤ T)]; exact hT)
    rwa [abs_neg, abs_of_nonneg (by linarith : (0 : ℝ) ≤ T)] at h
  have hneg : Tendsto (fun T : ℝ => -T) atTop atBot := by
    refine tendsto_atBot.mpr (fun b => ?_)
    filter_upwards [eventually_ge_atTop (-b)] with T hT
    linarith
  have hVR : Tendsto (fun T : ℝ => ∫ y : ℝ in (-T)..T, f ((xR : ℂ) + (y : ℂ) * Complex.I))
      atTop (nhds (∫ y : ℝ, f ((xR : ℂ) + (y : ℂ) * Complex.I))) :=
    intervalIntegral_tendsto_integral hiR hneg tendsto_id
  have hVL : Tendsto (fun T : ℝ => ∫ y : ℝ in (-T)..T, f ((xL : ℂ) + (y : ℂ) * Complex.I))
      atTop (nhds (∫ y : ℝ, f ((xL : ℂ) + (y : ℂ) * Complex.I))) :=
    intervalIntegral_tendsto_integral hiL hneg tendsto_id
  have hdiff : Tendsto (fun T : ℝ => Complex.I *
      ((∫ y : ℝ in (-T)..T, f ((xR : ℂ) + (y : ℂ) * Complex.I))
        - ∫ y : ℝ in (-T)..T, f ((xL : ℂ) + (y : ℂ) * Complex.I))) atTop
      (nhds (Complex.I * ((∫ y : ℝ, f ((xR : ℂ) + (y : ℂ) * Complex.I))
        - ∫ y : ℝ, f ((xL : ℂ) + (y : ℂ) * Complex.I)))) :=
    (hVR.sub hVL).const_mul Complex.I
  have hzero : Tendsto (fun T : ℝ => Complex.I *
      ((∫ y : ℝ in (-T)..T, f ((xR : ℂ) + (y : ℂ) * Complex.I))
        - ∫ y : ℝ in (-T)..T, f ((xL : ℂ) + (y : ℂ) * Complex.I))) atTop (nhds 0) := by
    have h0 := hHT.sub hHB
    rw [sub_zero] at h0
    exact h0.congr (fun T => (hrect T).symm)
  rcases mul_eq_zero.mp (tendsto_nhds_unique hdiff hzero) with hI | hsub
  · exact absurd hI Complex.I_ne_zero
  · exact (sub_eq_zero.mp hsub).symm

/-! ## §8. `H_n` as a RATIONAL function times the kernel

The four `Γ`-ratios of `zeta2-l7-proof.md` §1's `R_n`, paired so that every ratio has a
NON-NEGATIVE integer gap:

| pair | gap | `ascPochhammer` degree |
|---|---|---|
| `Γ(t+a₁)/Γ(t+b₁)`, `a₁ = 13n+1`, `b₁ = 1` | `13n` | numerator |
| `Γ(t+a₂)/Γ(t+b₂)`, `a₂ = 11n+1`, `b₂ = 2n+1` | `9n` | numerator |
| `Γ(t+a₃)/Γ(t+b₃)`, `a₃ = 9n+1`, `b₃ = 4n+1` | `5n` | numerator |
| `Γ(t+b₄)/Γ(t+a₄)`, `b₄ = 26n+2`, `a₄ = 15n+1` | `11n+1` | DENOMINATOR |

`13n + 9n + 5n = 27n` and `11n + 1` are exactly the write-up's `(|t| + 13n)^{27n}` and
`(9n)^{11n+1}`. -/

theorem shift_ratio_a₁ (n : ℕ) (t : ℂ) :
    t + (a₁ n : ℂ) = (t + (b₁ n : ℂ)) + ((13 * n : ℕ) : ℂ) := by
  simp only [a₁, b₁]; push_cast; ring

theorem shift_ratio_a₂ (n : ℕ) (t : ℂ) :
    t + (a₂ n : ℂ) = (t + (b₂ n : ℂ)) + ((9 * n : ℕ) : ℂ) := by
  simp only [a₂, b₂]; push_cast; ring

theorem shift_ratio_a₃ (n : ℕ) (t : ℂ) :
    t + (a₃ n : ℂ) = (t + (b₃ n : ℂ)) + ((5 * n : ℕ) : ℂ) := by
  simp only [a₃, b₃]; push_cast; ring

theorem shift_ratio_b₄ (n : ℕ) (t : ℂ) :
    t + (b₄ n : ℂ) = (t + (a₄ n : ℂ)) + ((11 * n + 1 : ℕ) : ℂ) := by
  simp only [a₄, b₄]; push_cast; ring

/-- `sin(π t) ≠ 0` off the real axis — all that survives of `zeta2-l7-proof.md` Lemma 3.2. -/
theorem sin_pi_ne_zero_of_im_ne_zero {t : ℂ} (ht : t.im ≠ 0) :
    Complex.sin ((Real.pi : ℂ) * t) ≠ 0 := by
  intro h
  rcases Complex.sin_eq_zero_iff.mp h with ⟨k, hk⟩
  have h2 : ((Real.pi : ℂ) * t).im = 0 := by rw [hk]; simp
  rw [Complex.mul_im] at h2
  simp only [Complex.ofReal_re, Complex.ofReal_im, zero_mul, add_zero] at h2
  rcases mul_eq_zero.mp h2 with h3 | h3
  · exact Real.pi_ne_zero h3
  · exact ht h3

/-- **`H_n` IS A RATIONAL FUNCTION TIMES `1/sin²`, off the real axis.**  Every `Γ` is gone.

Written without any division, so nothing here needs a nonvanishing side condition beyond the one
`asc` in the denominator — and that one is discharged on the strip by `re_pow_le_norm_asc`.  This
is `zeta2-l7-proof.md` Lemma 9's `H_n = Π·R_n·(π/sin πt)²` with `R_n` expanded. -/
theorem asc_mul_Hn (n : ℕ) {t : ℂ} (him : t.im ≠ 0)
    (h4 : asc (11 * n + 1) (t + (a₄ n : ℂ)) ≠ 0) :
    asc (11 * n + 1) (t + (a₄ n : ℂ)) * Hn n t * Complex.sin ((Real.pi : ℂ) * t) ^ 2
      = (Pi_n n : ℂ)
        * (asc (13 * n) (t + (b₁ n : ℂ)) * asc (9 * n) (t + (b₂ n : ℂ))
            * asc (5 * n) (t + (b₃ n : ℂ)))
        * (Real.pi : ℂ) ^ 2 := by
  have hsin := sin_pi_ne_zero_of_im_ne_zero him
  -- `field_simp` normalises `π * t` to `t * π` inside `sin`, so the nonvanishing fact has to be
  -- available in BOTH orientations or it leaves a live `sin · sin⁻¹` behind (measured).
  have hsin' : Complex.sin (t * (Real.pi : ℂ)) ≠ 0 := by rw [mul_comm]; exact hsin
  have hb1 : (t + (b₁ n : ℂ)).im ≠ 0 := by simpa using him
  have hb2 : (t + (b₂ n : ℂ)).im ≠ 0 := by simpa using him
  have hb3 : (t + (b₃ n : ℂ)).im ≠ 0 := by simpa using him
  have ha4 : (t + (a₄ n : ℂ)).im ≠ 0 := by simpa using him
  have g1 : Complex.Gamma (t + (a₁ n : ℂ))
      = asc (13 * n) (t + (b₁ n : ℂ)) * Complex.Gamma (t + (b₁ n : ℂ)) := by
    rw [shift_ratio_a₁]; exact Gamma_shift_nat _ hb1
  have g2 : Complex.Gamma (t + (a₂ n : ℂ))
      = asc (9 * n) (t + (b₂ n : ℂ)) * Complex.Gamma (t + (b₂ n : ℂ)) := by
    rw [shift_ratio_a₂]; exact Gamma_shift_nat _ hb2
  have g3 : Complex.Gamma (t + (a₃ n : ℂ))
      = asc (5 * n) (t + (b₃ n : ℂ)) * Complex.Gamma (t + (b₃ n : ℂ)) := by
    rw [shift_ratio_a₃]; exact Gamma_shift_nat _ hb3
  have g4 : Complex.Gamma (t + (b₄ n : ℂ))
      = asc (11 * n + 1) (t + (a₄ n : ℂ)) * Complex.Gamma (t + (a₄ n : ℂ)) := by
    rw [shift_ratio_b₄]; exact Gamma_shift_nat _ ha4
  have nb1 := Gamma_ne_zero_of_im_ne_zero hb1
  have nb2 := Gamma_ne_zero_of_im_ne_zero hb2
  have nb3 := Gamma_ne_zero_of_im_ne_zero hb3
  have na4 := Gamma_ne_zero_of_im_ne_zero ha4
  rw [Hn_eq_kernel_form n t hsin, g1, g2, g3, g4]
  -- with BOTH orientations of the `sin` nonvanishing available, `field_simp` closes this
  -- outright; a trailing `ring` is a "No goals" error, not a safety net (`skills/LEAN.md` §8).
  field_simp [hsin']

/-! ## §9. THE DECAY BOUND -/

/-- Lemma 9's decay constant for `H_n`.  It is enormous and that is fine: it is a per-`n`
constant multiplying `e^{−5|Im t|}`, so it dies against `T → ∞` at fixed `n`, and nothing
downstream ever sees it (this row proves an EQUALITY of integrals, not a bound). -/
noncomputable def Kn (n : ℕ) : ℝ :=
  16 * Real.pi ^ 2 * Pi_n n * (Nat.factorial (27 * n) : ℝ) * Real.exp (23 * (n : ℝ) + 2)

/-- **`zeta2-l7-proof.md` Lemma 9's horizontal-decay estimate.**

`‖H_n(t)‖ ≤ K_n e^{−5|Im t|}` on the closed strip `−6n − 1/2 ≤ Re t ≤ −4n − 1/2`, once
`|Im t| ≥ 1`.  The strip is stated at `6` rather than at `σ̃` because `σ̃ < 6` and nothing in the
estimate is tight — the write-up's own `e^{−2πT}` is cut to `e^{−5T}`, spending `2π > 6` on the
kernel (via `π > 3`) and one whole unit of it on the polynomial (§5).

The four ingredients: §8 removes every `Γ`; §2's upper bound handles the `27n` numerator factors;
§2's lower bound gives `‖(t+a₄)_{11n+1}‖ ≥ 1` for the `11n+1` denominator ones; §4 gives
`‖sin πt‖ ≥ e^{3|Im t|}/4`. -/
theorem norm_Hn_decay {n : ℕ} (hn : 1 ≤ n) {t : ℂ}
    (hL : -6 * (n : ℝ) - 1 / 2 ≤ t.re) (hR : t.re ≤ -4 * (n : ℝ) - 1 / 2)
    (him : 1 ≤ |t.im|) :
    ‖Hn n t‖ ≤ Kn n * Real.exp (-5 * |t.im|) := by
  have hN : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
  have ha0 : (0 : ℝ) ≤ |t.im| := abs_nonneg _
  have himne : t.im ≠ 0 := by
    intro h; rw [h, abs_zero] at him; linarith
  have hPi : 0 < Pi_n n := L7MidM4.Pi_n_pos n
  -- (1) the strip controls ‖t‖
  have hnormt : ‖t‖ ≤ 6 * (n : ℝ) + 1 / 2 + |t.im| := by
    have hre : |t.re| ≤ 6 * (n : ℝ) + 1 / 2 := by
      rw [abs_of_nonpos (by linarith)]
      linarith
    calc ‖t‖ = ‖((t.re : ℝ) : ℂ) + ((t.im : ℝ) : ℂ) * Complex.I‖ := by rw [Complex.re_add_im]
      _ ≤ ‖((t.re : ℝ) : ℂ)‖ + ‖((t.im : ℝ) : ℂ) * Complex.I‖ := norm_add_le _ _
      _ = |t.re| + |t.im| := by
          simp [Complex.norm_real, Real.norm_eq_abs, Complex.norm_I]
      _ ≤ 6 * (n : ℝ) + 1 / 2 + |t.im| := by linarith
  have hshiftnorm : ∀ c : ℕ, ‖t + (c : ℂ)‖ ≤ 6 * (n : ℝ) + 1 / 2 + |t.im| + (c : ℝ) := by
    intro c
    refine le_trans (norm_add_le _ _) ?_
    have hc : ‖((c : ℕ) : ℂ)‖ = (c : ℝ) := by simp
    rw [hc]
    linarith
  -- (2) the 27n numerator factors
  have hasc : ∀ c d : ℕ, (c : ℝ) + (d : ℝ) ≤ 17 * (n : ℝ) + 3 / 2 →
      ‖asc d (t + (c : ℂ))‖ ≤ (23 * (n : ℝ) + 2 + |t.im|) ^ d := by
    intro c d hcd
    refine le_trans (norm_asc_le d (t + (c : ℂ))) (pow_mono_base (by positivity) ?_ d)
    have h := hshiftnorm c
    linarith
  have hA1 := hasc (b₁ n) (13 * n) (by simp only [b₁]; push_cast; linarith)
  have hA2 := hasc (b₂ n) (9 * n) (by simp only [b₂]; push_cast; linarith)
  have hA3 := hasc (b₃ n) (5 * n) (by simp only [b₃]; push_cast; linarith)
  -- (3) the 11n+1 denominator factors are each ≥ 9n + 1/2 ≥ 1
  have hre4 : (9 : ℝ) ≤ (t + (a₄ n : ℂ)).re := by
    have hcast : ((a₄ n : ℕ) : ℝ) = 15 * (n : ℝ) + 1 := by simp only [a₄]; push_cast; ring
    rw [Complex.add_re, Complex.natCast_re, hcast]
    linarith
  have h4ge : (1 : ℝ) ≤ ‖asc (11 * n + 1) (t + (a₄ n : ℂ))‖ := by
    have h1 := re_pow_le_norm_asc (11 * n + 1) (z := t + (a₄ n : ℂ)) (by linarith)
    have h2 : (1 : ℝ) ^ (11 * n + 1) ≤ (t + (a₄ n : ℂ)).re ^ (11 * n + 1) :=
      pow_mono_base zero_le_one (by linarith) _
    simpa using le_trans h2 h1
  have h4ne : asc (11 * n + 1) (t + (a₄ n : ℂ)) ≠ 0 := by
    intro h; rw [h, norm_zero] at h4ge; linarith
  -- (4) the kernel
  have hsinlb : Real.exp (3 * |t.im|) / 4 ≤ ‖Complex.sin ((Real.pi : ℂ) * t)‖ := by
    have hz : ((Real.pi : ℂ) * t).im = Real.pi * t.im := by simp [Complex.mul_im]
    have habs : |((Real.pi : ℂ) * t).im| = Real.pi * |t.im| := by
      rw [hz, abs_mul, abs_of_nonneg Real.pi_pos.le]
    have h1 : (1 : ℝ) ≤ |((Real.pi : ℂ) * t).im| := by
      rw [habs]; nlinarith [Real.pi_gt_three]
    have h2 := exp_abs_im_le_four_mul_norm_sin h1
    rw [habs] at h2
    have h3 : Real.exp (3 * |t.im|) ≤ Real.exp (Real.pi * |t.im|) :=
      Real.exp_le_exp.mpr (by nlinarith [Real.pi_gt_three])
    linarith
  -- (5) take norms in §8's identity
  have hnorms := congrArg norm (asc_mul_Hn n himne h4ne)
  simp only [norm_mul, norm_pow, Complex.norm_real, Real.norm_eq_abs,
    abs_of_nonneg hPi.le, abs_of_nonneg Real.pi_pos.le] at hnorms
  have hprod : ‖asc (13 * n) (t + (b₁ n : ℂ))‖ * ‖asc (9 * n) (t + (b₂ n : ℂ))‖
      * ‖asc (5 * n) (t + (b₃ n : ℂ))‖ ≤ (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n) := by
    have hpow : (23 * (n : ℝ) + 2 + |t.im|) ^ (13 * n) * (23 * (n : ℝ) + 2 + |t.im|) ^ (9 * n)
        * (23 * (n : ℝ) + 2 + |t.im|) ^ (5 * n) = (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n) := by
      rw [← pow_add, ← pow_add]
      congr 1
      ring
    refine le_trans ?_ (le_of_eq hpow)
    refine mul_le_mul (mul_le_mul hA1 hA2 (norm_nonneg _) (by positivity)) hA3
      (norm_nonneg _) (by positivity)
  have hstep : ‖Hn n t‖ * (Real.exp (3 * |t.im|) / 4) ^ 2
      ≤ Pi_n n * (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n) * Real.pi ^ 2 := by
    have e1 : (Real.exp (3 * |t.im|) / 4) ^ 2 ≤ ‖Complex.sin ((Real.pi : ℂ) * t)‖ ^ 2 :=
      pow_mono_base (by positivity) hsinlb 2
    have e2 : ‖Hn n t‖ ≤ ‖asc (11 * n + 1) (t + (a₄ n : ℂ))‖ * ‖Hn n t‖ := by
      nlinarith [norm_nonneg (Hn n t)]
    calc ‖Hn n t‖ * (Real.exp (3 * |t.im|) / 4) ^ 2
        ≤ ‖Hn n t‖ * ‖Complex.sin ((Real.pi : ℂ) * t)‖ ^ 2 :=
          mul_le_mul_of_nonneg_left e1 (norm_nonneg _)
      _ ≤ ‖asc (11 * n + 1) (t + (a₄ n : ℂ))‖ * ‖Hn n t‖
            * ‖Complex.sin ((Real.pi : ℂ) * t)‖ ^ 2 :=
          mul_le_mul_of_nonneg_right e2 (by positivity)
      _ = Pi_n n * (‖asc (13 * n) (t + (b₁ n : ℂ))‖ * ‖asc (9 * n) (t + (b₂ n : ℂ))‖
            * ‖asc (5 * n) (t + (b₃ n : ℂ))‖) * Real.pi ^ 2 := hnorms
      _ ≤ Pi_n n * (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n) * Real.pi ^ 2 := by
          exact mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_left hprod hPi.le)
            (by positivity)
  -- (6) divide out the kernel and absorb the polynomial
  have hexp2 : Real.exp (3 * |t.im|) ^ 2 = Real.exp (6 * |t.im|) := by
    rw [sq, ← Real.exp_add]; ring_nf
  have hEsq : (Real.exp (3 * |t.im|) / 4) ^ 2 = Real.exp (6 * |t.im|) / 16 := by
    rw [div_pow, hexp2]; norm_num
  rw [hEsq] at hstep
  have hcancel : ‖Hn n t‖ * (Real.exp (6 * |t.im|) / 16) * (16 * Real.exp (-(6 * |t.im|)))
      = ‖Hn n t‖ := by
    rw [Real.exp_neg]
    field_simp
  have h1 := mul_le_mul_of_nonneg_right hstep
    (show (0 : ℝ) ≤ 16 * Real.exp (-(6 * |t.im|)) by positivity)
  rw [hcancel] at h1
  have hB : (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n)
      ≤ (Nat.factorial (27 * n) : ℝ) * (Real.exp (23 * (n : ℝ) + 2) * Real.exp |t.im|) := by
    have h := pow_le_factorial_mul_exp (27 * n)
      (show (0 : ℝ) ≤ 23 * (n : ℝ) + 2 + |t.im| by positivity)
    rwa [show Real.exp (23 * (n : ℝ) + 2 + |t.im|)
      = Real.exp (23 * (n : ℝ) + 2) * Real.exp |t.im| by rw [← Real.exp_add]] at h
  have hcollapse : Real.exp |t.im| * Real.exp (-(6 * |t.im|)) = Real.exp (-5 * |t.im|) := by
    rw [← Real.exp_add]; ring_nf
  calc ‖Hn n t‖
      ≤ Pi_n n * (23 * (n : ℝ) + 2 + |t.im|) ^ (27 * n) * Real.pi ^ 2
          * (16 * Real.exp (-(6 * |t.im|))) := h1
    _ ≤ Pi_n n * ((Nat.factorial (27 * n) : ℝ)
            * (Real.exp (23 * (n : ℝ) + 2) * Real.exp |t.im|)) * Real.pi ^ 2
          * (16 * Real.exp (-(6 * |t.im|))) := by
        refine mul_le_mul_of_nonneg_right ?_ (by positivity)
        exact mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_left hB hPi.le) (by positivity)
    _ = Kn n * Real.exp (-5 * |t.im|) := by
        rw [Kn, ← hcollapse]
        ring

/-! ## §10. LEMMA 9 -/

/-- **`zeta2-l7-proof.md` §5, Lemma 9 — the contour move, for every `n ≥ 1`.**

`∫_ℝ H_n(−σ̃n − 1/2 + is) ds = ∫_ℝ H_n(−4n − 1/2 + is) ds`.

The left-hand contour is route B's (M4's `contourB`, in the write-up's ordinate `s` — see
`L7MidM4.contourB_ordinate`); the right-hand one is route A's, which is where
`zeta2-l7-proof.md` §1 DEFINES `r_n`.  So this is the statement that lets `r_n` be defined at
either line, and it is what makes M5's `hrep` a statement about the chain's `r_n` rather than
about a differently-defined object.

Hypotheses: `σ̃ ≤ 9` (M2's analyticity, the only place `σ ≤ 9` is spent) and `1 ≤ n` (the decay
estimate, which needs the strip to be nonempty and `9n + 1/2 ≥ 1`). -/
theorem lemma9 {n : ℕ} (hn : 1 ≤ n) :
    (∫ s : ℝ, Hn n (((-(sigT * (n : ℝ)) - 1 / 2 : ℝ) : ℂ) + (s : ℂ) * Complex.I))
      = ∫ s : ℝ, Hn n (((-4 * (n : ℝ) - 1 / 2 : ℝ) : ℂ) + (s : ℂ) * Complex.I) := by
  have hN : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
  have hsig6 : sigT < 6 := by norm_num [sigT]
  have hsig4 : (4 : ℝ) < sigT := by norm_num [sigT]
  refine line_integral_eq_of_exp_decay (K := Kn n) (c := 5) (by nlinarith) (by norm_num)
    ?_ ?_
  · refine (differentiableOn_Hn n (show sigT ≤ 9 by norm_num [sigT])).mono ?_
    rintro z ⟨hz1, hz2⟩
    exact ⟨by linarith, hz2⟩
  · intro z h1 h2 h3
    exact norm_Hn_decay hn (by nlinarith) h2 h3

/-- **Lemma 9 in M4's contour vocabulary**, so M5 can move between the two lines without
re-deriving the ordinate substitution.  `L7MidM4.contourB_ordinate` is the bridge. -/
theorem lemma9_contourB {n : ℕ} (hn : 1 ≤ n) :
    (∫ s : ℝ, Hn n (L7MidM4.contourB n (s / (n : ℝ))))
      = ∫ s : ℝ, Hn n (((-4 * (n : ℝ) - 1 / 2 : ℝ) : ℂ) + (s : ℂ) * Complex.I) := by
  rw [← lemma9 hn]
  congr 1
  funext s
  rw [L7MidM4.contourB_ordinate hn s]

/-! ## §11. EDGE CASES (`skills/LEAN.md` §5) — asked of the real data, not assumed -/

/-- **EDGE, `s = 0`: the ONE point where the estimate cannot be run, and it does not matter.**
The decay bound goes through `1/‖sin πt‖`, which is why it is stated for `|Im t| ≥ 1`; at
`Im t = 0` on the route-A line `Re t = −4n − 1/2` the kernel form's `‖sin πt‖` is in fact `1`,
but on route B's line it is `|sin(π(σ̃n + 1/2))|`, which the write-up bounds below only through
Lemma 3.2's odd-`q̃` separation — the argument `zeta2-l7-middle.md` §3a retired.  §6's compact
core is what makes that irrelevant: `H_n` is CONTINUOUS across `Im t = 0` (it is `Hn`, defined in
the reflected form, not the kernel form), so `IsCompact.exists_bound_of_continuousOn` supplies a
bound there with no arithmetic at all.  Recorded as the theorem that `H_n` is defined — indeed
zero — at exactly the points the kernel form is not. -/
theorem no_separation_needed (n : ℕ) (m : ℤ) : Hn n (m : ℂ) = 0 :=
  Hn_defined_at_integer n m

/-- **EDGE, `n = 0`, and it FAILS — deliberately.**  M2's analyticity needs no `1 ≤ n`
(`differentiableOn_Hn_at_zero`), so the question is asked rather than assumed.  Here `1 ≤ n` IS
load-bearing, and for a reason that belongs to this row rather than to M3: at `n = 0` the strip
`−1/2 ≤ Re t ≤ −1/2` is a single LINE, the two contours of Lemma 9 COINCIDE, and the statement is
a triviality rather than a contour move.  `L7MidM4.strip_nonempty` is the positive half of this;
recorded here as the arithmetic fact that the two abscissae are equal at `n = 0`. -/
theorem contours_coincide_at_zero :
    -(sigT * ((0 : ℕ) : ℝ)) - 1 / 2 = -4 * ((0 : ℕ) : ℝ) - 1 / 2 := by
  norm_num

/-- **EDGE, the decay exponent.**  `zeta2-l7-proof.md` Lemma 9 claims `e^{−2πT}`; this row proves
`e^{−5T}`, and the gap is where the polynomial `(T + cn)^{27n}` was absorbed (§5).  The margin
that makes it work is `2π − 6 > 0` from `π > 3` plus the one unit spent on the polynomial:
`6 − 5 = 1`.  Stated as a theorem because a future tightening that spent more than one unit would
break §9 silently. -/
theorem decay_budget : (5 : ℝ) + 1 ≤ 2 * Real.pi := by
  nlinarith [Real.pi_gt_three]

/-- **The kill for that budget (rung 0: a check that cannot go red attests nothing).**  Spending
TWO units on the polynomial instead of one would need `e^{−7|Im t|}` out of the kernel, and `2π`
does not supply it: `2π < 7`.  So §9's `-5` is not slack that could absorb a second polynomial
factor — it is the whole budget minus one.

API drift note (`skills/LEAN.md` §8): the `π < 3.15` bound is **`Real.pi_lt_d2`**, not
`Real.pi_lt_315` — Mathlib names the decimal bounds by DIGIT COUNT (`pi_gt_d2`, `pi_lt_d4`,
`pi_lt_d6`, `pi_lt_d20`), the same `_dN` convention as `Real.exp_one_lt_d9`. -/
theorem decay_budget_kill : ¬ ((5 : ℝ) + 2 ≤ 2 * Real.pi) := by
  have h := Real.pi_lt_d2
  norm_num at h ⊢
  linarith

/-! ## RECEIPTS — `skills/LEAN.md` §1: exit 0 attests NOTHING, and these are emitted from inside
the file so they are regenerated on every elaboration rather than remembered from a green run. -/

#print axioms L7MidM6.pow_mono_base
#print axioms L7MidM6.asc_succ
#print axioms L7MidM6.norm_asc_le
#print axioms L7MidM6.re_pow_le_norm_asc
#print axioms L7MidM6.Gamma_ne_zero_of_im_ne_zero
#print axioms L7MidM6.Gamma_shift_nat
#print axioms L7MidM6.exp_abs_im_le_four_mul_norm_sin
#print axioms L7MidM6.pow_le_factorial_mul_exp
#print axioms L7MidM6.integrable_exp_neg_mul_abs
#print axioms L7MidM6.integrable_of_exp_decay
#print axioms L7MidM6.line_integral_eq_of_exp_decay
#print axioms L7MidM6.shift_ratio_a₁
#print axioms L7MidM6.shift_ratio_a₂
#print axioms L7MidM6.shift_ratio_a₃
#print axioms L7MidM6.shift_ratio_b₄
#print axioms L7MidM6.sin_pi_ne_zero_of_im_ne_zero
#print axioms L7MidM6.asc_mul_Hn
#print axioms L7MidM6.norm_Hn_decay
#print axioms L7MidM6.lemma9
#print axioms L7MidM6.lemma9_contourB
#print axioms L7MidM6.no_separation_needed
#print axioms L7MidM6.contours_coincide_at_zero
#print axioms L7MidM6.decay_budget
#print axioms L7MidM6.decay_budget_kill

end L7MidM6
