/-
# Row D4 (data half) — the L2 / L3 finite exact facts of the certified operator

GENERATED by external_tests/zeta2_small_rows/gen_d4_lean.py from
external_tests/chain_close_design/results/chi_artifact.txt — the four exact integer
coefficients of χ_op, the primitive integer cubic of the certified operator's leading
coefficients (docs/future/zeta2-chain-close.md §L2).  Do not hand-edit:
`gen_d4_lean.py --check` regenerates and diffs.

Every literal below is derived from those four integers by exact integer arithmetic, and
`norm_num` re-does all of it.  The general lemmas that CONSUME these facts (L12's arithmetic,
L4's dominance criterion) are in `Zeta2D4.lean`.
-/
import Mathlib.Tactic.NormNum

namespace Zeta2D4Data

/-- `ℓ_0`, the λ^0 coefficient of χ_op (84 digits). -/
def l0 : ℤ :=
  179675601764063309680388847331568994349427602132617142760339179746063577052666015625

/-- `ℓ_1`, the λ^1 coefficient of χ_op (97 digits). -/
def l1 : ℤ :=
  1534700302959727782777662542613996667933123242487888812757468773330982525824403026766192862443008

/-- `ℓ_2`, the λ^2 coefficient of χ_op (109 digits). -/
def l2 : ℤ :=
  3445599956405225181380741309815710101060769026997421483623964592400375119506765245290307730924197436449685504

/-- `ℓ_3`, the λ^3 coefficient of χ_op (91 digits). -/
def l3 : ℤ :=
  1915567470601676011932609085977123493692093614518627379378235356322201600000000000000000000

/-- χ_op evaluated at a rational point. -/
def chiOp (x : ℚ) : ℚ := (l3 : ℚ) * x ^ 3 + (l2 : ℚ) * x ^ 2 + (l1 : ℚ) * x + (l0 : ℚ)

/--
**L2 — the recurrence is Poincaré-class.**  The leading coefficient of the limiting
characteristic cubic is nonzero, which is the hypothesis `deg P_j` all equal and `ℓ₃ ≠ 0`
delivers.  All four coefficients are in fact strictly positive, which is what forces the
unique real root to be NEGATIVE (the operator convention recorded in the artifact).
-/
theorem chiOp_coeffs_pos : 0 < l0 ∧ 0 < l1 ∧ 0 < l2 ∧ 0 < l3 := by
  refine ⟨?_, ?_, ?_, ?_⟩ <;> norm_num [l0, l1, l2, l3]

/-- `ℓ₃ ≠ 0` on its own, the form L4's Poincaré-class step consumes. -/
theorem chiOp_leading_ne_zero : l3 ≠ 0 := by
  norm_num [l3]

/--
**L3 — exactly one real root.**  The cubic discriminant of χ_op is strictly negative,
which for a real cubic is equivalent to one real root and one complex-conjugate pair.
Stated with every term moved to the side on which it is positive, so `norm_num` decides an
inequality between two 409-digit positive integers with no cancellation.
-/
theorem chiOp_disc_neg :
    18 * l3 * l2 * l1 * l0 + l2 ^ 2 * l1 ^ 2 <
      4 * l2 ^ 3 * l0 + 4 * l3 * l1 ^ 3 + 27 * l3 ^ 2 * l0 ^ 2 := by
  norm_num [l0, l1, l2, l3]

/--
**L3 — the real root, enclosed.**  `χ_op` changes sign on `[-1798735888599616356, -1798735888599616355]`, so its unique real
root `−|λ₁|` lies strictly inside: `1798735888599616355 < |λ₁| < 1798735888599616356`.  The two endpoints are consecutive
integers, so this is the exact integer part of `|λ₁|` — a relative width of 6e-19, which is
what the chain's `C1 = log|λ₁|` needs (its own budget is ~1e-9; see `Zeta2D4.lean`).
-/
theorem chiOp_root_enclosure : chiOp (-1798735888599616356) < 0 ∧ 0 < chiOp (-1798735888599616355) := by
  constructor <;> norm_num [chiOp, l0, l1, l2, l3]

/--
**L3 — the certified modulus gap `|pair| < |λ₁|`.**  By Vieta the product of the three roots
is `−ℓ₀/ℓ₃`, so `|λ₁| · |pair|² = ℓ₀/ℓ₃` and the gap is equivalent to `ℓ₀/ℓ₃ < |λ₁|³`.  With
the enclosure above it suffices that `ℓ₀ < ℓ₃ · 1798735888599616355³`, which is what this decides.
-/
theorem chiOp_modulus_gap : l0 < l3 * 1798735888599616355 ^ 3 := by
  norm_num [l0, l3]

/--
**L3 — `|pair|²`, enclosed.**  `|pair|² = (ℓ₀/ℓ₃)/|λ₁|`, and `|λ₁|` is enclosed above, so
the two rational endpoints bracket it.  Written against decimal fractions with a strict
margin on each side.
-/
theorem chiOp_pair_sq_lower : (52146390770075886020 : ℚ) / 10 ^ 45 < (l0 : ℚ) / ((l3 : ℚ) * 1798735888599616356) := by
  norm_num [l0, l3]

/-- The upper endpoint of the same enclosure. -/
theorem chiOp_pair_sq_upper : (l0 : ℚ) / ((l3 : ℚ) * 1798735888599616355) < (52146390770075886050 : ℚ) / 10 ^ 45 := by
  norm_num [l0, l3]

/-! ### Receipts (LEAN.md §1 — exit 0 is not an attestation) -/

#print axioms chiOp_coeffs_pos
#print axioms chiOp_leading_ne_zero
#print axioms chiOp_disc_neg
#print axioms chiOp_root_enclosure
#print axioms chiOp_modulus_gap
#print axioms chiOp_pair_sq_lower
#print axioms chiOp_pair_sq_upper

end Zeta2D4Data
