/-
# Row PT-P, layer 11 — `KummerRowsOpen`'s two sides as functions of THREE RESIDUES

`Zeta2PtpKummer.KummerRowsOpen` compares `φ̃ + b_r − 1 + v_p(L·C(m,L))` with the units count
`kumLo`/`kumHi` of each term of `h_m`.  At a row `(n, p, r)` with `m = 11n+1+r < p²` every quantity
in it is a function of `r₀ = n % p`, `ρ = (r+1) % p` and `u = i % p`:

    Mres p r₀ ρ     = m % p
    kumLoR p r₀ ρ u = kumLo n p m i    (i ≤ 13n)          `kumLo_eq_res`
    kumHiR p r₀ ρ u = kumHi n p m i    (26n < i)          `kumHi_eq_res`
    targetR p r₀ ρ v = v + b_r − 1 + v_p(L·C(m,L))        `target_eq_res`  (v = φ̃, 1 ≤ ρ)

so the open statement becomes `∀ p r₀ ρ u, … → targetR ≤ kumLoR + 1 ∧ targetR ≤ kumHiR + 1`, a
statement `omega` can decide once the floors `⌊c·r₀/p⌋` are fixed — the stratum lemmas of
`Zeta2PtpKumS*.lean` (GENERATED by `ptp_kummer_strata.py --emit`), in `Zeta2PtpCong`'s shape.

This file is the BRIDGE only: the residue forms, the three identities, and the abstraction lemmas
that turn each `cb`/`%` into an `if` over opaque residue variables.  Nothing here is a valuation
bound.  `Zeta2Target.zeta2_not_liouvilleWith` is `sorry`.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Zeta2Defs
import Zeta2Arith
import Zeta2QnInt
import Zeta2PnHarm
import Zeta2Profile
import Zeta2PhiT
import Zeta2NewtonCarry
import Zeta2NewtonAssemble
import Zeta2PnCleared
import Zeta2PnFunc
import Zeta2PnHarmDelta
import Zeta2PhiTDvd
import Zeta2PtpPolar
import Zeta2PtpRun
import Zeta2PtpStratum
import Zeta2PtpCong
import Zeta2PtpPoly
import Zeta2PtpCoeff
import Zeta2HatCarry
import Zeta2PtpKummer

namespace Zeta2PtpKumRes

open Zeta2Defs Zeta2Arith Zeta2PhiT Zeta2PtpPolar Zeta2PtpPoly Zeta2PtpKummer Zeta2PtpRun Nat

/-! ## 1. Three `%` identities -/

/-- `(c·n) % p` depends on `n` only through `n % p`. -/
theorem mul_mod_res (c n p : ℕ) : (c * n) % p = (c * (n % p)) % p := by
  rw [Nat.mul_mod, Nat.mul_mod c (n % p), Nat.mod_mod]

/-- **A difference's residue as ONE comparison**, for `b ≤ a`. -/
theorem sub_mod_split {p a b : ℕ} (hp : 0 < p) (hba : b ≤ a) :
    (a - b) % p = if b % p ≤ a % p then a % p - b % p else a % p + p - b % p := by
  have hap := Nat.mod_lt a hp
  have hbp := Nat.mod_lt b hp
  have key : ∀ t, t < p → (t + b) % p = a % p → (a - b) % p = t := by
    intro t ht h
    have h1 : (a - b + b) % p = (t + b) % p := by rw [Nat.sub_add_cancel hba, h]
    have h2 : (a - b) % p = t % p := Nat.ModEq.add_right_cancel' b h1
    rw [h2]
    exact Nat.mod_eq_of_lt ht
  split_ifs with h
  · refine key _ (by omega) ?_
    rw [Nat.add_mod, Nat.mod_eq_of_lt (show a % p - b % p < p by omega),
      show a % p - b % p + b % p = a % p by omega, Nat.mod_mod]
  · refine key _ (by omega) ?_
    rw [Nat.add_mod, Nat.mod_eq_of_lt (show a % p + p - b % p < p by omega),
      show a % p + p - b % p + b % p = a % p + p by omega, Nat.add_mod_right, Nat.mod_mod]

/-- `(a + p − u) % p` for `a, u < p`. -/
theorem wrap_mod {p a u : ℕ} (hu : u < p) (ha : a < p) :
    (a + p - u) % p = if u ≤ a then a - u else a + p - u := by
  split_ifs with h
  · rw [show a + p - u = (a - u) + p by omega, Nat.add_mod_right]
    exact Nat.mod_eq_of_lt (by omega)
  · exact Nat.mod_eq_of_lt (by omega)

/-- `a % p` for `a < 2p`, as one comparison. -/
theorem mod_of_lt_two_mul {p a : ℕ} (h : a < 2 * p) : a % p = if a < p then a else a - p := by
  split_ifs with h1
  · exact Nat.mod_eq_of_lt h1
  · conv_lhs => rw [show a = (a - p) + p by omega]
    rw [Nat.add_mod_right]
    exact Nat.mod_eq_of_lt (by omega)

/-! ## 2. The residue forms -/

/-- `m % p` from `r₀` and `ρ`. -/
def Mres (p r ρ : ℕ) : ℕ := ((11 * r) % p + ρ) % p

/-- `kumLo` in residues: `[M < u] + [(R₂₆ − u) mod p < R₁₃] + [(R₂₄ − u) mod p < R₉] + [(R₂₂ − u) mod p < R₅]`. -/
def kumLoR (p r ρ u : ℕ) : ℕ :=
  (if Mres p r ρ < u then 1 else 0)
    + cb p ((26 * r) % p + p - u) (13 * r)
    + cb p ((24 * r) % p + p - u) (9 * r)
    + cb p ((22 * r) % p + p - u) (5 * r)

/-- `kumHi` in residues: `(u − R_c − 1) mod p` is `(u + p − 1 − R_c) % p`. -/
def kumHiR (p r ρ u : ℕ) : ℕ :=
  (if Mres p r ρ < u then 1 else 0)
    + cb p (u + p - 1 - (13 * r) % p) (13 * r)
    + cb p (u + p - 1 - (15 * r) % p) (9 * r)
    + cb p (u + p - 1 - (17 * r) % p) (5 * r)

/-- The target in residues: `v + [ρ ≤ R₁₁] − 1 + [p ≤ R₁₁ + ρ]`. -/
def targetR (p r ρ v : ℕ) : ℕ :=
  v + (if ρ ≤ (11 * r) % p then 1 else 0) - 1 + (if p ≤ (11 * r) % p + ρ then 1 else 0)

/-! ## 3. The bridge, term side -/

theorem Mres_eq (n p r : ℕ) : (11 * n + 1 + r) % p = Mres p (n % p) ((r + 1) % p) := by
  rw [Mres, show 11 * n + 1 + r = 11 * n + (r + 1) by ring, Nat.add_mod, mul_mod_res 11 n p]

theorem cb_sub_eq {n p i c d : ℕ} (hp : 0 < p) (hi : i ≤ c * n) :
    cb p (c * n - i) (d * n) = cb p ((c * (n % p)) % p + p - i % p) (d * (n % p)) := by
  have hip := Nat.mod_lt i hp
  have hcp := Nat.mod_lt (c * (n % p)) hp
  unfold cb
  rw [sub_mod_split hp hi, mul_mod_res c n p, mul_mod_res d n p, wrap_mod hip hcp]

theorem cb_sub_eq' {n p i c d : ℕ} (hp1 : 1 < p) (hi : c * n + 1 ≤ i) :
    cb p (i - c * n - 1) (d * n) = cb p (i % p + p - 1 - (c * (n % p)) % p) (d * (n % p)) := by
  have hp : 0 < p := by omega
  have hip := Nat.mod_lt i hp
  have hRp := Nat.mod_lt (c * (n % p)) hp
  unfold cb
  rw [show i - c * n - 1 = i - (c * n + 1) by omega, sub_mod_split hp hi, mul_mod_res d n p,
    Nat.add_mod (c * n) 1 p, mul_mod_res c n p, Nat.mod_eq_of_lt hp1,
    Zeta2PtpCong.add_mod_split hRp (by omega : 1 ≤ p),
    mod_of_lt_two_mul (a := i % p + p - 1 - (c * (n % p)) % p) (by omega)]
  split_ifs <;> omega

/-- **`kumLo` at a row IS `kumLoR` at its residues.** -/
theorem kumLo_eq_res {n p r i : ℕ} (hp : 0 < p) (hi : i ≤ 13 * n) :
    kumLo n p (11 * n + 1 + r) i = kumLoR p (n % p) ((r + 1) % p) (i % p) := by
  unfold kumLo kumLoR
  rw [cb_sub_eq hp (by omega : i ≤ 26 * n), cb_sub_eq hp (by omega : i ≤ 24 * n),
    cb_sub_eq hp (by omega : i ≤ 22 * n)]
  congr 3
  unfold cb
  rw [Mres_eq]

/-- **`kumHi` at a row IS `kumHiR` at its residues.** -/
theorem kumHi_eq_res {n p r i : ℕ} (hp1 : 1 < p) (hi : 26 * n < i) :
    kumHi n p (11 * n + 1 + r) i = kumHiR p (n % p) ((r + 1) % p) (i % p) := by
  unfold kumHi kumHiR
  rw [cb_sub_eq' hp1 (by omega : 13 * n + 1 ≤ i), cb_sub_eq' hp1 (by omega : 15 * n + 1 ≤ i),
    cb_sub_eq' hp1 (by omega : 17 * n + 1 ≤ i)]
  congr 3
  unfold cb
  rw [Mres_eq]

/-! ## 4. The bridge, target side -/

/-- `v_p(L) ∈ {0, 1}` for `L < p²`, and it is `1` exactly when `p ∣ L`. -/
theorem padicValNat_eq_ite_of_lt_sq {p L : ℕ} [Fact p.Prime] (hL0 : L ≠ 0) (hL : L < p ^ 2) :
    padicValNat p L = if L % p = 0 then 1 else 0 := by
  have hpp : p.Prime := Fact.out
  split_ifs with h
  · have hd : p ∣ L := Nat.dvd_of_mod_eq_zero h
    have h1 : 1 ≤ padicValNat p L := one_le_padicValNat_of_dvd hL0 hd
    have h2 : padicValNat p L < 2 := by
      by_contra hc
      have : p ^ 2 ∣ L := (pow_dvd_pow p (by omega : 2 ≤ padicValNat p L)).trans pow_padicValNat_dvd
      have := Nat.le_of_dvd (Nat.pos_of_ne_zero hL0) this
      omega
    omega
  · exact padicValNat.eq_zero_of_not_dvd (fun hd => h (Nat.mod_eq_zero_of_dvd hd))

/-- **`v_p(L·C(m,L))` at a window prime with `m < p²`**: `v_p(L)` plus one units carry bit. -/
theorem padicValNat_LC {n p r : ℕ} (hp : p ∈ phiWindow n) (hm : 11 * n + 1 + r < p ^ 2) :
    padicValNat p (LC n r)
      = (if (11 * n + 1) % p = 0 then 1 else 0) + cb p (11 * n + 1 + r) (11 * n + 1) := by
  have hpp := prime_of_mem_phiWindow hp
  have : Fact p.Prime := ⟨hpp⟩
  have hL0 : 11 * n + 1 ≠ 0 := by omega
  have hC0 : (11 * n + 1 + r).choose (11 * n + 1) ≠ 0 :=
    Nat.choose_pos (by omega) |>.ne'
  rw [LC, padicValNat.mul hL0 hC0, padicValNat_eq_ite_of_lt_sq hL0 (by omega),
    Zeta2PtpRun.vp_choose_eq_cb (by omega) (Zeta2PtpRun.log_le_one_of_lt_sq hm)]

/-- `bbit` in residues. -/
theorem bbit_eq_res (n p r : ℕ) :
    bbit n p r = if (r + 1) % p ≤ (11 * (n % p)) % p then 1 else 0 := by
  rw [bbit, mul_mod_res 11 n p]

/-- **The target at a row IS `targetR` at its residues**, for a non-polar row (`1 ≤ ρ`). -/
theorem target_eq_res {n p r : ℕ} (hp : p ∈ phiWindow n) (hm : 11 * n + 1 + r < p ^ 2)
    (hρ : 1 ≤ (r + 1) % p) (v : ℕ) :
    v + bbit n p r - 1 + padicValNat p (LC n r) = targetR p (n % p) ((r + 1) % p) v := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  have hp1 := (prime_of_mem_phiWindow hp).one_lt
  rw [padicValNat_LC hp hm, bbit_eq_res, targetR]
  have hR := Nat.mod_lt (11 * (n % p)) hp0
  have hρp := Nat.mod_lt (r + 1) hp0
  -- `(11n+1) % p = (R₁₁ + 1) % p`, `m % p = (R₁₁ + ρ) % p`, both as one comparison.
  have e1 : (11 * n + 1) % p = if (11 * (n % p)) % p + 1 < p then (11 * (n % p)) % p + 1
      else (11 * (n % p)) % p + 1 - p := by
    rw [Nat.add_mod, mul_mod_res 11 n p, Nat.mod_eq_of_lt hp1,
      Zeta2PtpCong.add_mod_split hR (by omega)]
  have e2 : (11 * n + 1 + r) % p = if (11 * (n % p)) % p + (r + 1) % p < p
      then (11 * (n % p)) % p + (r + 1) % p else (11 * (n % p)) % p + (r + 1) % p - p := by
    rw [Mres_eq, Mres, Zeta2PtpCong.add_mod_split hR (by omega)]
  -- `split_ifs` does not split an `if` nested inside another `if`'s CONDITION, so the two
  -- residues stay ATOMS in the goal and their values go to `omega` as disjunctions.
  have e1' : (11 * (n % p) % p + 1 < p ∧ (11 * n + 1) % p = 11 * (n % p) % p + 1)
      ∨ (p ≤ 11 * (n % p) % p + 1 ∧ (11 * n + 1) % p = 11 * (n % p) % p + 1 - p) := by
    rw [e1]
    split_ifs with h
    · exact Or.inl ⟨h, rfl⟩
    · exact Or.inr ⟨by omega, rfl⟩
  have e2' : (11 * (n % p) % p + (r + 1) % p < p
        ∧ (11 * n + 1 + r) % p = 11 * (n % p) % p + (r + 1) % p)
      ∨ (p ≤ 11 * (n % p) % p + (r + 1) % p
        ∧ (11 * n + 1 + r) % p = 11 * (n % p) % p + (r + 1) % p - p) := by
    rw [e2]
    split_ifs with h
    · exact Or.inl ⟨h, rfl⟩
    · exact Or.inr ⟨by omega, rfl⟩
  clear e1 e2
  unfold cb
  split_ifs <;> omega

/-! ## 5. The bridge at a POLAR row (`p ∣ r+1`): `b_r = 1` and `v_p(L·C(m,L)) = 1` -/

theorem bbit_polar {n p r : ℕ} (hpol : p ∣ r + 1) : bbit n p r = 1 := by
  rw [bbit, Nat.mod_eq_zero_of_dvd hpol]
  simp

/-- At a polar row `m ≡ L − 1 (mod p)`, so `C(m, L)` carries exactly one unit — or `p ∣ L` and
the unit is `L`'s. -/
theorem padicValNat_LC_polar {n p r : ℕ} (hp : p ∈ phiWindow n) (hm : 11 * n + 1 + r < p ^ 2)
    (hpol : p ∣ r + 1) : padicValNat p (LC n r) = 1 := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  have hp1 := (prime_of_mem_phiWindow hp).one_lt
  have hR := Nat.mod_lt (11 * n) hp0
  rw [padicValNat_LC hp hm]
  have e2 : (11 * n + 1 + r) % p = (11 * n) % p := by
    rw [show 11 * n + 1 + r = 11 * n + (r + 1) by ring, Nat.add_mod, Nat.mod_eq_zero_of_dvd hpol,
      Nat.add_zero, Nat.mod_mod]
  have e1 : (11 * n + 1) % p = if (11 * n) % p + 1 < p then (11 * n) % p + 1
      else (11 * n) % p + 1 - p := by
    rw [Nat.add_mod, Nat.mod_eq_of_lt hp1, Zeta2PtpCong.add_mod_split hR (by omega)]
  have e1' : ((11 * n) % p + 1 < p ∧ (11 * n + 1) % p = (11 * n) % p + 1)
      ∨ (p ≤ (11 * n) % p + 1 ∧ (11 * n + 1) % p = (11 * n) % p + 1 - p) := by
    rw [e1]
    split_ifs with h
    · exact Or.inl ⟨h, rfl⟩
    · exact Or.inr ⟨by omega, rfl⟩
  clear e1
  unfold cb
  rw [e2]
  split_ifs <;> omega

#print axioms Zeta2PtpKumRes.bbit_polar
#print axioms Zeta2PtpKumRes.padicValNat_LC_polar
#check @Zeta2PtpKumRes.padicValNat_LC_polar
#print axioms Zeta2PtpKumRes.sub_mod_split
#print axioms Zeta2PtpKumRes.wrap_mod
#print axioms Zeta2PtpKumRes.kumLo_eq_res
#check @Zeta2PtpKumRes.kumLo_eq_res
#print axioms Zeta2PtpKumRes.kumHi_eq_res
#check @Zeta2PtpKumRes.kumHi_eq_res
#print axioms Zeta2PtpKumRes.padicValNat_LC
#check @Zeta2PtpKumRes.padicValNat_LC
#print axioms Zeta2PtpKumRes.target_eq_res
#check @Zeta2PtpKumRes.target_eq_res

end Zeta2PtpKumRes
