/-
# Row PT-P, layer 18 — the φ̃ = 2 run stratum `S2a2` `[3/26, 2/17)` CLOSED below `p²`

GENERATED by `gen_ptp_runs2.py` — edit the generator, not this file.  One stratum per module so a
falsifier arm re-elaborates one stratum; `Zeta2PtpRunS2.lean` composes the five.  The mechanism is
in `Zeta2PtpRunS2.lean`'s header.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Zeta2PtpRunG2
import Zeta2PtpResPair
import Zeta2PtpS2a

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

namespace Zeta2PtpRunS2

open Zeta2PtpRunG2 Zeta2PtpBlock Zeta2PtpS7 Zeta2PtpRunBlock Zeta2PtpS2Kit Finset Polynomial

/-! ## Stratum `S2a2`: `3/26 ≤ s/p < 2/17`, carried factor C(22n−i, 5n) / C(i−17n−1, 5n) -/

section S2a2
variable {p : ℕ} [hp : Fact p.Prime]

theorem S2a2_res {n a s : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p) :
    (5 * n) % p = 5 * s - 0 * p ∧ (9 * n) % p = 9 * s - 1 * p ∧ (11 * n) % p = 11 * s - 1 * p ∧ (13 * n) % p = 13 * s - 1 * p ∧ (22 * n) % p = 22 * s - 2 * p ∧ (24 * n) % p = 24 * s - 2 * p ∧ (26 * n) % p = 26 * s - 3 * p := by
  have hp0 := hp.out.pos
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact res_mul hp0 (S := 5 * s) (A := 5 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 9 * s) (A := 9 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 11 * s) (A := 11 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 13 * s) (A := 13 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 22 * s) (A := 22 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 24 * s) (A := 24 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 26 * s) (A := 26 * a) (by rw [hn]; ring) (by omega) (by omega)

theorem S2a2_resT {n a s : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p) :
    (((13 * n + 1) % p = 13 * s - 1 * p + 1 ∧ 13 * s - 1 * p + 1 < p) ∨ ((13 * n + 1) % p = 0 ∧ 13 * s + 1 = 1 * p + p))
    ∧ (((15 * n + 1) % p = 15 * s - 1 * p + 1 ∧ 15 * s - 1 * p + 1 < p) ∨ ((15 * n + 1) % p = 0 ∧ 15 * s + 1 = 1 * p + p))
    ∧ (((17 * n + 1) % p = 17 * s - 1 * p + 1 ∧ 17 * s - 1 * p + 1 < p) ∨ ((17 * n + 1) % p = 0 ∧ 17 * s + 1 = 1 * p + p)) := by
  have hp0 := hp.out.pos
  refine ⟨?_, ?_, ?_⟩
  · exact res_succ hp0 (S := 13 * s) (A := 13 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_succ hp0 (S := 15 * s) (A := 15 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_succ hp0 (S := 17 * s) (A := 17 * a) (by rw [hn]; ring) (by omega) (by omega)

theorem S2a2_deg {n m a s : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p) (hm : m % p = (11 * n) % p) :
    (p - 1 - m % p) + (13 * n) % p + (9 * n) % p + (5 * n) % p ≤ 2 * p - 2 := by
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2a2_res hn h1 h2
  rw [hm, r5, r9, r11, r13]
  omega

theorem S2a2_lo {n m a s : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p) (hm : m % p = (11 * n) % p) :
    (∀ u < p, cLo1 p n u ∨ cLo2 p n u ∨ cLo3 p n u ∨ c4 p m u)
    ∧ (∀ u < p, ¬ cLo3 p n u → (cLo1 p n u ∧ cLo2 p n u) ∨ (cLo1 p n u ∧ c4 p m u) ∨ (cLo2 p n u ∧ c4 p m u)) := by
  obtain ⟨r5, r9, r11, r13, r22, r24, r26⟩ := S2a2_res hn h1 h2
  refine ⟨fun u hu => ?_, fun u hu => ?_⟩ <;>
  · unfold cLo1 cLo2 cLo3 c4
    rw [hm, r11, r13, r26, r9, r24, r5, r22,
      wrap_mod_down hu (show 26 * s - 3 * p < p by omega),
      wrap_mod_down hu (show 24 * s - 2 * p < p by omega),
      wrap_mod_down hu (show 22 * s - 2 * p < p by omega)]
    split_ifs <;> omega

theorem S2a2_hi {n m a s : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p) (hm : m % p = (11 * n) % p) :
    (∀ u < p, cHi1 p n u ∨ cHi2 p n u ∨ cHi3 p n u ∨ c4 p m u)
    ∧ (∀ u < p, ¬ cHi3 p n u → (cHi1 p n u ∧ cHi2 p n u) ∨ (cHi1 p n u ∧ c4 p m u) ∨ (cHi2 p n u ∧ c4 p m u)) := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2a2_res hn h1 h2
  obtain ⟨d13, d15, d17⟩ := S2a2_resT hn h1 h2
  have q13 := Nat.mod_lt (13 * n + 1) hp0
  have q15 := Nat.mod_lt (15 * n + 1) hp0
  have q17 := Nat.mod_lt (17 * n + 1) hp0
  refine ⟨fun u hu => ?_, fun u hu => ?_⟩ <;>
  · unfold cHi1 cHi2 cHi3 c4
    rw [hm, r11, r13, r9, r5, wrap_mod_up hu q13, wrap_mod_up hu q15, wrap_mod_up hu q17]
    generalize (13 * n + 1) % p = Q13 at *
    generalize (15 * n + 1) % p = Q15 at *
    generalize (17 * n + 1) % p = Q17 at *
    split_ifs <;> omega

theorem S2a2_lo_hsup {n m a s t u : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p)
    (hpa : 26 * 26 * a + 26 * 3 < 26 * p) (hm : m % p = (11 * n) % p)
    (ht : t ≤ 13 * a + 1) (hu : u < p) : cLo3 p n u → ¬ cLo1 p n u → ¬ cLo2 p n u → ¬ c4 p m u →
      t * p + u ≤ 22 * n ∧ (26 * n - (t * p + u)) / p = 26 * a + 2 - t
      ∧ (24 * n - (t * p + u)) / p = 24 * a + 2 - t ∧ (22 * n - (t * p + u)) / p = 22 * a + 2 - t := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, r22, r24, r26⟩ := S2a2_res hn h1 h2
  intro hk ho1 ho2 ho3
  unfold cLo1 cLo2 cLo3 c4 at *
  rw [r22, r5, wrap_mod_down hu (show 22 * s - 2 * p < p by omega)] at hk
  rw [r26, r13, wrap_mod_down hu (show 26 * s - 3 * p < p by omega)] at ho1
  rw [r24, r9, wrap_mod_down hu (show 24 * s - 2 * p < p by omega)] at ho2
  rw [hm, r11] at ho3
  have hT : t * p ≤ (13 * a + 1) * p := Nat.mul_le_mul_right p ht
  have e13 : (13 * a + 1) * p = 13 * (p * a) + 1 * p := by ring
  have g26 : (26 * a + 2) * p = 26 * (p * a) + 2 * p := by ring
  have g24 : (24 * a + 2) * p = 24 * (p * a) + 2 * p := by ring
  have g22 : (22 * a + 2) * p = 22 * (p * a) + 2 * p := by ring
  split_ifs at hk ho1 ho2 ho3 <;>
  exact ⟨by omega, div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega)⟩

theorem S2a2_lo_h3 {n a s t : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p)
    (hpa : 26 * 26 * a + 26 * 3 < 26 * p) (ht : t ≤ 13 * a + 1) :
    5 * n / p < 22 * a + 2 - t ∧ 22 * a + 2 - t < p := by
  have hp0 := hp.out.pos
  have hdq : 5 * n / p = 5 * a + 0 := by
    have e : (5 * a + 0) * p = 5 * (p * a) + 0 * p := by ring
    exact div_of_lin hp0 (r := 5 * s - 0 * p) (by rw [hn]; omega) (by omega)
  omega

theorem S2a2_hi_hsup {n m a s t u : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p)
    (hm : m % p = (11 * n) % p) (ht : 26 * a + 3 ≤ t) (htp : t < p) (hu : u < p) :
    cHi3 p n u → ¬ cHi1 p n u → ¬ cHi2 p n u → ¬ c4 p m u →
      17 * n + 1 ≤ t * p + u ∧ (t * p + u - (13 * n + 1)) / p = t - (13 * a + 2)
      ∧ (t * p + u - (15 * n + 1)) / p = t - (15 * a + 2) ∧ (t * p + u - (17 * n + 1)) / p = t - (17 * a + 2) := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2a2_res hn h1 h2
  obtain ⟨d13, d15, d17⟩ := S2a2_resT hn h1 h2
  have q13 := Nat.mod_lt (13 * n + 1) hp0
  have q15 := Nat.mod_lt (15 * n + 1) hp0
  have q17 := Nat.mod_lt (17 * n + 1) hp0
  intro hk ho1 ho2 ho3
  unfold cHi1 cHi2 cHi3 c4 at *
  rw [r5, wrap_mod_up hu q17] at hk
  rw [r13, wrap_mod_up hu q13] at ho1
  rw [r9, wrap_mod_up hu q15] at ho2
  rw [hm, r11] at ho3
  have hT : (26 * a + 3) * p ≤ t * p := Nat.mul_le_mul_right p ht
  have e26 : (26 * a + 3) * p = 26 * (p * a) + 3 * p := by ring
  have g13 : (13 * a + 2) * p = 13 * (p * a) + 2 * p := by ring
  have g15 : (15 * a + 2) * p = 15 * (p * a) + 2 * p := by ring
  have g17 : (17 * a + 2) * p = 17 * (p * a) + 2 * p := by ring
  generalize (13 * n + 1) % p = Q13 at *
  generalize (15 * n + 1) % p = Q15 at *
  generalize (17 * n + 1) % p = Q17 at *
  split_ifs at hk ho1 ho2 ho3 <;>
  exact ⟨by omega, div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega)⟩

theorem S2a2_hi_h3 {n a s t : ℕ} (hn : n = p * a + s) (h1 : 3 * p ≤ 26 * s) (h2 : 17 * s < 2 * p)
    (ht : 26 * a + 3 ≤ t) (htp : t < p) :
    5 * n / p < t - (17 * a + 2) ∧ t - (17 * a + 2) < p := by
  have hp0 := hp.out.pos
  have hdq : 5 * n / p = 5 * a + 0 := by
    have e : (5 * a + 0) * p = 5 * (p * a) + 0 * p := by ring
    exact div_of_lin hp0 (r := 5 * s - 0 * p) (by rw [hn]; omega) (by omega)
  omega

/-- **`S2a2` CLOSED below `p²`**: at a polar row on the stratum with `m < p²`, the coefficient
bound holds — every LO and TAIL block of `h_m` is `0 mod p²`. -/
theorem S2a2_closed {n p r : ℕ} (hp : p ∈ Zeta2PhiT.phiWindow n) (hr : r < 16 * n)
    (hpol : p ∣ r + 1) (hm : 11 * n + 1 + r < p ^ 2) (h1 : 3 * p ≤ 26 * (n % p))
    (h2 : 17 * (n % p) < 2 * p) :
    Zeta2PtpPolar.PVal p (Zeta2PhiT.phiT (Int.fract ((n : ℚ) / (p : ℚ))) + Zeta2PtpPoly.bbit n p r - 1)
      ((Zeta2PtpPoly.coeff n r : ℤ) : ℚ) := by
  have hpp := Zeta2PhiT.prime_of_mem_phiWindow hp
  have : Fact p.Prime := ⟨hpp⟩
  have hp0 := hpp.pos
  have hsq := Zeta2PhiT.sq_gt_of_mem_phiWindow hp
  have hn1 := Zeta2PtpPolar.pos_of_mem_phiWindow hp
  have hp2 : 2 < p := by
    by_contra hc
    have : p ^ 2 ≤ 4 := by
      have : p ≤ 2 := by omega
      calc p ^ 2 ≤ 2 ^ 2 := Nat.pow_le_pow_left this 2
        _ = 4 := by norm_num
    omega
  refine Zeta2PtpResPair.pval_coeff_of_dvd hp ?_
  rw [Zeta2PtpKumRes.padicValNat_LC_polar hp hm hpol, Zeta2PtpKumRes.bbit_polar hpol,
    Zeta2PtpS2a.phiT_piece2_res hp0 (by omega) (by omega)]
  have hmp : (11 * n + 1 + r) % p = (11 * n) % p := by
    rw [show 11 * n + 1 + r = 11 * n + (r + 1) by ring, Nat.add_mod, Nat.mod_eq_zero_of_dvd hpol,
      Nat.add_zero, Nat.mod_mod]
  have hM1 : (11 * n + 1 + r) / p < p := by
    rw [Nat.div_lt_iff_lt_mul hp0, ← sq]; exact hm
  have hn' : n = p * (n / p) + n % p := (Nat.div_add_mod n p).symm
  have hwin : 26 * (p * (n / p) + n % p) + 1 < p ^ 2 := by rw [← hn']; exact hsq
  generalize n / p = a at hn' hwin
  generalize n % p = s at hn' h1 h2 hwin
  have hpa := win_bound hwin h1 (by norm_num)
  obtain ⟨hone_lo, htwo_lo⟩ := S2a2_lo hn' h1 h2 hmp
  obtain ⟨hone_hi, htwo_hi⟩ := S2a2_hi hn' h1 h2 hmp
  have hdeg := S2a2_deg hn' h1 h2 hmp
  obtain ⟨r5, -, -, -, -, -, -⟩ := S2a2_res hn' h1 h2
  have hdvd : (p : ℤ) ^ 2 ∣ Zeta2NewtonAssemble.hc n (11 * n + 1 + r) := by
    refine pow_dvd_hc_of_blocks hp0 hn1 (fun t ht => ?_) (fun t ht => ?_)
    · by_cases hz : 13 * a + 1 < t
      · have e1 : (13 * a + 1 + 1) * p ≤ t * p := Nat.mul_le_mul_right p hz
        have e2 : (13 * a + 1 + 1) * p = 13 * (p * a) + 2 * p := by ring
        exact lo_all_zero hn1 (by omega)
      obtain ⟨hh3, h3p⟩ := S2a2_lo_h3 hn' h1 h2 hpa (t := t) (by omega)
      exact lo3_block_dvd hp2 hn1 hdeg (by omega) hone_lo htwo_lo
        (fun u hu hk ho1 ho2 ho3 => S2a2_lo_hsup hn' h1 h2 hpa hmp (by omega) hu hk ho1 ho2 ho3)
        hh3 h3p
    · by_cases hz : t < 26 * a + 3
      · have e1 : t * p + p ≤ (26 * a + 3) * p := by
          have := Nat.mul_le_mul_right p hz
          rw [Nat.succ_mul] at this; exact this
        have e2 : (26 * a + 3) * p = 26 * (p * a) + 3 * p := by ring
        exact hi_all_zero hn1 (by omega)
      obtain ⟨hh3, h3p⟩ := S2a2_hi_h3 hn' h1 h2 (t := t) (by omega) (by omega)
      exact hi3_block_dvd hp2 hn1 hdeg (by omega) hone_hi htwo_hi
        (fun u hu hk ho1 ho2 ho3 => S2a2_hi_hsup hn' h1 h2 hmp (by omega) (by omega) hu hk ho1 ho2 ho3)
        hh3 h3p
  rw [show 2 + 1 - 1 + 1 = 1 + 2 by rfl, pow_add, pow_one]
  exact mul_dvd_mul_left _ hdvd

end S2a2

end Zeta2PtpRunS2

#print axioms Zeta2PtpRunS2.S2a2_res
#print axioms Zeta2PtpRunS2.S2a2_resT
#print axioms Zeta2PtpRunS2.S2a2_deg
#print axioms Zeta2PtpRunS2.S2a2_lo
#print axioms Zeta2PtpRunS2.S2a2_hi
#print axioms Zeta2PtpRunS2.S2a2_lo_hsup
#print axioms Zeta2PtpRunS2.S2a2_hi_hsup
#print axioms Zeta2PtpRunS2.S2a2_closed
#check @Zeta2PtpRunS2.S2a2_closed
