/-
# ROW PAIR-8, obligation 1 of 3 — `λden(n) ≠ 0`, the division PAIR-8's CROSSING performs

`docs/future/zeta2-lean-chain.md` row PAIR-8.

**The module's theorem**, for EVERY natural `n`:

    lden_eval_ne_zero : StarKernel.hornerQ Zeta2Pair7Lam.lden (n : ℚ) ≠ 0

and, in the shape PAIR-7's four identity modules actually state, `lamDen n ≠ 0` — see
`Zeta2Pair8.lamDen_ne_zero`, which is this theorem plus `dld = 1`.

**WHICH nonvanishing this is, in types and not by degree.**  PAIR-7 proves `β̂ⱼ(n)·λden(n) =
γⱼ(n)·λnum(n)` at all four `j`.  PAIR-8 has to turn a recurrence in the CHAIN's operator `γ`
(L1-ASM's export) into one in the HAT's `β̂` (PAIR-6's), and the only way through that seam
divides by `λden`.  Three degree-carrying objects live in this neighbourhood; this is exactly
one of them:

  * **`λden` (deg 58) — THIS MODULE.**  PAIR-8's alone: PAIR-6 consumes nothing from
    PAIR-7 (its modules import no `Zeta2Pair7*`), so λ enters only at PAIR-8's crossing.
  * `al3` (deg 154) — PAIR-N, LANDED (`Zeta2PairN.L_ne_zero`), and a different obligation:
    it is what makes `Zeta2Pair6.betaHat n 3` nonzero, i.e. the division the INDUCTION does.
  * `L_t1` (deg 132) — the chain side's, owed by STAR-ID and L1-ASM.  Not proved here.

**The range.**  `∀ n : ℕ`, with nothing excluded: the mod-`scanP` scan covers `n ≤ 91`
and the dominance criterion covers every RATIONAL `x ≥ 91`, and the two overlap at
`n = 91`.  `ld_dominance_minimal` is the K-M0 kill: the inequality FAILS at `90`, so
`91` is the LEAST integer this criterion admits and not merely one that works.

**What this module does NOT discharge.**  `hatQ n = qnInt n` is row PAIR-8 and is NOT proved
by this file or by any file in this landing: it needs the chain-side recurrence, which is
L1-ASM's `hrecq_rat`/`hrecp_rat` and is `not started`.  `Zeta2Target.zeta2_not_liouvilleWith`
is still `sorry`.

**No coefficient data is emitted here.**  `ldlow`/`ldlead`/`ldz` are `take`/`getD` views of
the COMMITTED `Zeta2Pair7Lam.lden`, tied back by `ldz_eq`, one `decide +kernel`.  The only
literal this file carries is `rld`, `lden` reduced mod `scanP` — 59 naturals below 10^6, so
the scan never touches a 165-digit number.

**The instrument is not new.**  Sections 1 and 2 are `Zeta2L4`'s dominance criterion and its
Horner/scan bridges as PAIR-N carries them, SPLICED verbatim by `gen_pair8_lean.py` (not
copied by hand) so the files cannot drift — the third caller of that device
([PHILOSOPHY.md](../../docs/PHILOSOPHY.md) §5a: a second caller strengthens the instrument).
The prose inside that block speaks of `Zeta2L4`'s own degree-510 instance; it is kept verbatim
on purpose.  This instance is the cheapest of the three by a wide margin: degree 58
against 154 and 510, `m₀` 91 against 364 and 1127, 165-digit coefficients against
255 and 639.

GENERATED by `external_tests/zeta2_star_b1/gen_pair8_lean.py` from the committed
`Zeta2Pair7Lam.lean`.  Do not hand-edit: `gen_pair8_lean.py --check` regenerates and diffs,
and `pair8_check.py` re-derives every number here with its own arithmetic.

**How to elaborate** — Lean NEVER runs on the laptop (owner rule 2026-09-07):

    sh external_tests/zeta2_star_b1/run_probe.sh Zeta2Pair8Lam.lean

Receipts: `out_axioms_pair8lam.txt`.  Falsifier: `falsify_pair8.sh --lean`.  Second
implementation, in exact ℚ and a different language: `pair8_check.py` → `pair8_check.out`.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Algebra.Order.Group.Unbundled.Int
import Mathlib.Data.Int.ModEq
import Mathlib.Data.Nat.ModEq
import Mathlib.Tactic.GCongr
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import StarKernelBridge
import Zeta2Pair7Lam

-- FILE-LEVEL on purpose: placed between a docstring and its theorem a `set_option` is a parse
-- error Lean silently RECOVERS from — the file does not parse, the option is dropped, and every
-- receipt still prints clean (zeta2-lean-chain.md, PAIR-7's and PAIR-6's landings).
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

namespace Zeta2Pair8Lam

open Finset

/-! ## 1. The instrument (criterion + bridges), spliced verbatim from `Zeta2PairN.lean` -/

/--
**L4's dominance criterion.**  If the low-order coefficients are dominated at one point
`m > 0`,

`Σ_{i<d} |a_i| m^i < |a_d| m^d`,

then the polynomial `Σ_{i≤d} a_i x^i` has NO root at any `x ≥ m`.  One exact check at `m₀`
therefore covers the whole real tail — which is exactly the argument
docs/future/zeta2-chain-close.md §L4 records ("each normalized term strictly decreasing in
real `m > 0`, so one exact check covers the whole tail"), stated once and proved once.

The scaling step needs no division: `x^i·m^d ≤ m^i·x^d` for `i ≤ d` because `x ≥ m > 0`.
-/
theorem no_root_from_dominance {d : ℕ} (a : ℕ → ℚ) (m : ℚ) (hm : 0 < m)
    (hdom : ∑ i ∈ range d, |a i| * m ^ i < |a d| * m ^ d) (x : ℚ) (hx : m ≤ x) :
    ∑ i ∈ range (d + 1), a i * x ^ i ≠ 0 := by
  have hx0 : 0 < x := lt_of_lt_of_le hm hx
  have hmd : (0 : ℚ) < m ^ d := pow_pos hm d
  have hxd : (0 : ℚ) < x ^ d := pow_pos hx0 d
  have key : ∀ i ∈ range d, |a i| * x ^ i * m ^ d ≤ |a i| * m ^ i * x ^ d := by
    intro i hi
    obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le (le_of_lt (Finset.mem_range.mp hi))
    have hpk : m ^ k ≤ x ^ k := pow_le_pow_left₀ hm.le hx k
    have hpos : (0 : ℚ) ≤ |a i| * (x ^ i * m ^ i) := by positivity
    calc |a i| * x ^ i * m ^ (i + k) = |a i| * (x ^ i * m ^ i) * m ^ k := by ring
      _ ≤ |a i| * (x ^ i * m ^ i) * x ^ k := mul_le_mul_of_nonneg_left hpk hpos
      _ = |a i| * m ^ i * x ^ (i + k) := by ring
  have hscale : (∑ i ∈ range d, |a i| * x ^ i) * m ^ d
      ≤ (∑ i ∈ range d, |a i| * m ^ i) * x ^ d := by
    rw [Finset.sum_mul, Finset.sum_mul]
    exact Finset.sum_le_sum key
  have hlt : (∑ i ∈ range d, |a i| * x ^ i) * m ^ d < (|a d| * x ^ d) * m ^ d := by
    have h2 : (∑ i ∈ range d, |a i| * m ^ i) * x ^ d < (|a d| * m ^ d) * x ^ d :=
      by exact (mul_lt_mul_of_pos_right hdom hxd)
    have h3 : (|a d| * m ^ d) * x ^ d = (|a d| * x ^ d) * m ^ d := by ring
    linarith [hscale, h2, h3.le, h3.ge]
  have hSx : ∑ i ∈ range d, |a i| * x ^ i < |a d| * x ^ d :=
    lt_of_mul_lt_mul_right hlt hmd.le
  intro hzero
  rw [Finset.sum_range_succ] at hzero
  have habs : |∑ i ∈ range d, a i * x ^ i| ≤ ∑ i ∈ range d, |a i| * x ^ i := by
    refine (Finset.abs_sum_le_sum_abs _ _).trans (le_of_eq (Finset.sum_congr rfl ?_))
    intro i _
    rw [abs_mul, abs_pow, abs_of_pos hx0]
  have heq : |∑ i ∈ range d, a i * x ^ i| = |a d| * x ^ d := by
    have hneg : (∑ i ∈ range d, a i * x ^ i) = -(a d * x ^ d) := by linarith
    rw [hneg, abs_neg, abs_mul, abs_pow, abs_of_pos hx0]
  linarith

/-! ## 2. Horner evaluation, and the bridge to `Finset.range` sums

The criterion speaks of `∑ i ∈ range (d+1), a i * x ^ i` with `a : ℕ → ℚ`.  A 511-term
`Finset` sum over ℚ literals is not something a kernel can evaluate, so every COMPUTATION
below happens on `List ℕ` / `List ℤ` by Horner, where literal `Nat` arithmetic is kernel
accelerated, and these bridges carry the answer back. -/

/-- Horner evaluation of an ascending integer coefficient list. -/
def hornerZ : List ℤ → ℤ → ℤ
  | [], _ => 0
  | c :: cs, x => c + x * hornerZ cs x

/-- Horner evaluation of an ascending natural coefficient list. -/
def hornerN : List ℕ → ℕ → ℕ
  | [], _ => 0
  | c :: cs, m => c + m * hornerN cs m

/-- Horner evaluation reduced mod `p` at every step, so no intermediate value grows. -/
def hornerNM : List ℕ → ℕ → ℕ → ℕ
  | [], _, _ => 0
  | c :: cs, m, p => (c + m * hornerNM cs m p) % p

/-- `scanNZ L p k = true` exactly when `hornerNM L n p ≠ 0` for every `n < k`. -/
def scanNZ (L : List ℕ) (p : ℕ) : ℕ → Bool
  | 0 => true
  | k + 1 => (hornerNM L k p != 0) && scanNZ L p k

/-- `|z|` in ℚ is the cast of `z.natAbs`. -/
theorem cast_abs_natAbs (z : ℤ) : |((z : ℤ) : ℚ)| = ((z.natAbs : ℕ) : ℚ) := by
  rw [← Int.cast_abs, Int.abs_eq_natAbs, Int.cast_natCast]

/-- The absolute-value sum the criterion's hypothesis asks for, as a `ℕ` Horner value. -/
theorem sum_range_abs (L : List ℤ) (m : ℕ) :
    ∑ i ∈ range L.length, |((L.getD i 0 : ℤ) : ℚ)| * (m : ℚ) ^ i
      = ((hornerN (L.map Int.natAbs) m : ℕ) : ℚ) := by
  induction L with
  | nil => simp [hornerN]
  | cons c cs ih =>
      rw [List.length_cons, Finset.sum_range_succ']
      have hstep : ∀ i : ℕ, |(((c :: cs).getD (i + 1) 0 : ℤ) : ℚ)| * (m : ℚ) ^ (i + 1)
          = (|((cs.getD i 0 : ℤ) : ℚ)| * (m : ℚ) ^ i) * (m : ℚ) := by
        intro i
        simp only [List.getD_cons_succ, pow_succ]
        ring
      rw [Finset.sum_congr rfl (fun i _ => hstep i), ← Finset.sum_mul, ih]
      simp only [List.getD_cons_zero, pow_zero, mul_one, List.map_cons, hornerN,
        cast_abs_natAbs]
      push_cast
      ring

/-- The signed evaluation, as a `ℤ` Horner value. -/
theorem sum_range_hornerZ (L : List ℤ) (x : ℤ) :
    ∑ i ∈ range L.length, ((L.getD i 0 : ℤ) : ℚ) * (x : ℚ) ^ i
      = ((hornerZ L x : ℤ) : ℚ) := by
  induction L with
  | nil => simp [hornerZ]
  | cons c cs ih =>
      rw [List.length_cons, Finset.sum_range_succ']
      have hstep : ∀ i : ℕ, (((c :: cs).getD (i + 1) 0 : ℤ) : ℚ) * (x : ℚ) ^ (i + 1)
          = (((cs.getD i 0 : ℤ) : ℚ) * (x : ℚ) ^ i) * (x : ℚ) := by
        intro i
        simp only [List.getD_cons_succ, pow_succ]
        ring
      rw [Finset.sum_congr rfl (fun i _ => hstep i), ← Finset.sum_mul, ih]
      simp only [List.getD_cons_zero, pow_zero, mul_one, hornerZ]
      push_cast
      ring

/-- The reducing Horner agrees with the plain one modulo `p`. -/
theorem hornerNM_eq (L : List ℕ) (m p : ℕ) : hornerNM L m p = hornerN L m % p := by
  induction L with
  | nil => simp [hornerNM, hornerN]
  | cons c cs ih =>
      simp only [hornerNM, hornerN, ih]
      exact ((Nat.mod_modEq (hornerN cs m) p).mul_left m).add_left c

/-- Reducing the coefficients mod `p` reduces the value mod `p`. -/
theorem hornerN_map_modEq (L : List ℤ) (n p : ℕ) (hp : 0 < p) :
    ((hornerN (L.map (fun z => (z % (p : ℤ)).toNat)) n : ℕ) : ℤ)
      ≡ hornerZ L (n : ℤ) [ZMOD (p : ℤ)] := by
  induction L with
  | nil => simp [hornerN, hornerZ]
  | cons c cs ih =>
      have hp' : (0 : ℤ) < (p : ℤ) := by exact_mod_cast hp
      have hc : (((c % (p : ℤ)).toNat : ℕ) : ℤ) = c % (p : ℤ) :=
        Int.toNat_of_nonneg (Int.emod_nonneg c (ne_of_gt hp'))
      simp only [List.map_cons, hornerN, hornerZ, Nat.cast_add, Nat.cast_mul, hc]
      exact (Int.mod_modEq c (p : ℤ)).add (ih.mul_left (n : ℤ))

/--
A nonzero mod-`p` Horner value certifies that the integer value is nonzero.  This is what
turns a 1128-point scan over residues into a statement about 849-digit integers.
-/
theorem hornerZ_ne_zero_of_hornerNM (L : List ℤ) (R : List ℕ) (n p : ℕ) (hp : 0 < p)
    (hR : L.map (fun z => (z % (p : ℤ)).toNat) = R) (h : hornerNM R n p ≠ 0) :
    hornerZ L (n : ℤ) ≠ 0 := by
  subst hR
  intro h0
  apply h
  rw [hornerNM_eq]
  have key := hornerN_map_modEq L n p hp
  rw [h0] at key
  have hdvd : (p : ℤ) ∣ ((hornerN (L.map (fun z => (z % (p : ℤ)).toNat)) n : ℕ) : ℤ) :=
    Int.modEq_zero_iff_dvd.mp key
  have hd : p ∣ hornerN (L.map (fun z => (z % (p : ℤ)).toNat)) n := by exact_mod_cast hdvd
  simpa [Nat.ModEq] using Nat.modEq_zero_iff_dvd.mpr hd

/-- `scanNZ` says what it is meant to say. -/
theorem scanNZ_spec {L : List ℕ} {p : ℕ} : ∀ {k : ℕ}, scanNZ L p k = true →
    ∀ n, n < k → hornerNM L n p ≠ 0 := by
  intro k
  induction k with
  | zero => intro _ n hn; exact absurd hn (Nat.not_lt_zero n)
  | succ k ih =>
      intro h n hn
      rw [scanNZ, Bool.and_eq_true, bne_iff_ne] at h
      rcases Nat.lt_or_ge n k with h1 | h1
      · exact ih h.2 n h1
      · have hnk : n = k := by omega
        exact hnk ▸ h.1

/-! ## 3. The data — a VIEW of `Zeta2Pair7Lam.lden`, plus one residue list

`ldlow` and `ldlead` are the low-order 58 coefficients and the leading one, taken from the
COMMITTED `Zeta2Pair7Lam.lden` by `take`/`getD` rather than re-emitted, and `ldz_eq` ties the
reassembled list back to `lden` by one `decide +kernel`.  Nothing else about `lden` is restated
anywhere in this file, so there is no second copy to drift.  `rld` is `lden` reduced mod
`scanP`: 59 naturals below `scanP`, carried as a literal so the [0, 91] scan never
evaluates a 165-digit number. -/

/-- The 58 low-order coefficients of `lden`, ascending. -/
def ldlow : List ℤ := Zeta2Pair7Lam.lden.take 58

/-- The leading coefficient of `lden` (149 digits). -/
def ldlead : ℤ := Zeta2Pair7Lam.lden.getD 58 0

/-- The whole degree-58 polynomial, reassembled from the two views. -/
def ldz : List ℤ := ldlow ++ [ldlead]

/-- The coefficient function of `lden`, in the shape the criterion of section 1 consumes. -/
def lq (i : ℕ) : ℚ := ((ldz.getD i 0 : ℤ) : ℚ)

/-- The scan modulus: the least prime ≥ 10^6 at which `lden` has no root in [0, 91]. -/
def scanP : ℕ := 1000003

/-- `lden` reduced mod `scanP`, ascending. -/
def rld : List ℕ :=
  [816234, 623815, 479903, 84108, 146743, 998568, 51904, 18722, 165448, 71953, 465507, 750251, 589526, 672444, 541266, 276676, 55693, 660459, 571986, 150201, 43866, 718974, 992214, 215490, 976680, 524474, 276496, 304538, 420061, 961134, 324370, 204914, 498408, 688759, 214583, 842699, 410720, 166683, 768157, 62634, 408272, 957274, 869528, 41015, 176022, 475055, 799628, 33604, 898576, 690795, 379461, 349908, 265585, 83336, 137987, 500357, 749972, 678308, 312355]

/-! ## 4. `λden` is nonzero at every natural `n` -/

/-- The two views really do reassemble `lden`, so every statement below about `ldz` is a
statement about the list PAIR-7's `lamDen` evaluates. -/
theorem ldz_eq : ldz = Zeta2Pair7Lam.lden := by decide +kernel

/-- `ldlow` really does hold the 58 low-order coefficients. -/
theorem ldlow_length : ldlow.length = 58 := by decide +kernel

/-- `ldz` is the whole degree-58 polynomial. -/
theorem ldz_length : ldz.length = 59 := by
  simp [ldz, ldlow_length]

/-- Below the leading index, `lq` reads off `ldlow`. -/
theorem lq_low {i : ℕ} (h : i < 58) : lq i = ((ldlow.getD i 0 : ℤ) : ℚ) := by
  rw [lq, ldz, List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
    List.getElem?_append_left (by rw [ldlow_length]; exact h)]

/-- At the leading index, `lq` reads off `ldlead`. -/
theorem lq_lead : lq 58 = (ldlead : ℚ) := by
  rw [lq, ldz, List.getD_eq_getElem?_getD,
    List.getElem?_append_right (by rw [ldlow_length]), ldlow_length]
  simp

/--
**The dominance inequality for `lden`, in exact `ℕ` arithmetic at `m₀ = 91`.**
One exact check kills the whole real tail: each term of `|a_i| m^i / (|a_d| m^d)` is strictly
decreasing in real `m > 0`, so the criterion of section 1 lifts it.  The kernel evaluates a
58-term Horner sum against a 149-digit leading coefficient times `91 ^ 58`.
-/
theorem ld_dominance_nat :
    hornerN (ldlow.map Int.natAbs) 91 < ldlead.natAbs * 91 ^ 58 := by
  decide +kernel

/--
**K-M0, in Lean.**  The same inequality FAILS at `m₀ - 1`, so `91` is the LEAST integer the
criterion admits for this polynomial.  Without it the emitted `m₀` would be unfalsifiable: any
larger number also works, and a scan longer than it needs to be reads exactly the same.
-/
theorem ld_dominance_minimal :
    ¬ (hornerN (ldlow.map Int.natAbs) 90 < ldlead.natAbs * 90 ^ 58) := by
  decide +kernel

/-- The dominance hypothesis in the exact shape `no_root_from_dominance` consumes. -/
theorem ld_dominance :
    ∑ i ∈ range 58, |lq i| * (91 : ℚ) ^ i
      < |lq 58| * (91 : ℚ) ^ 58 := by
  have hs : ∑ i ∈ range 58, |lq i| * (91 : ℚ) ^ i
      = ((hornerN (ldlow.map Int.natAbs) 91 : ℕ) : ℚ) := by
    rw [← sum_range_abs ldlow 91, ldlow_length]
    refine Finset.sum_congr rfl (fun i hi => ?_)
    rw [lq_low (Finset.mem_range.mp hi)]
    norm_num
  have hl : |lq 58| * (91 : ℚ) ^ 58
      = ((ldlead.natAbs * 91 ^ 58 : ℕ) : ℚ) := by
    rw [lq_lead, cast_abs_natAbs]
    push_cast
    ring
  rw [hs, hl]
  exact_mod_cast ld_dominance_nat

/-- No RATIONAL `x ≥ 91` is a root of `lden` — the criterion of section 1, instantiated on
PAIR-7's own λ denominator. -/
theorem ld_no_rat_root (x : ℚ) (hx : (91 : ℚ) ≤ x) :
    ∑ i ∈ range (58 + 1), lq i * x ^ i ≠ 0 :=
  no_root_from_dominance lq 91 (by norm_num) ld_dominance x hx

/-- The same, as a statement about the integer index the recurrence runs on. -/
theorem ld_ne_zero_of_ge (n : ℕ) (hn : 91 ≤ n) : hornerZ ldz (n : ℤ) ≠ 0 := by
  intro h0
  refine ld_no_rat_root (n : ℚ) (by exact_mod_cast hn) ?_
  have hsum : ∑ i ∈ range (58 + 1), lq i * (n : ℚ) ^ i
      = ((hornerZ ldz (n : ℤ) : ℤ) : ℚ) := by
    rw [← sum_range_hornerZ ldz (n : ℤ), ldz_length]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    rw [lq]
    push_cast
    ring
  rw [hsum, h0]
  norm_num

/-- `rld` is `lden` reduced mod `scanP`. -/
theorem ld_reduction : ldz.map (fun z => (z % (scanP : ℤ)).toNat) = rld := by
  decide +kernel

/--
**The [0, 91] integer-root scan**, as a mod-`scanP` certificate: 92 reduced Horner
evaluations, none of them zero.  The polynomial HAS roots modulo every prime; what this
certifies is that none of them falls in `[0, 91]`.
-/
theorem ld_scan : scanNZ rld scanP 92 = true := by decide +kernel

/-- The scan, as nonvanishing at every index it covers. -/
theorem ld_ne_zero_of_lt (n : ℕ) (hn : n < 92) : hornerZ ldz (n : ℤ) ≠ 0 :=
  hornerZ_ne_zero_of_hornerNM ldz rld n scanP (by decide) ld_reduction
    (scanNZ_spec ld_scan n hn)

/-- **`lden` is nonzero at EVERY natural `n`** — the scan below 92, the criterion at and
above 91, and the two ranges overlap. -/
theorem ld_ne_zero (n : ℕ) : hornerZ ldz (n : ℤ) ≠ 0 := by
  rcases Nat.lt_or_ge n 92 with h | h
  · exact ld_ne_zero_of_lt n h
  · exact ld_ne_zero_of_ge n (by omega)

/-! ## 5. Back to `StarKernel.hornerQ`, the form `lamDen` is written in -/

/-- `hornerQ` at a NATURAL point is the cast of `hornerZ`.  One list induction; the ℚ twin of
`StarKernel.qeval_map_zdivq`'s step, over a list that is already integral. -/
theorem hornerQ_natCast (L : List ℤ) (n : ℕ) :
    StarKernel.hornerQ L (n : ℚ) = ((hornerZ L (n : ℤ) : ℤ) : ℚ) := by
  induction L with
  | nil => simp [StarKernel.hornerQ, hornerZ]
  | cons c cs ih =>
      rw [StarKernel.hornerQ_cons, ih, hornerZ]
      push_cast
      ring

/--
**ROW PAIR-8, obligation 1.**  `λden(n) ≠ 0` for every natural `n`, on PAIR-7's own `lden` —
the quantity PAIR-8's crossing from `β̂` to `γ` divides by.  Nothing is excluded.
-/
theorem lden_eval_ne_zero (n : ℕ) :
    StarKernel.hornerQ Zeta2Pair7Lam.lden (n : ℚ) ≠ 0 := by
  rw [← ldz_eq, hornerQ_natCast]
  exact_mod_cast ld_ne_zero n

/-! ## 6. Receipts (LEAN.md §1 — exit 0 is not an attestation)

EVERY theorem in this file, the spliced instrument included — the list is DERIVED from the
emitted text by the generator, not typed, so a lemma can never be added without its receipt. -/

#print axioms Zeta2Pair8Lam.no_root_from_dominance
#print axioms Zeta2Pair8Lam.cast_abs_natAbs
#print axioms Zeta2Pair8Lam.sum_range_abs
#print axioms Zeta2Pair8Lam.sum_range_hornerZ
#print axioms Zeta2Pair8Lam.hornerNM_eq
#print axioms Zeta2Pair8Lam.hornerN_map_modEq
#print axioms Zeta2Pair8Lam.hornerZ_ne_zero_of_hornerNM
#print axioms Zeta2Pair8Lam.scanNZ_spec
#print axioms Zeta2Pair8Lam.ldz_eq
#print axioms Zeta2Pair8Lam.ldlow_length
#print axioms Zeta2Pair8Lam.ldz_length
#print axioms Zeta2Pair8Lam.lq_low
#print axioms Zeta2Pair8Lam.lq_lead
#print axioms Zeta2Pair8Lam.ld_dominance_nat
#print axioms Zeta2Pair8Lam.ld_dominance_minimal
#print axioms Zeta2Pair8Lam.ld_dominance
#print axioms Zeta2Pair8Lam.ld_no_rat_root
#print axioms Zeta2Pair8Lam.ld_ne_zero_of_ge
#print axioms Zeta2Pair8Lam.ld_reduction
#print axioms Zeta2Pair8Lam.ld_scan
#print axioms Zeta2Pair8Lam.ld_ne_zero_of_lt
#print axioms Zeta2Pair8Lam.ld_ne_zero
#print axioms Zeta2Pair8Lam.hornerQ_natCast
#print axioms Zeta2Pair8Lam.lden_eval_ne_zero

end Zeta2Pair8Lam
