/-
# Row PT-P, layer 18 — the φ̃ = 2 run stratum `S2d` `[12/13, 14/15)` CLOSED below `p²`

GENERATED by `gen_ptp_runs2.py` — edit the generator, not this file.  One stratum per module so a
falsifier arm re-elaborates one stratum; `Zeta2PtpRunS2.lean` composes the five.  The mechanism is
in `Zeta2PtpRunS2.lean`'s header.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Zeta2PtpRunG2
import Zeta2PtpResPair
import Zeta2PtpS2d

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

namespace Zeta2PtpRunS2

open Zeta2PtpRunG2 Zeta2PtpBlock Zeta2PtpS7 Zeta2PtpRunBlock Zeta2PtpS2Kit Finset Polynomial

/-! ## Stratum `S2d`: `12/13 ≤ s/p < 14/15`, carried factor C(m, i) -/

section S2d
variable {p : ℕ} [hp : Fact p.Prime]

theorem S2d_res {n a s : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p) :
    (5 * n) % p = 5 * s - 4 * p ∧ (9 * n) % p = 9 * s - 8 * p ∧ (11 * n) % p = 11 * s - 10 * p ∧ (13 * n) % p = 13 * s - 12 * p ∧ (22 * n) % p = 22 * s - 20 * p ∧ (24 * n) % p = 24 * s - 22 * p ∧ (26 * n) % p = 26 * s - 24 * p := by
  have hp0 := hp.out.pos
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact res_mul hp0 (S := 5 * s) (A := 5 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 9 * s) (A := 9 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 11 * s) (A := 11 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 13 * s) (A := 13 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 22 * s) (A := 22 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 24 * s) (A := 24 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_mul hp0 (S := 26 * s) (A := 26 * a) (by rw [hn]; ring) (by omega) (by omega)

theorem S2d_resT {n a s : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p) :
    (((13 * n + 1) % p = 13 * s - 12 * p + 1 ∧ 13 * s - 12 * p + 1 < p) ∨ ((13 * n + 1) % p = 0 ∧ 13 * s + 1 = 12 * p + p))
    ∧ (((15 * n + 1) % p = 15 * s - 13 * p + 1 ∧ 15 * s - 13 * p + 1 < p) ∨ ((15 * n + 1) % p = 0 ∧ 15 * s + 1 = 13 * p + p))
    ∧ (((17 * n + 1) % p = 17 * s - 15 * p + 1 ∧ 17 * s - 15 * p + 1 < p) ∨ ((17 * n + 1) % p = 0 ∧ 17 * s + 1 = 15 * p + p)) := by
  have hp0 := hp.out.pos
  refine ⟨?_, ?_, ?_⟩
  · exact res_succ hp0 (S := 13 * s) (A := 13 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_succ hp0 (S := 15 * s) (A := 15 * a) (by rw [hn]; ring) (by omega) (by omega)
  · exact res_succ hp0 (S := 17 * s) (A := 17 * a) (by rw [hn]; ring) (by omega) (by omega)

theorem S2d_deg {n m a s : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p) (hm : m % p = (11 * n) % p) :
    (13 * n) % p + (9 * n) % p + (5 * n) % p ≤ p - 2 + (m % p + 1) := by
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2d_res hn h1 h2
  rw [hm, r5, r9, r11, r13]
  omega

theorem S2d_lo {n m a s : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p) (hm : m % p = (11 * n) % p) :
    (∀ u < p, cLo1 p n u ∨ cLo2 p n u ∨ cLo3 p n u ∨ c4 p m u)
    ∧ (∀ u < p, ¬ c4 p m u → (cLo1 p n u ∧ cLo2 p n u) ∨ (cLo1 p n u ∧ cLo3 p n u) ∨ (cLo2 p n u ∧ cLo3 p n u)) := by
  obtain ⟨r5, r9, r11, r13, r22, r24, r26⟩ := S2d_res hn h1 h2
  refine ⟨fun u hu => ?_, fun u hu => ?_⟩ <;>
  · unfold cLo1 cLo2 cLo3 c4
    rw [hm, r11, r13, r26, r9, r24, r5, r22,
      wrap_mod_down hu (show 26 * s - 24 * p < p by omega),
      wrap_mod_down hu (show 24 * s - 22 * p < p by omega),
      wrap_mod_down hu (show 22 * s - 20 * p < p by omega)]
    split_ifs <;> omega

theorem S2d_hi {n m a s : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p) (hm : m % p = (11 * n) % p) :
    (∀ u < p, cHi1 p n u ∨ cHi2 p n u ∨ cHi3 p n u ∨ c4 p m u)
    ∧ (∀ u < p, ¬ c4 p m u → (cHi1 p n u ∧ cHi2 p n u) ∨ (cHi1 p n u ∧ cHi3 p n u) ∨ (cHi2 p n u ∧ cHi3 p n u)) := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2d_res hn h1 h2
  obtain ⟨d13, d15, d17⟩ := S2d_resT hn h1 h2
  have q13 := Nat.mod_lt (13 * n + 1) hp0
  have q15 := Nat.mod_lt (15 * n + 1) hp0
  have q17 := Nat.mod_lt (17 * n + 1) hp0
  refine ⟨fun u hu => ?_, fun u hu => ?_⟩ <;>
  · unfold cHi1 cHi2 cHi3 c4
    rw [hm, r11, r13, r9, r5, wrap_mod_up hu q13, wrap_mod_up hu q15, wrap_mod_up hu q17]
    generalize (13 * n + 1) % p = Q13 at *
    generalize (15 * n + 1) % p = Q15 at *
    generalize (17 * n + 1) % p = Q17 at *
    split_ifs <;> omega

theorem S2d_lo_hsup {n m a s t u : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p)
    (hpa : 26 * 13 * a + 26 * 12 < 13 * p) (hm : m % p = (11 * n) % p)
    (ht : t ≤ 13 * a + 12) (hu : u < p) : c4 p m u → ¬ cLo1 p n u → ¬ cLo2 p n u → ¬ cLo3 p n u →
      t * p + u ≤ 22 * n ∧ (26 * n - (t * p + u)) / p = 26 * a + 23 - t
      ∧ (24 * n - (t * p + u)) / p = 24 * a + 21 - t ∧ (22 * n - (t * p + u)) / p = 22 * a + 19 - t := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, r22, r24, r26⟩ := S2d_res hn h1 h2
  intro hk ho1 ho2 ho3
  unfold cLo1 cLo2 cLo3 c4 at *
  rw [hm, r11] at hk
  rw [r26, r13, wrap_mod_down hu (show 26 * s - 24 * p < p by omega)] at ho1
  rw [r24, r9, wrap_mod_down hu (show 24 * s - 22 * p < p by omega)] at ho2
  rw [r22, r5, wrap_mod_down hu (show 22 * s - 20 * p < p by omega)] at ho3
  have hT : t * p ≤ (13 * a + 12) * p := Nat.mul_le_mul_right p ht
  have e13 : (13 * a + 12) * p = 13 * (p * a) + 12 * p := by ring
  have g26 : (26 * a + 23) * p = 26 * (p * a) + 23 * p := by ring
  have g24 : (24 * a + 21) * p = 24 * (p * a) + 21 * p := by ring
  have g22 : (22 * a + 19) * p = 22 * (p * a) + 19 * p := by ring
  split_ifs at hk ho1 ho2 ho3 <;>
  exact ⟨by omega, div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega)⟩

theorem S2d_hi_hsup {n m a s t u : ℕ} (hn : n = p * a + s) (h1 : 12 * p ≤ 13 * s) (h2 : 15 * s < 14 * p)
    (hm : m % p = (11 * n) % p) (ht : 26 * a + 24 ≤ t) (htp : t < p) (hu : u < p) :
    c4 p m u → ¬ cHi1 p n u → ¬ cHi2 p n u → ¬ cHi3 p n u →
      17 * n + 1 ≤ t * p + u ∧ (t * p + u - (13 * n + 1)) / p = t - (13 * a + 12)
      ∧ (t * p + u - (15 * n + 1)) / p = t - (15 * a + 14) ∧ (t * p + u - (17 * n + 1)) / p = t - (17 * a + 16) := by
  have hp0 := hp.out.pos
  obtain ⟨r5, r9, r11, r13, -, -, -⟩ := S2d_res hn h1 h2
  obtain ⟨d13, d15, d17⟩ := S2d_resT hn h1 h2
  have q13 := Nat.mod_lt (13 * n + 1) hp0
  have q15 := Nat.mod_lt (15 * n + 1) hp0
  have q17 := Nat.mod_lt (17 * n + 1) hp0
  intro hk ho1 ho2 ho3
  unfold cHi1 cHi2 cHi3 c4 at *
  rw [hm, r11] at hk
  rw [r13, wrap_mod_up hu q13] at ho1
  rw [r9, wrap_mod_up hu q15] at ho2
  rw [r5, wrap_mod_up hu q17] at ho3
  have hT : (26 * a + 24) * p ≤ t * p := Nat.mul_le_mul_right p ht
  have e26 : (26 * a + 24) * p = 26 * (p * a) + 24 * p := by ring
  have g13 : (13 * a + 12) * p = 13 * (p * a) + 12 * p := by ring
  have g15 : (15 * a + 14) * p = 15 * (p * a) + 14 * p := by ring
  have g17 : (17 * a + 16) * p = 17 * (p * a) + 16 * p := by ring
  generalize (13 * n + 1) % p = Q13 at *
  generalize (15 * n + 1) % p = Q15 at *
  generalize (17 * n + 1) % p = Q17 at *
  split_ifs at hk ho1 ho2 ho3 <;>
  exact ⟨by omega, div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega), div_eq_of_bounds (by rw [Nat.sub_mul]; omega) (by rw [Nat.sub_mul]; omega)⟩

/-- **`S2d` CLOSED below `p²`**: at a polar row on the stratum with `m < p²`, the coefficient
bound holds — every LO and TAIL block of `h_m` is `0 mod p²`. -/
theorem S2d_closed {n p r : ℕ} (hp : p ∈ Zeta2PhiT.phiWindow n) (hr : r < 16 * n)
    (hpol : p ∣ r + 1) (hm : 11 * n + 1 + r < p ^ 2) (h1 : 12 * p ≤ 13 * (n % p))
    (h2 : 15 * (n % p) < 14 * p) :
    Zeta2PtpPolar.PVal p (Zeta2PhiT.phiT (Int.fract ((n : ℚ) / (p : ℚ))) + Zeta2PtpPoly.bbit n p r - 1)
      ((Zeta2PtpPoly.coeff n r : ℤ) : ℚ) := by
  have hpp := Zeta2PhiT.prime_of_mem_phiWindow hp
  have : Fact p.Prime := ⟨hpp⟩
  have hp0 := hpp.pos
  have hsq := Zeta2PhiT.sq_gt_of_mem_phiWindow hp
  have hn1 := Zeta2PtpPolar.pos_of_mem_phiWindow hp
  have hp2 : 2 < p := by
    by_contra hc
    have : p ^ 2 ≤ 4 := by
      have : p ≤ 2 := by omega
      calc p ^ 2 ≤ 2 ^ 2 := Nat.pow_le_pow_left this 2
        _ = 4 := by norm_num
    omega
  refine Zeta2PtpResPair.pval_coeff_of_dvd hp ?_
  rw [Zeta2PtpKumRes.padicValNat_LC_polar hp hm hpol, Zeta2PtpKumRes.bbit_polar hpol,
    Zeta2PtpS2d.phiT_piece25_res hp0 (by omega) (by omega)]
  have hmp : (11 * n + 1 + r) % p = (11 * n) % p := by
    rw [show 11 * n + 1 + r = 11 * n + (r + 1) by ring, Nat.add_mod, Nat.mod_eq_zero_of_dvd hpol,
      Nat.add_zero, Nat.mod_mod]
  have hM1 : (11 * n + 1 + r) / p < p := by
    rw [Nat.div_lt_iff_lt_mul hp0, ← sq]; exact hm
  have hn' : n = p * (n / p) + n % p := (Nat.div_add_mod n p).symm
  have hwin : 26 * (p * (n / p) + n % p) + 1 < p ^ 2 := by rw [← hn']; exact hsq
  generalize n / p = a at hn' hwin
  generalize n % p = s at hn' h1 h2 hwin
  have hpa := win_bound hwin h1 (by norm_num)
  obtain ⟨hone_lo, htwo_lo⟩ := S2d_lo hn' h1 h2 hmp
  obtain ⟨hone_hi, htwo_hi⟩ := S2d_hi hn' h1 h2 hmp
  have hdeg := S2d_deg hn' h1 h2 hmp
  obtain ⟨r5, -, -, -, -, -, -⟩ := S2d_res hn' h1 h2
  have hdvd : (p : ℤ) ^ 2 ∣ Zeta2NewtonAssemble.hc n (11 * n + 1 + r) := by
    refine pow_dvd_hc_of_blocks hp0 hn1 (fun t ht => ?_) (fun t ht => ?_)
    · by_cases hz : 13 * a + 12 < t
      · have e1 : (13 * a + 12 + 1) * p ≤ t * p := Nat.mul_le_mul_right p hz
        have e2 : (13 * a + 12 + 1) * p = 13 * (p * a) + 13 * p := by ring
        exact lo_all_zero hn1 (by omega)
      by_cases hpast : (11 * n + 1 + r) / p ≤ t
      · exact lo4_block_past hn1 htwo_lo hpast
      exact lo4_block_dvd hp2 hn1 hdeg hone_lo htwo_lo
        (fun u hu hk ho1 ho2 ho3 => S2d_lo_hsup hn' h1 h2 hpa hmp (by omega) hu hk ho1 ho2 ho3)
        (by omega) hM1
    · by_cases hz : t < 26 * a + 24
      · have e1 : t * p + p ≤ (26 * a + 24) * p := by
          have := Nat.mul_le_mul_right p hz
          rw [Nat.succ_mul] at this; exact this
        have e2 : (26 * a + 24) * p = 26 * (p * a) + 24 * p := by ring
        exact hi_all_zero hn1 (by omega)
      by_cases hpast : (11 * n + 1 + r) / p ≤ t
      · exact hi4_block_past hn1 htwo_hi hpast
      exact hi4_block_dvd hp2 hn1 hdeg hone_hi htwo_hi
        (fun u hu hk ho1 ho2 ho3 => S2d_hi_hsup hn' h1 h2 hmp (by omega) (by omega) hu hk ho1 ho2 ho3)
        (by omega) hM1
  rw [show 2 + 1 - 1 + 1 = 1 + 2 by rfl, pow_add, pow_one]
  exact mul_dvd_mul_left _ hdvd

end S2d

end Zeta2PtpRunS2

#print axioms Zeta2PtpRunS2.S2d_res
#print axioms Zeta2PtpRunS2.S2d_resT
#print axioms Zeta2PtpRunS2.S2d_deg
#print axioms Zeta2PtpRunS2.S2d_lo
#print axioms Zeta2PtpRunS2.S2d_hi
#print axioms Zeta2PtpRunS2.S2d_lo_hsup
#print axioms Zeta2PtpRunS2.S2d_hi_hsup
#print axioms Zeta2PtpRunS2.S2d_closed
#check @Zeta2PtpRunS2.S2d_closed
