/-
# Row PT-P, layer 18 — the four φ̃ = 2 run strata CLOSED for the polynomial half below `p²`, and
# `ResidualRunOpen` narrowed to the polar run-strata rows at or above `p²`

GENERATED by `gen_ptp_runs2.py` — edit the generator, not this file.

Each stratum (`[1/9, 3/26)`, `[3/26, 2/17)`, `[5/9, 9/16)`, `[6/13, 7/15)`, `[12/13, 14/15)`, with
`n = p·a + s`) fixes the nine floors `⌊c·s/p⌋`; from them `omega` proves the residue facts the
generic quotient block lemmas of `Zeta2PtpRunG2` take — every residue carries (`hone`), a residue
where the carried factor does not carry carries twice (`htwo`), the degree count, and on the
one-carry set of each block the high digits (`*_lo_hsup`, `*_hi_hsup`).  `*_closed` then sums the
blocks of both halves of `h_m` (`Zeta2PtpRunBlock.pow_dvd_hc_of_blocks`): LO blocks up to
`13a + ⌊13x⌋` by the quotient lemma and the rest vanish (`i > 13n`); TAIL blocks from the one
containing `26n` by the quotient lemma, the ones below vanish (`i ≤ 26n`), and — on the two
strata whose carried factor is `C(m, i)` — the blocks at or past `m/p` vanish outright
(`*_block_past`).  So `p² ∣ h_m` and the coefficient bound holds at every polar row on the stratum
below `p²`, for every `n`.

**`restBelowOpen : RestBelowOpen`** — the `m < p²` rows of `Zeta2PtpRunS7.ResidualRunRestOpen`,
hypothesis-free.  The other half, the polar run-strata rows at or above `p²` (`RestAboveOpen`), and
the split composing the two into `ResidualRunRestOpen` live in their own file (a sibling unit's);
nothing here states or assumes them.  Row PT-P does not close and
`Zeta2Target.zeta2_not_liouvilleWith` is `sorry`.

Falsifier: `falsify_ptpruns2.sh` / `out_ptpruns2_falsify.txt`.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Zeta2PtpRunS7
import Zeta2PtpRunSa1
import Zeta2PtpRunSa2
import Zeta2PtpRunSb
import Zeta2PtpRunSc
import Zeta2PtpRunSd

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

namespace Zeta2PtpRunS2

open Zeta2PtpRunG2 Zeta2PtpBlock Zeta2PtpS7 Zeta2PtpRunBlock Zeta2PtpS2Kit Finset Polynomial

/-! ## `RestBelowOpen`: the `m < p²` rows of `Zeta2PtpRunS7.ResidualRunRestOpen` -/

/-- **The `m < p²` half of `Zeta2PtpRunS7.ResidualRunRestOpen`**: the polar run-strata rows below
`p²` that `Zeta2PtpRunS7.coeff_runLow_S7` does not already close. -/
def RestBelowOpen : Prop :=
  ∀ n p r : ℕ, p ∈ Zeta2PhiT.phiWindow n → r < 16 * n → p ∣ r + 1 →
    Zeta2PtpKumRows.RunStrata p (n % p) →
    ¬ (11 * n + 1 + r < p ^ 2 ∧ 3 * p ≤ 13 * (n % p) ∧ 17 * (n % p) < 4 * p) →
    11 * n + 1 + r < p ^ 2 →
    Zeta2PtpPolar.PVal p (Zeta2PhiT.phiT (Int.fract ((n : ℚ) / (p : ℚ))) + Zeta2PtpPoly.bbit n p r - 1)
      ((Zeta2PtpPoly.coeff n r : ℤ) : ℚ)

/-- **`RestBelowOpen` IS A THEOREM**: the four φ̃ = 2 strata below `p²`. -/
theorem restBelowOpen : RestBelowOpen := by
  intro n p r hp hr hpol hrun hns7 hm
  have hrun' := hrun
  unfold Zeta2PtpKumRows.RunStrata at hrun'
  rcases hrun' with ⟨h1, h2⟩ | ⟨h1, h2⟩ | ⟨h1, h2⟩ | ⟨h1, h2⟩ | ⟨h1, h2⟩
  · by_cases h3 : 26 * (n % p) < 3 * p
    · exact S2a1_closed hp hr hpol hm (by omega) (by omega)
    · exact S2a2_closed hp hr hpol hm (by omega) (by omega)
  · exact absurd ⟨hm, h1, h2⟩ hns7
  · exact S2c_closed hp hr hpol hm (by omega) (by omega)
  · exact S2b_closed hp hr hpol hm (by omega) (by omega)
  · exact S2d_closed hp hr hpol hm (by omega) (by omega)

end Zeta2PtpRunS2

#print axioms Zeta2PtpRunS2.restBelowOpen
#check @Zeta2PtpRunS2.restBelowOpen
#print Zeta2PtpRunS2.RestBelowOpen
