/-
# STAR-ID — the Π-REBASE: the Pochhammer literals of part (ii) ARE `Zeta2Defs.Member.Pin`'s ratio

`docs/future/zeta2-lean-chain.md` row STAR-ID.  Added 2026-09-17.

**HEADLINE: `Zeta2Target.zeta2_not_liouvilleWith` is `sorry` and stays `sorry`.**  This file
discharges ONE named debt of STAR-ID and nothing else.  The row still owes part (iii)'s `'alt'`
sign, the `hr` spelling into `Zeta2T1Eval.Phi_rho`, the composition with STAR, and the ℚ→ℝ
transport (row L4-BR).

**THE DEBT.**  `Zeta2StarIdII.star_ii_j3` reads `Cq c3 n * Cq n3 n = -(Atil3 n * Cq d3 n * Wq n)`
where `n3`, `d3` are integer coefficient LISTS.  That they are `Π(n+3)/Π(n)` was measured off
Lean for `n ≤ 12` and stated nowhere, so the landed theorem is about two anonymous lists rather
than about the member.  This file closes that gap at `j = 1, 2, 3`.

**THE THEOREMS.**

    ascN_pos      : 0 < ascN m k
    factorial_shift : (m + k)! = m ! * ascN m k
    Pin_shift     : m.Pin (n + j) * (Dj m n j : ℚ) = m.Pin n * (Nj m n j : ℚ)   -- ANY Member, ANY j
    pin_j1/j2/j3  : candidateM.Pin (n + j) * (d<j> at n) = candidateM.Pin n * (n<j> at n)
    pin_ratio_j1/j2/j3 : candidateM.Pin (n + j) / candidateM.Pin n = (n<j> at n) / (d<j> at n)

`Pin_shift` is stated for an arbitrary `Member`, so it is not a candidate-specific trick: the
ℕ-subtractions `α₂−β₂`, `α₃−β₃`, `β₄−α₄` appear on both sides and never need `Member.WF`,
because the identity is `(A(n+j))! = (An)! · ∏(An+i)` applied four times whatever those slopes are.

**NO DIVISION IN THE LOAD-BEARING FORM.**  `Pin_shift` and `pin_j*` are cross-multiplied, so a
consumer needs no nonvanishing side condition.  The quotient spellings are derived beside them
from `Member.Pin_pos` (landed) and `dj_pos` (here), and are unconditional.

**THE DATA.**  `n1`,`d1`,`n2`,`d2`,`n3`,`d3` are the ascending Pochhammer products of the
rebase.  They are NOT trusted as transcriptions: each is tied by `decide +kernel` to `ascL`, a
list-level recursion, and `ascL` is tied to the ℕ-level `ascN` by `hornerZ_ascL`, so a mistyped
digit makes a `decide` false rather than proving something else.  `n3`/`d3` are additionally
required by the generator to be BYTE-IDENTICAL to the landed `Zeta2StarIdII.n3`/`.d3`, which is
what makes this file a statement about the landed (ii) rather than about a neighbouring pair.

GENERATED by `external_tests/zeta2_star_b1/gen_starid_ii_pi_lean.py`.  Do not hand-edit:
`--check` regenerates and diffs, and `starid_ii_pi_check.py` re-derives every number.

**How to elaborate** — Lean NEVER runs on the laptop (owner rule 2026-09-07):

    sh external_tests/zeta2_star_b1/run_probe.sh Zeta2StarIdPi.lean

Receipts: `out_axioms_staridpi.txt`.  Falsifier: `falsify_staridpi.sh --lean`.

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import Zeta2Defs

-- FILE-LEVEL on purpose: placed between a docstring and its theorem a `set_option` is a parse
-- error Lean silently RECOVERS from — the file does not parse, the option is dropped, and every
-- receipt still prints clean (found_bugs 2026-09-14).
set_option maxRecDepth 4000000
-- RAISED for the FALSIFIER, not for this file: at the default 200000 two of `falsify_staridpi`'s
-- identification arms (A3 `recordM`, A5 the shift index) red through `(deterministic) timeout at
-- whnf` inside the right declaration, and a falsifier arm that RESOURCE-ERRORS has not rejected
-- anything (LEAN.md §3).  With the limit raised they red through the type mismatch they are
-- about.  The unperturbed module never approaches it.
set_option maxHeartbeats 2000000

namespace Zeta2StarIdPi

open Zeta2Defs

/-! ## 1. Dense `List ℤ` polynomial arithmetic, and its Horner bridge

`hornerZ` is `Zeta2L4`'s own evaluator, restated here because this file imports no `Zeta2L4`
(and `starid_ii_check.py` §1 pins the restatement against the committed one byte for byte).
`addZ`/`smulZ`/`mulZ` are new: nothing in this corpus had yet asked the kernel to MULTIPLY two
coefficient lists.  The four bridge lemmas are what turn a `decide +kernel` fact about lists
into a `∀ x : ℤ` fact about values, which is the only form the consumer can use. -/

/-- Horner evaluation of a dense coefficient list, low degree first. -/
def hornerZ : List ℤ → ℤ → ℤ
  | [], _ => 0
  | c :: cs, x => c + x * hornerZ cs x

/-- Dense-list polynomial addition. -/
def addZ : List ℤ → List ℤ → List ℤ
  | [], b => b
  | a, [] => a
  | x :: a, y :: b => (x + y) :: addZ a b

/-- Scalar multiple of a dense coefficient list. -/
def smulZ (c : ℤ) : List ℤ → List ℤ
  | [] => []
  | x :: l => c * x :: smulZ c l

/-- Dense-list polynomial multiplication, low degree first. -/
def mulZ : List ℤ → List ℤ → List ℤ
  | [], _ => []
  | x :: a, b => addZ (smulZ x b) (0 :: mulZ a b)

theorem hornerZ_addZ : ∀ (A B : List ℤ) (x : ℤ),
    hornerZ (addZ A B) x = hornerZ A x + hornerZ B x := by
  intro A
  induction A with
  | nil => intro B x; simp [addZ, hornerZ]
  | cons a A ih =>
      intro B x
      cases B with
      | nil => simp [addZ, hornerZ]
      | cons b B =>
          simp only [addZ, hornerZ, ih B x]
          ring

theorem hornerZ_smulZ : ∀ (c : ℤ) (L : List ℤ) (x : ℤ),
    hornerZ (smulZ c L) x = c * hornerZ L x := by
  intro c L
  induction L with
  | nil => intro x; simp [smulZ, hornerZ]
  | cons a L ih =>
      intro x
      simp only [smulZ, hornerZ, ih x]
      ring

theorem hornerZ_mulZ : ∀ (A B : List ℤ) (x : ℤ),
    hornerZ (mulZ A B) x = hornerZ A x * hornerZ B x := by
  intro A
  induction A with
  | nil => intro B x; simp [mulZ, hornerZ]
  | cons a A ih =>
      intro B x
      simp only [mulZ, hornerZ_addZ, hornerZ_smulZ, hornerZ, ih B x]
      ring

theorem hornerZ_map_mul : ∀ (s : ℤ) (L : List ℤ) (x : ℤ),
    hornerZ (L.map (fun z => s * z)) x = s * hornerZ L x := by
  intro s L
  induction L with
  | nil => intro x; simp [hornerZ]
  | cons a L ih =>
      intro x
      simp only [List.map_cons, hornerZ, ih x]
      ring

/-! ## 2. The ascending product, at three levels

`ascN m k = ∏_{i=1}^{k} (m + i) = (m+k)!/m!` over ℕ; `ascL s k` is the same object as a dense
`List ℤ` in the variable `n` at slope `s`; `hornerZ_ascL` is the bridge, and it is the only
place where the list literals of section 4 acquire their meaning. -/

/-- `∏_{i=1}^{k} (m + i)`, over ℕ.  Defined by recursion rather than through Mathlib's
ascending-factorial API, whose argument convention has drifted more than once (LEAN.md §8). -/
def ascN (m : ℕ) : ℕ → ℕ
  | 0 => 1
  | (k + 1) => ascN m k * (m + k + 1)

/-- `∏_{i=1}^{k} (s·n + i)` as a dense coefficient list in `n`. -/
def ascL (s : ℕ) : ℕ → List ℤ
  | 0 => [1]
  | (k + 1) => mulZ (ascL s k) [((k : ℤ) + 1), (s : ℤ)]

theorem ascN_pos (m : ℕ) : ∀ k : ℕ, 0 < ascN m k := by
  intro k
  induction k with
  | zero => simp [ascN]
  | succ k ih => exact Nat.mul_pos ih (Nat.succ_pos _)

theorem ascN_ne_zero (m k : ℕ) : ascN m k ≠ 0 := by
  have h := ascN_pos m k
  omega

theorem hornerZ_ascL (s n : ℕ) : ∀ k : ℕ,
    hornerZ (ascL s k) (n : ℤ) = ((ascN (s * n) k : ℕ) : ℤ) := by
  intro k
  induction k with
  | zero => simp [ascL, ascN, hornerZ]
  | succ k ih =>
      simp only [ascL, ascN, hornerZ_mulZ, ih, hornerZ]
      push_cast
      ring

/-- `(m + k)! = m ! · ∏_{i=1}^{k} (m + i)`.  The whole arithmetic content of this file. -/
theorem factorial_shift (m : ℕ) : ∀ k : ℕ,
    Nat.factorial (m + k) = Nat.factorial m * ascN m k := by
  intro k
  induction k with
  | zero => simp [ascN]
  | succ k ih =>
      have h : m + (k + 1) = (m + k) + 1 := by omega
      rw [h, Nat.factorial_succ, ih]
      simp only [ascN]
      ring


/-! ## 3. The Π-rebase, for an ARBITRARY member and an ARBITRARY shift

This is the general theorem; section 4 is nothing but four `decide +kernel` ties into it.  It is
stated CROSS-MULTIPLIED, so it carries no nonvanishing hypothesis at all. -/

/-- The rebase numerator `∏_{i=1}^{(β₄−α₄)j} ((β₄−α₄)n + i)`. -/
def Nj (m : Member) (n j : ℕ) : ℕ := ascN ((m.b4 - m.a4) * n) ((m.b4 - m.a4) * j)

/-- The rebase denominator — one ascending product per numerator Γ-block of `Pin`. -/
def Dj (m : Member) (n j : ℕ) : ℕ :=
  ascN (m.a1 * n) (m.a1 * j) * ascN ((m.a2 - m.b2) * n) ((m.a2 - m.b2) * j)
    * ascN ((m.a3 - m.b3) * n) ((m.a3 - m.b3) * j)

theorem Nj_pos (m : Member) (n j : ℕ) : 0 < Nj m n j := ascN_pos _ _

theorem Dj_pos (m : Member) (n j : ℕ) : 0 < Dj m n j :=
  Nat.mul_pos (Nat.mul_pos (ascN_pos _ _) (ascN_pos _ _)) (ascN_pos _ _)

theorem Dj_ne_zero (m : Member) (n j : ℕ) : Dj m n j ≠ 0 := by
  have h := Dj_pos m n j
  omega

/-- **`Π(n+j) · Dⱼ(n) = Π(n) · Nⱼ(n)`** — the Π-rebase, for every member and every shift. -/
theorem Pin_shift (m : Member) (n j : ℕ) :
    m.Pin (n + j) * ((Dj m n j : ℕ) : ℚ) = m.Pin n * ((Nj m n j : ℕ) : ℚ) := by
  have hf : ∀ a : ℕ, ((Nat.factorial a : ℕ) : ℚ) ≠ 0 := by
    intro a
    have h : Nat.factorial a ≠ 0 := by
      have := Nat.factorial_pos a
      omega
    exact_mod_cast h
  have ha : ∀ a b : ℕ, ((ascN a b : ℕ) : ℚ) ≠ 0 := by
    intro a b
    exact_mod_cast ascN_ne_zero a b
  have h1 := hf (m.a1 * n)
  have h2 := hf ((m.a2 - m.b2) * n)
  have h3 := hf ((m.a3 - m.b3) * n)
  have h4 := ha (m.a1 * n) (m.a1 * j)
  have h5 := ha ((m.a2 - m.b2) * n) ((m.a2 - m.b2) * j)
  have h6 := ha ((m.a3 - m.b3) * n) ((m.a3 - m.b3) * j)
  unfold Member.Pin Nj Dj
  rw [Nat.mul_add m.a1 n j, Nat.mul_add (m.a2 - m.b2) n j, Nat.mul_add (m.a3 - m.b3) n j,
    Nat.mul_add (m.b4 - m.a4) n j, factorial_shift, factorial_shift, factorial_shift,
    factorial_shift]
  push_cast
  -- `field_simp` closes this outright: after the four `factorial_shift` rewrites both sides are
  -- the same product over the same nonzero denominators.  No `ring` follows, because a `ring`
  -- on no goals is an ERROR, not a no-op (measured here on the first elaboration).
  field_simp

/-- The quotient spelling.  Unconditional: `Member.Pin_pos` is landed and `Dj_pos` is above. -/
theorem Pin_shift_div (m : Member) (n j : ℕ) :
    m.Pin (n + j) / m.Pin n = ((Nj m n j : ℕ) : ℚ) / ((Dj m n j : ℕ) : ℚ) := by
  have hP : m.Pin n ≠ 0 := ne_of_gt (m.Pin_pos n)
  have hD : ((Dj m n j : ℕ) : ℚ) ≠ 0 := by
    exact_mod_cast Dj_ne_zero m n j
  field_simp
  linear_combination Pin_shift m n j


/-! ## 4. The candidate's literals, tied to section 3

`candidateM` is `⟨13, 11, 9, 15, 2, 4, 26⟩`, so the four slopes of the rebase are
`β₄−α₄ = 11` and `α₁ = 13`, `α₂−β₂ = 9`, `α₃−β₃ = 5`.  Each `decide +kernel` below is a
statement about SMALL integers — the whole section costs less than one coefficient of the
convolutions in `Zeta2StarIdII`. -/

/-- `N1 = ∏_{i=1}^{11} (11·n + i)` — degree 11. -/
def n1 : List ℤ :=
  [39916800, 1325982240, 18261075096, 140098499156, 673423482930, 2148345451285, 4672594888038, 6965163120333, 7003104642270, 4539049305175, 1711870023666, 285311670611]

/-- `D1 = ∏_{i=1}^{13}(13 n+i) · ∏_{i=1}^{9}(9 n+i) · ∏_{i=1}^{5}(5 n+i)` — degree 27. -/
def d1 : List ℤ :=
  [271159356948480000, 21209846217670656000, 771643358711986176000, 17432083663798307512320, 275307907260302315642880, 3243308611595768857290240, 29685355578172506186112320, 217020875420348167726172160, 1292536645868580504897613680, 6363005049077973833503034640, 26172146820537003736443013020, 90664938742822948795061239560, 266050553529002866951412845305, 663909434849799551605448680515, 1412064383308426830880787664645, 2561608196639607534863565695535, 3960304122946560449139071561205, 5205259411258807298948065822215, 5791669519150302557041493966745, 5420282319875289653327251345635, 4227881510089441208567141562555, 2713668520090296164856118898265, 1407813647028895925812158332895, 575348014512831087662342919165, 178227500182698596429355294375, 39315384439484330009416618125, 5500313526651458478361734375, 366687568443430565224115625]

theorem n1_ascL : n1 = ascL 11 11 := by decide +kernel

theorem d1_ascL : d1 = mulZ (mulZ (ascL 13 13) (ascL 9 9)) (ascL 5 5) := by
  decide +kernel

/-- `Nj` at `candidateM` and `j = 1`, in numerals. -/
theorem nj1_num (n : ℕ) : Nj candidateM n 1 = ascN (11 * n) 11 := rfl

/-- `Dj` at `candidateM` and `j = 1`, in numerals. -/
theorem dj1_num (n : ℕ) : Dj candidateM n 1
    = ascN (13 * n) 13 * ascN (9 * n) 9 * ascN (5 * n) 5 := rfl

/-- The literal `n1` evaluates to the rebase numerator. -/
theorem n1_eval (n : ℕ) : hornerZ n1 (n : ℤ) = ((Nj candidateM n 1 : ℕ) : ℤ) := by
  rw [n1_ascL, hornerZ_ascL, nj1_num]

/-- The literal `d1` evaluates to the rebase denominator. -/
theorem d1_eval (n : ℕ) : hornerZ d1 (n : ℤ) = ((Dj candidateM n 1 : ℕ) : ℤ) := by
  rw [d1_ascL]
  simp only [hornerZ_mulZ, hornerZ_ascL, dj1_num]
  push_cast
  ring

theorem d1_ne_zero (n : ℕ) : ((hornerZ d1 (n : ℤ) : ℤ) : ℚ) ≠ 0 := by
  rw [d1_eval]
  exact_mod_cast Dj_ne_zero candidateM n 1

/-- **The Π-rebase at `j = 1`**, in `Zeta2StarIdII`'s own vocabulary: the Pochhammer literals
`n1`/`d1` that part (ii) is stated against ARE `Pin (n+1)/Pin n`. -/
theorem pin_j1 (n : ℕ) :
    candidateM.Pin (n + 1) * ((hornerZ d1 (n : ℤ) : ℤ) : ℚ)
      = candidateM.Pin n * ((hornerZ n1 (n : ℤ) : ℤ) : ℚ) := by
  -- `linear_combination` and NOT `exact_mod_cast`: on a mismatched goal `norm_cast` searches
  -- until the heartbeat limit, and a falsifier arm that RESOURCE-ERRORS has rejected nothing
  -- (LEAN.md §3).  `linear_combination` ends in `ring1`, which refuses in milliseconds — which
  -- is what `falsify_staridpi.sh`'s A3 and A5 need in order to mean anything.  MEASURED: both
  -- arms red through `whnf` timeouts under `exact_mod_cast`, at 200000 heartbeats and at
  -- 2000000, and through `ring failed` here.
  have key := Pin_shift candidateM n 1
  rw [n1_eval, d1_eval]
  push_cast
  push_cast at key
  linear_combination key

/-- The quotient spelling at `j = 1` — unconditional. -/
theorem pin_ratio_j1 (n : ℕ) :
    candidateM.Pin (n + 1) / candidateM.Pin n
      = ((hornerZ n1 (n : ℤ) : ℤ) : ℚ) / ((hornerZ d1 (n : ℤ) : ℤ) : ℚ) := by
  have hP : candidateM.Pin n ≠ 0 := ne_of_gt (candidateM.Pin_pos n)
  have hD := d1_ne_zero n
  field_simp
  linear_combination pin_j1 n

/-- `N2 = ∏_{i=1}^{22} (11·n + i)` — degree 22. -/
def n2 : List ℤ :=
  [1124000727777607680000, 45633244572690001920000, 817493747526282613248000, 8716299538947784436505600, 62674063471693991319374592, 325594773738842366212267968, 1276069944226300920426339456, 3884221473652191621043808560, 9370533351464080438519560992, 18173648630414969634683893988, 28614967798255360738075855336, 36807105632713067538713071245, 38800533909198065022758987247, 33530200082688915897598618003, 23689712254752535222202290781, 13601500601253554642901782930, 6282125665096201962183452662, 2297786047646640592633403658, 649935574786226137339883106, 137015627717939834273921665, 20254484097434584197014507, 1872263235897314505606383, 81402749386839761113321]

/-- `D2 = ∏_{i=1}^{26}(13 n+i) · ∏_{i=1}^{18}(9 n+i) · ∏_{i=1}^{10}(5 n+i)` — degree 54. -/
def d2 : List ℤ :=
  [9369643779479875057613736062387591577600000000000, 901437221204781455472223406790306045100032000000000, 41305172664022673691552941667340636974061977600000000, 1204099852204508291919699909248294292746749870080000000, 25160692393547312643637665348067164586705403510784000000, 402497419710542056013871682863323680466418969398476800000, 5140078077457476089729659112031891787820711885710295040000, 53945490193138560379799868298523963900841752405666168832000, 475318729349046850703847988130959075600829458334846917017600, 3573965810600579881221172433710244165766797005779658447257600, 23229860277078680921288205365662107558700159061363431401062400, 131883956984883347601229562111621584355107748955546878607360000, 659632726596354041872239441750530249629621643261836513667481600, 2927363463149845463512266428162140712442738693961878176104857600, 11596573972320423507181916944398459694742073040819672191787622400, 41217898753517869343395212513785526565301620665712751399950848000, 132023189445253408008436761272245862415861490704628733335787673600, 382526843215840759467940614959327724859288883780360996595368985600, 1005853999556405101284598450400057205851809111185427183974326054400, 2407077635788256605537259133089767740917312224595434409887416096000, 5255087650841245629416746840846997455956858374559814069569542121600, 10488388230167201051806952530831874032431847704459923820310188849600, 19171142943314314836143122648002831468442186634033849016210294650400, 32140234161296346206566663888490815782054194804140372659539198574000, 49482627631008327206109627956503239333885641241273223590731447262600, 70032114728312272709737477072995333499833493664618061659197193309100, 91185013743065782634154993576846442011405247070160920623739121439650, 109289726236010540442007845602212607328629742636335587175587182762375, 120620807458917706096505243128549325184309998455952034977203425548025, 122608374249400382517082201648859061262442251699994700346127388240525, 114776079170760542000418544893734900284101977635065082572596992233225, 98924308183783739216399324733613005984767893962002290155850205981250, 78463493967324499225335453772751973519583959388905304221459997332150, 57231964242591061211802501674601227659912356143040539483719064263650, 38353381167151302039163025480596336577353767896870942491356294800100, 23584992294945701942356724100372881810187760950030351727209004840125, 13288689023802998113399575576631929327376836815666951973635688598275, 6847779881590677855958377054816369039405681295131444642679411493775, 3220230085995220062161739421661351693446324543066421832573497634975, 1378349782240082087075852836991209271988920292650965496851502401500, 535329282646555348062198719563981704261110833780447332788598045900, 187963616289285553523911448233127269781241516688601598719633975400, 59404257661418288726540506966640348889694781984947681140578630850, 16810541168254090157152199814594697119945682924252818346214276625, 4232851147803455916124130949721631561244129759145980278072921775, 941126599678705941211368748757576668386305965437992817245545275, 183033650477373462295765515892900614547006210294092515634315975, 30771203233608696367782472690270441475985611716470964751231250, 4404500702760424481287307713193206865188196499148884038793750, 526102538532376314407420502696537022271055654775957435406250, 51010508678327053304282351244079780625810978023518807375000, 3856164164067036370327934667202010774497076616949716796875, 213177274023726484279767056772743528087223854642033203125, 7664207052504467790642129988927483704837891612041015625, 134459772850955575274423333139078661488384063369140625]

theorem n2_ascL : n2 = ascL 11 22 := by decide +kernel

theorem d2_ascL : d2 = mulZ (mulZ (ascL 13 26) (ascL 9 18)) (ascL 5 10) := by
  decide +kernel

/-- `Nj` at `candidateM` and `j = 2`, in numerals. -/
theorem nj2_num (n : ℕ) : Nj candidateM n 2 = ascN (11 * n) 22 := rfl

/-- `Dj` at `candidateM` and `j = 2`, in numerals. -/
theorem dj2_num (n : ℕ) : Dj candidateM n 2
    = ascN (13 * n) 26 * ascN (9 * n) 18 * ascN (5 * n) 10 := rfl

/-- The literal `n2` evaluates to the rebase numerator. -/
theorem n2_eval (n : ℕ) : hornerZ n2 (n : ℤ) = ((Nj candidateM n 2 : ℕ) : ℤ) := by
  rw [n2_ascL, hornerZ_ascL, nj2_num]

/-- The literal `d2` evaluates to the rebase denominator. -/
theorem d2_eval (n : ℕ) : hornerZ d2 (n : ℤ) = ((Dj candidateM n 2 : ℕ) : ℤ) := by
  rw [d2_ascL]
  simp only [hornerZ_mulZ, hornerZ_ascL, dj2_num]
  push_cast
  ring

theorem d2_ne_zero (n : ℕ) : ((hornerZ d2 (n : ℤ) : ℤ) : ℚ) ≠ 0 := by
  rw [d2_eval]
  exact_mod_cast Dj_ne_zero candidateM n 2

/-- **The Π-rebase at `j = 2`**, in `Zeta2StarIdII`'s own vocabulary: the Pochhammer literals
`n2`/`d2` that part (ii) is stated against ARE `Pin (n+2)/Pin n`. -/
theorem pin_j2 (n : ℕ) :
    candidateM.Pin (n + 2) * ((hornerZ d2 (n : ℤ) : ℤ) : ℚ)
      = candidateM.Pin n * ((hornerZ n2 (n : ℤ) : ℤ) : ℚ) := by
  -- `linear_combination` and NOT `exact_mod_cast`: on a mismatched goal `norm_cast` searches
  -- until the heartbeat limit, and a falsifier arm that RESOURCE-ERRORS has rejected nothing
  -- (LEAN.md §3).  `linear_combination` ends in `ring1`, which refuses in milliseconds — which
  -- is what `falsify_staridpi.sh`'s A3 and A5 need in order to mean anything.  MEASURED: both
  -- arms red through `whnf` timeouts under `exact_mod_cast`, at 200000 heartbeats and at
  -- 2000000, and through `ring failed` here.
  have key := Pin_shift candidateM n 2
  rw [n2_eval, d2_eval]
  push_cast
  push_cast at key
  linear_combination key

/-- The quotient spelling at `j = 2` — unconditional. -/
theorem pin_ratio_j2 (n : ℕ) :
    candidateM.Pin (n + 2) / candidateM.Pin n
      = ((hornerZ n2 (n : ℤ) : ℤ) : ℚ) / ((hornerZ d2 (n : ℤ) : ℤ) : ℚ) := by
  have hP : candidateM.Pin n ≠ 0 := ne_of_gt (candidateM.Pin_pos n)
  have hD := d2_ne_zero n
  field_simp
  linear_combination pin_j2 n

/-- `N3 = ∏_{i=1}^{33} (11·n + i)` — degree 33. -/
def n3 : List ℤ :=
  [8683317618811886495518194401280000000, 390547670406641210984106048041779200000, 7934318228007366819672245483054039040000, 98141597840775860516196605891950018560000, 837637329076055614476065108273893908480000, 5289200232727640071212381982803757996769280, 25833387818645691454458646045290015253733376, 100646664150600720763393297979757199022493696, 319878072670929544051813599884832028001239296, 843500289662919911310029627729023494382185216, 1869723368099476367150664037873283790913392384, 3519727675798815942199979538927350021972049664, 5672709763513290969814995590781285927469306464, 7877500341402456088826038186286310654378290464, 9472374439229598709379657462358465120801775440, 9900098233266572817808559737759648949264494240, 9018031531282886347169535398826655666967726865, 7172003331530861336649571027117527350186089515, 4984201086980876050748944105385699947082201880, 3026613001532322111773977314008996271720897480, 1604366216831782069536988912341777764256361980, 740943260405605609116680656981333983254028180, 297215659493995402879393919021316851410767240, 103104595221188052450998081245131327414770040, 30750118775508742053420051296280925377158790, 7823076579320852012778183452253790862480610, 1680221711667198226767902390158029888715944, 300469648913031071508170452856364049260024, 43902865786505863464918715910371017960924, 5104166606035017407674829501388554647604, 453979982067872450476876009499200373736, 29001883737416266602254571131827474856, 1184482875414278215191090157611765681, 23225154419887808141001767796309131]

/-- `D3 = ∏_{i=1}^{39}(13 n+i) · ∏_{i=1}^{27}(9 n+i) · ∏_{i=1}^{15}(5 n+i)` — degree 81. -/
def d3 : List ℤ :=
  [290447390478888914533762983285418224900244511355297465882970059649843200000000000000000, 31051822080098684781088486021175230345980404813940651820599859329311440896000000000000000, 1595470264829286581853138675165076977046860592261734259274981727402846521917440000000000000, 52621626087645492275647102391222998206712362767098257708836588483859435661295616000000000000, 1255192372405183742305544768656202942410037426563561815362310912467436695918424883200000000000, 23126483929689486655605453767849089358556678139818508909673544492850888195272867840000000000000, 343218157018982735192887938078140989533572632885609454737113488974462312880221383032832000000000, 4224186602639565483297440578651054494999049263052151494947161107882109997476564603555020800000000, 44050012577400440916148440057523418304080277697010077999182275339368760428770937154159247360000000, 395672490736731224568352892404763947044501075089017754308917151347866953856524417962187161600000000, 3101597170928514001701668644950531572067296998479209365385065484175236861537945276955610211942400000, 21443848428981471936765569430974878207497006488756627752523511883200449338176602001412768671989760000, 131918247600419079624187010894619244423978628054591986289646709818537592611179733622447390360338432000, 727451710658762775748272894293650932221516391312008879914412628420458209260744934962783764594294784000, 3618593266692738622287460251311026264445909400318528063526910358437034994179728255594838111006228480000, 16325747723503122158849964315729050178382798038705769901170560097457101167050588980451457857539276800000, 67121051253524007178446896510858013510384482058187744002462181657464444843858591726990906859110531072000, 252521637211774789032362126866475491954942361764455624350692268954040838836352675041843048758844063744000, 872535926561086975251093628502452604407531114165324660169398719460986752087288077927349036399595356160000, 2777955316871032186647065830744607445037234036850140268575073989142305706067082544541566370647650467840000, 8173056394848231333480857546703552982513246564270816933044423410413846237539228115813942708735238602752000, 22278703386494041071658296498252860880170247882833368093871894141099488621817623967312362698000555638784000, 56397040746785923029522362901331750343879430270121115595659774272352042271323229592401969762481896407040000, 132861322814784800817930628525238922499020715202695251816352548636708495760507279415136320679507652730880000, 291838977719252403397503925234712252570030841130067280242703940354829298779859209137474963317877996634112000, 598740508521378202662270030826272173123278527917426314645220262752702727823687530767422801416060684509184000, 1149112467663709395487637902336605146510662064758324181555598423466177026735632370453187079827039733176320000, 2065996759657082149079901000436351321483334917369186166738063283447709485090334200349712674159092838456320000, 3484153205400118487564581423676068722493970492859980236048265661376693844929116973876321063257214987226112000, 5517855938485652610898495566148709367635214229991480718630591358555051201269986907355913440242525431729664000, 8214970132908105733862655466207179414135075296163399632556099708937828191062212181724503535013278239318400000, 11508450677948050247515963133329236439950859573850116846397437436206191749310572199251315365765313222854080000, 15183594056678701861318407484097305738774324845922969503345596655797041651506181930554254344271853661119936000, 18880451535141823968506478505782987676462236196119672344619446435708423224693229970803396244580059569411232000, 22142537499983120611464565208244004965620094925877822209509896164526942593467336196682195507700507988123740000, 24506578757712453827415177377568008819726489601372144066821506593421715371080703056071933964218120839203750000, 25609961091060118935244719629155223251240311395254467550335287454709283785766256029013365476443837249815106000, 25281668039728404601677763295070247604325601392236257477816629424128076936793482254451952776001019526923837000, 23585379864139685946070366377950702017830042306179025228454447741511232454293898700180094327778681613020098750, 20799897643707803437812908272377202734058829564807935940559189163714697621829141942740601389284502190893716875, 17344959083181613485595709540303928219931579982010906469304720440565364918321073662033097051215400682726889750, 13679303135919984249994766615041915381268246195799743331692470307526764120015094307802999089450622934361810125, 10204475960086579380615750866622093849298094931619395152771632714621807509129556119763113053415985445605807500, 7200847266526172004403032387291308338699102182545282021756333056785493570902303342985507727868031013823183750, 4806682031565305401715979665939340761242839769641059014040356904722858965690246035034975308729412514623313500, 3034947569396662915051681911987178644492697570848535096416624302673158303893083317856853448499976050754688250, 1812374726544564978974390393087532070691430770234311305646900338033963710016861609239548497868766075057028750, 1023420329403151089662647377617784647382562977188632079428270075521072763673167705833477039168606427531006875, 546333577150139878029862513142794520740190530736960327795599762535030139404509347763118676871979536682169750, 275624197055402229802079663378651274125353578670079096762800429569400878420237989445056497520339462973175125, 131358443052574511191481121895096415602407970793348403570205693222415152204663573409947342233511825293450000, 59111446544609020619522820131410025967299580564868148942329152952473463532536704823044866333929958082285000, 25102327678110867988954646350695443527867589427982253657972036883520471554029230825202046284556522983382000, 10053165219333946780690833946749020900685162758160405904676451908974767599127980674092291688048102778109000, 3794150845334827070555770730894621880988452084380354619159962204691478657198901178863485661830114573717500, 1348284215737414599561061024981198120860220311806771700410377057329307588730551537959986321563968424293750, 450699662797666146633823209142991160404350403719705568753498195553725323080056481469947159205395291259500, 141567282590837894055322970793480041307907606593401635168281042747039157013331434150298940560302233700250, 41733141978784134030562304521984660413238753267928844732704022016240038379198984105614242448256526085000, 11530541723825542858588184393620319969343609056181913185921513296169394601693132977740241004054961802500, 2981290816140629463085760464694569319461029931240852428658480738341954869242755962806102768280135577000, 720110360000611553273232607700006825360216712708498801798477705440141372784034903163091973522894921500, 162179331621074791768040277288874493889288532605418297090042278691683903427913404445228351571086527500, 33982052700897997312109637923672937118791351401181174622933168087757886520867651740667698423481248750, 6608385331102644497599580220022956880353771859556527260605312475360015670597681294424296805453449500, 1189391486534105406709370928766407675401623787435129493310364863215566548623900617216210051223815250, 197498255802666367636022413645921627713130885329432595485124563668473965582162680320644698265870000, 30146557276496946781668447016140248034062820706352691353563083598267483489514051916524072185095000, 4212470962120017769432421547244041470343691567219511325451173518226767245898492951080631890812000, 536239935737730673800802604258353881256102913547812974464296164681095048008650249081284611364000, 61836292955097415205933022961708231428636595936544028213380992193979554266962978889851749343750, 6416180981491861829644983013473960693078509178556656796629295121116325067055196054740101609375, 594243890064555190259450473278422378588090558995514813300558098834218162318720386841769218750, 48646353222709100201293815167765091239666850324404448354962272212846716239310779375514765625, 3477304678477663998575218830022299836355570353604113499737469052499035197249976997929687500, 213699963313563059224203541377651268484552909914627559641684618863914566561859236464843750, 11063173861063170321878885186216616059679669915188495893585304360170761120673819335937500, 469170658484154955420169715144945779649019144277048671560060779529986025974862597656250, 15650322171556871131288928457290077740332732737486268661554436019336587012048339843750, 385052809959217840251727643378323596334921458788873616887178240166477746478271484375, 6212395622181785330526706176558668745001979957595295565788713394287427917480468750, 49304727160172899448624652194910069404777618711073774331656455510217681884765625]

theorem n3_ascL : n3 = ascL 11 33 := by decide +kernel

theorem d3_ascL : d3 = mulZ (mulZ (ascL 13 39) (ascL 9 27)) (ascL 5 15) := by
  decide +kernel

/-- `Nj` at `candidateM` and `j = 3`, in numerals. -/
theorem nj3_num (n : ℕ) : Nj candidateM n 3 = ascN (11 * n) 33 := rfl

/-- `Dj` at `candidateM` and `j = 3`, in numerals. -/
theorem dj3_num (n : ℕ) : Dj candidateM n 3
    = ascN (13 * n) 39 * ascN (9 * n) 27 * ascN (5 * n) 15 := rfl

/-- The literal `n3` evaluates to the rebase numerator. -/
theorem n3_eval (n : ℕ) : hornerZ n3 (n : ℤ) = ((Nj candidateM n 3 : ℕ) : ℤ) := by
  rw [n3_ascL, hornerZ_ascL, nj3_num]

/-- The literal `d3` evaluates to the rebase denominator. -/
theorem d3_eval (n : ℕ) : hornerZ d3 (n : ℤ) = ((Dj candidateM n 3 : ℕ) : ℤ) := by
  rw [d3_ascL]
  simp only [hornerZ_mulZ, hornerZ_ascL, dj3_num]
  push_cast
  ring

theorem d3_ne_zero (n : ℕ) : ((hornerZ d3 (n : ℤ) : ℤ) : ℚ) ≠ 0 := by
  rw [d3_eval]
  exact_mod_cast Dj_ne_zero candidateM n 3

/-- **The Π-rebase at `j = 3`**, in `Zeta2StarIdII`'s own vocabulary: the Pochhammer literals
`n3`/`d3` that part (ii) is stated against ARE `Pin (n+3)/Pin n`. -/
theorem pin_j3 (n : ℕ) :
    candidateM.Pin (n + 3) * ((hornerZ d3 (n : ℤ) : ℤ) : ℚ)
      = candidateM.Pin n * ((hornerZ n3 (n : ℤ) : ℤ) : ℚ) := by
  -- `linear_combination` and NOT `exact_mod_cast`: on a mismatched goal `norm_cast` searches
  -- until the heartbeat limit, and a falsifier arm that RESOURCE-ERRORS has rejected nothing
  -- (LEAN.md §3).  `linear_combination` ends in `ring1`, which refuses in milliseconds — which
  -- is what `falsify_staridpi.sh`'s A3 and A5 need in order to mean anything.  MEASURED: both
  -- arms red through `whnf` timeouts under `exact_mod_cast`, at 200000 heartbeats and at
  -- 2000000, and through `ring failed` here.
  have key := Pin_shift candidateM n 3
  rw [n3_eval, d3_eval]
  push_cast
  push_cast at key
  linear_combination key

/-- The quotient spelling at `j = 3` — unconditional. -/
theorem pin_ratio_j3 (n : ℕ) :
    candidateM.Pin (n + 3) / candidateM.Pin n
      = ((hornerZ n3 (n : ℤ) : ℤ) : ℚ) / ((hornerZ d3 (n : ℤ) : ℤ) : ℚ) := by
  have hP : candidateM.Pin n ≠ 0 := ne_of_gt (candidateM.Pin_pos n)
  have hD := d3_ne_zero n
  field_simp
  linear_combination pin_j3 n

/-! ## 5. Receipts (LEAN.md §1 — exit 0 is not an attestation)

The list is DERIVED from the emitted text, not typed, so a lemma cannot be added without its
receipt.  Read them with `python3 tools/lean_falsifier_restore.py audit-probe <file>` AND read
`lean`'s own rc separately: the predicate scores a parse-broken file GREEN (found_bugs
2026-09-14), so neither channel attests alone. -/

#print axioms hornerZ_addZ
#print axioms hornerZ_smulZ
#print axioms hornerZ_mulZ
#print axioms hornerZ_map_mul
#print axioms ascN_pos
#print axioms ascN_ne_zero
#print axioms hornerZ_ascL
#print axioms factorial_shift
#print axioms Nj_pos
#print axioms Dj_pos
#print axioms Dj_ne_zero
#print axioms Pin_shift
#print axioms Pin_shift_div
#print axioms n1_ascL
#print axioms d1_ascL
#print axioms nj1_num
#print axioms dj1_num
#print axioms n1_eval
#print axioms d1_eval
#print axioms d1_ne_zero
#print axioms pin_j1
#print axioms pin_ratio_j1
#print axioms n2_ascL
#print axioms d2_ascL
#print axioms nj2_num
#print axioms dj2_num
#print axioms n2_eval
#print axioms d2_eval
#print axioms d2_ne_zero
#print axioms pin_j2
#print axioms pin_ratio_j2
#print axioms n3_ascL
#print axioms d3_ascL
#print axioms nj3_num
#print axioms dj3_num
#print axioms n3_eval
#print axioms d3_eval
#print axioms d3_ne_zero
#print axioms pin_j3
#print axioms pin_ratio_j3

end Zeta2StarIdPi
