/-
# Row X-L1 (data half) — the certified operator's leading coefficients

GENERATED by `external_tests/zeta2_xl1/gen_xl1_lean.py` from the repo's own copies of record:
`chain_close_design/results/solution_a.txt` (rebuilt through the landed `l4_data.py` /
`closure.py`, in under a second) for the four cleared leading coefficients, and the LANDED
`Zeta2L5Char.lean` for D1's majorant constants — parsed out of that theorem rather than
retyped, so the literals here are byte-identical to the ones it proves about.  Do not
hand-edit: `gen_xl1_lean.py --check` regenerates and diffs, and
`falsify_xl1_encoding.sh` shows that check going red.

The generator refuses to emit unless every one of these holds exactly:
all four `cleared_j` have degree 510 and a positive leading coefficient; `lead_j * l₃ =
l_j * lead₃` against `Zeta2D4Data`'s χ_op; `lead₀`/`lead₃` equal the landed
`Zeta2L4.c0lead`/`c3lead`; `A_j = |lead_j/lead₃| · (1 + 10⁻¹²)` and `ρ = A₂ · (1 + 10⁻³⁰)`;
and `ρ` lies strictly above `Zeta2D4Data.chiOp_root_enclosure`'s upper endpoint but within
10⁻¹¹ of it.

Lines here exceed the 100-column limit by construction — a 658-digit coefficient does not fit,
and breaking the literal would obscure that it is a single number.

The lemmas that CONSUME these facts are in `Zeta2XL1.lean`.
-/
import Mathlib.Tactic.NormNum
import Zeta2D4Data

namespace Zeta2XL1Data

/-- The common degree of the four cleared polynomials `cleared_0 .. cleared_3`. -/
def dcl : ℕ := 510

/-- The leading coefficient of `cleared_0` (632 digits). -/
def lead0 : ℤ :=
  75140545452412733504647728260011708154323154591918821978170551439520151245215194629841676969176851827410738618604521269283059805441895198705623681684385628243700281272584651499124997746388554163147409861792909661370156658164188907807332702085226647731714308275427954482067915413684021646092484850558410336498666490206101696112906868829437136117005620816361878469140590619713402302248557945606071570413764554588895818458930940450107182297328973465188827049218274430738697370814644672652466390733756071555608673712930389340295573314436650963617392609194602414402064798668908200372658319130624000000000000000000000000000000000000000000

/-- The leading coefficient of `cleared_1` (645 digits). -/
def lead1 : ℤ :=
  641813450118866773273050747851508747195386312544889672818199126500413243768251433915982876325502653900144910829422472380088435812272157154911382523439521423312751716001901572641214970752926620372800635387775997711234865247994967687574560566042886800734787119761363724690523095809256308462585379433279122611669469323031403631333150894073367212246172544837720422568604810382660759530829433995046435060997133512518991791736079384621674011768774782764155501956709722040711129674390678062486622590540917331155158373006676183008121610752666544512510896568482355412935359002022206025972444617910376846055954125197777305600000000000000000000000000000000

/-- The leading coefficient of `cleared_2` (658 digits). -/
def lead2 : ℤ :=
  1440953905778882829345089102452107653283514180741521796930391769882403229207557577298344636591687911705880248858851225362906120658692488423648072262490656549293110643012602164952862050664705698701409748011594251951731800812714141612076370814575701294285323453698583554646349133870251206422764084911725718339501035905756064706626904058126563266110734603762218572145665364703739547194001343934147437329210746204415793788466653416489840030205273070549350614547860244331231129953555552910883409326961951080074913336473976897908280154223686246590177410370340193401818767706876286698686707424947389168618084534104976638959359413452800000000000000000000000000000000

/-- The leading coefficient of `cleared_3` (639 digits). -/
def lead3 : ℤ :=
  801092542219035682365007832287428829341901468567107095427913620625252405894247663856923936470838566684940938510958764923440150604095540553693775093206807880728236217007658305452360804696769945759023363017467133718179698767134237250797665540417309987967620757371672958537797165880686849327810082678433547049900209503855414034624606657874110231526586201445726010579275065622994521821090900276497770298807517764020756640962587465559066482800471048402148927098338736697539930228676504270637746651634088827679297541967763775259246916538548579886782149518343672343222687805347402065250478981120000000000000000000000000000000000000000000000000000

/-- D1's `A₀`, as a numerator over the common denominator `cden`. -/
def aNum0 : ℤ :=
  2741632106998336567415663309345235949657580125838723302650021314831907901495545642121164947748184204101562500000000000000

/-- D1's `A₁`, as a numerator over the common denominator `cden`. -/
def aNum1 : ℤ :=
  23417668197040748338022190405224217689143939806454802490233713716792907632411712788269306418911349378394210937500000000000000000000000

/-- D1's `A₂`, as a numerator over the common denominator `cden`. -/
def aNum2 : ℤ :=
  52575682928599102498430580673173383214883189958167758982100860807556138368212366034085304201804927737130885336859889000000000000000000000000000000

/-- D1's `ρ`, as a numerator over the common denominator `cden`. -/
def rhoNum : ℤ :=
  52575682928599102498430580673225958897811789060666189562774034190771021558170533793067405062612483875499097702893974304201804927737130885336859889

/-- The common denominator of `A₀`, `A₁`, `A₂` and `ρ`. -/
def cden : ℤ :=
  29229239968897644225045915008195854090760705787942922658969655705600000000000000000000000000000000000000000000000000000000000000

/-- The upper endpoint of `Zeta2D4Data.chiOp_root_enclosure`, i.e. the certified
integer ceiling of the dominant root modulus `|λ₁|`. -/
def rootHi : ℤ := 1798735888599616356

/-! ## Positivity — every one of these is an edge the degree facts depend on -/

/-- `cleared_0` really does have a nonzero top coefficient, so its degree is
`dcl` and not something smaller. -/
theorem lead0_pos : 0 < lead0 := by norm_num [lead0]

/-- `cleared_1` really does have a nonzero top coefficient, so its degree is
`dcl` and not something smaller. -/
theorem lead1_pos : 0 < lead1 := by norm_num [lead1]

/-- `cleared_2` really does have a nonzero top coefficient, so its degree is
`dcl` and not something smaller. -/
theorem lead2_pos : 0 < lead2 := by norm_num [lead2]

/-- `cleared_3` really does have a nonzero top coefficient, so its degree is
`dcl` and not something smaller. -/
theorem lead3_pos : 0 < lead3 := by norm_num [lead3]

/-- The common denominator is positive, so `A_j` and `ρ` are the ratios they look like. -/
theorem cden_pos : 0 < cden := by norm_num [cden]

/-- `ρ`'s numerator is positive, which with `cden_pos` is `poincare_upper_bound`'s `hρ`. -/
theorem rhoNum_pos : 0 < rhoNum := by norm_num [rhoNum]

/-! ## The exact relations D1's constants were built to satisfy -/

/-- **`A_0` is EXACTLY `|lead_0/lead₃| · (1 + 10⁻¹²)`.**  An equality, not an
inequality: it pins the margin as well as the direction, so a regenerated `A_0`
that drifted would fail here rather than pass a slack bound. -/
theorem ratio0_exact : aNum0 * lead3 * 10 ^ 12 = lead0 * cden * (10 ^ 12 + 1) := by
  norm_num [aNum0, lead3, lead0, cden]

/-- **`A_1` is EXACTLY `|lead_1/lead₃| · (1 + 10⁻¹²)`.**  An equality, not an
inequality: it pins the margin as well as the direction, so a regenerated `A_1`
that drifted would fail here rather than pass a slack bound. -/
theorem ratio1_exact : aNum1 * lead3 * 10 ^ 12 = lead1 * cden * (10 ^ 12 + 1) := by
  norm_num [aNum1, lead3, lead1, cden]

/-- **`A_2` is EXACTLY `|lead_2/lead₃| · (1 + 10⁻¹²)`.**  An equality, not an
inequality: it pins the margin as well as the direction, so a regenerated `A_2`
that drifted would fail here rather than pass a slack bound. -/
theorem ratio2_exact : aNum2 * lead3 * 10 ^ 12 = lead2 * cden * (10 ^ 12 + 1) := by
  norm_num [aNum2, lead3, lead2, cden]

/-- **`ρ` is EXACTLY `A₂ · (1 + 10⁻³⁰)`.**  The inflation above `A₂` is not decoration:
`Zeta2XL1.majorant_fails_at_A2` shows the majorant cubic FAILS at `ρ = A₂`. -/
theorem rho_exact : rhoNum * 10 ^ 30 = aNum2 * (10 ^ 30 + 1) := by
  norm_num [rhoNum, aNum2]

/-! ## `ρ` against the certified spectrum -/

/-- `1 < ρ`.  The conclusion X-L1 delivers at these constants is therefore a GROWTH
bound, not a decay bound — `ρ ≈ 1.7987e18` is the operator's dominant root modulus. -/
theorem cden_lt_rhoNum : cden < rhoNum := by norm_num [cden, rhoNum]

/-- **`ρ` lies strictly above `Zeta2D4Data.chiOp_root_enclosure`'s upper endpoint.**
That enclosure brackets `|λ₁|` between two consecutive integers, so this says D1's `ρ`
is a valid growth rate for the certified operator and ties the two landed artifacts
together at the kernel rather than in prose. -/
theorem rootHi_lt_rho : rootHi * cden < rhoNum := by norm_num [rootHi, cden, rhoNum]

/-- …and by no more than `10⁻¹¹`, so `ρ` is not a slack over-estimate. -/
theorem rho_lt_rootHi_loose :
    rhoNum * 10 ^ 11 < rootHi * (10 ^ 11 + 1) * cden := by
  norm_num [rootHi, cden, rhoNum]

/-! ## The tie to `Zeta2D4Data`'s χ_op -/

/-- `lead_0 / lead₃ = ℓ_0 / ℓ₃`: the ratio X-L1 bounds is the ratio D1 certified.
χ_op is the PRIMITIVE integer cubic of these same four leading coefficients
(`closure.stage_chi`), so the two differ by one positive integer content. -/
theorem lead0_prop : lead0 * Zeta2D4Data.l3 = Zeta2D4Data.l0 * lead3 := by
  norm_num [lead0, lead3, Zeta2D4Data.l0, Zeta2D4Data.l3]

/-- `lead_1 / lead₃ = ℓ_1 / ℓ₃`: the ratio X-L1 bounds is the ratio D1 certified.
χ_op is the PRIMITIVE integer cubic of these same four leading coefficients
(`closure.stage_chi`), so the two differ by one positive integer content. -/
theorem lead1_prop : lead1 * Zeta2D4Data.l3 = Zeta2D4Data.l1 * lead3 := by
  norm_num [lead1, lead3, Zeta2D4Data.l1, Zeta2D4Data.l3]

/-- `lead_2 / lead₃ = ℓ_2 / ℓ₃`: the ratio X-L1 bounds is the ratio D1 certified.
χ_op is the PRIMITIVE integer cubic of these same four leading coefficients
(`closure.stage_chi`), so the two differ by one positive integer content. -/
theorem lead2_prop : lead2 * Zeta2D4Data.l3 = Zeta2D4Data.l2 * lead3 := by
  norm_num [lead2, lead3, Zeta2D4Data.l2, Zeta2D4Data.l3]

/-! ### Receipts (LEAN.md §1 — exit 0 is not an attestation) -/

#print axioms lead0_pos
#print axioms lead1_pos
#print axioms lead2_pos
#print axioms lead3_pos
#print axioms cden_pos
#print axioms rhoNum_pos
#print axioms ratio0_exact
#print axioms ratio1_exact
#print axioms ratio2_exact
#print axioms rho_exact
#print axioms cden_lt_rhoNum
#print axioms rootHi_lt_rho
#print axioms rho_lt_rootHi_loose
#print axioms lead0_prop
#print axioms lead1_prop
#print axioms lead2_prop

end Zeta2XL1Data
