/-
# Row PT-P, layer 10 — the 21 RUN-FREE profile pieces, stratum by stratum, and each piece
# discharged for the harmonic side (GENERATED by `gen_ptp_runfree.py`; do not edit by hand)

On a run-free piece every residue carries at least `φ̃` times (`ptp_mechanism_probe.py` arm A2:
the eight run-admitting strata all lie in the five run-carrying pieces), so each block sum is
divisible by `p^φ̃` TERMWISE through `Zeta2PtpBlock.blockSum_dvd_of_noShort`.  On each stratum
where the six floors are constant, `φ̃ ≤ bitsR p r u` is `omega` after `Zeta2PtpCong`'s
`residue_spec` / `bit*_abstract` rewrites — `bits_S1 … bits_S7`'s proof with the stratum's own
floors.  Per piece: the strata bounds, the φ̃ wire (`Zeta2PtpS7.phiT_of_mem`), and the dispatcher.

`gen_ptp_runfree.py --check` reds if this file drifts from its generator (LEAN.md §10).

VINTAGE: toolchain leanprover/lean4:v4.34.0-rc2, mathlib 5aedf732 (current), buildbox.
-/
import Zeta2Defs
import Zeta2Arith
import Zeta2QnInt
import Zeta2Profile
import Zeta2PhiT
import Zeta2PtpPolar
import Zeta2PtpRun
import Zeta2PtpStratum
import Zeta2PtpCong
import Zeta2PtpBlock
import Zeta2PtpS7
import Zeta2CarryFull

set_option maxRecDepth 20000

namespace Zeta2PtpRunFree

open Zeta2Defs Zeta2Arith Zeta2PhiT Zeta2PtpPolar Zeta2PtpBlock Zeta2PtpS7 Zeta2PtpCong
  Zeta2PtpRun Zeta2PtpStratum Nat Finset


/-! ## Piece 1: `[1/15, 1/13)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[1/15, 1/13)`: floors `⌊13x⌋=0, ⌊9x⌋=0, ⌊5x⌋=0, ⌊11x⌋=0, ⌊4x⌋=0, ⌊2x⌋=0`. -/
theorem bits_p1_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 1 * p ≤ 15 * r) (hhi : 13 * r < 1 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 0) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 0) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 0) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 0) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 0) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p1_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 1 * p ≤ 15 * (n % p)) (hhi : 13 * (n % p) < 1 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p1_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece1 {x : ℚ} (h1 : 1 / 15 ≤ x) (h2 : x < 1 / 13) : phiT x = 1 := by
  have h := phiT_of_mem (a := 1 / 15) (b := 1 / 13) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece1_res {n p : ℕ} (hp : 0 < p) (hlo : 1 * p ≤ 15 * (n % p))
    (hhi : 13 * (n % p) < 1 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece1 ?_ ?_
  · have h := (fract_ge_iff n p 1 15 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 1 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 1 `[1/15, 1/13)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece1_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 1 * p ≤ 15 * (n % p))
    (hhi : 13 * (n % p) < 1 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece1_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p1_1 hp0 (by omega) (by omega)) t


/-! ## Piece 3: `[2/17, 1/7)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[2/17, 1/7)`: floors `⌊13x⌋=1, ⌊9x⌋=1, ⌊5x⌋=0, ⌊11x⌋=1, ⌊4x⌋=0, ⌊2x⌋=0`. -/
theorem bits_p3_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 2 * p ≤ 17 * r) (hhi : 7 * r < 1 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 1) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 1) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 0) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 1) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 0) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p3_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 2 * p ≤ 17 * (n % p)) (hhi : 7 * (n % p) < 1 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p3_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece3 {x : ℚ} (h1 : 2 / 17 ≤ x) (h2 : x < 1 / 7) : phiT x = 1 := by
  have h := phiT_of_mem (a := 2 / 17) (b := 1 / 7) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece3_res {n p : ℕ} (hp : 0 < p) (hlo : 2 * p ≤ 17 * (n % p))
    (hhi : 7 * (n % p) < 1 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece3 ?_ ?_
  · have h := (fract_ge_iff n p 2 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 1 7 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 3 `[2/17, 1/7)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece3_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 2 * p ≤ 17 * (n % p))
    (hhi : 7 * (n % p) < 1 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece3_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p3_1 hp0 (by omega) (by omega)) t


/-! ## Piece 4: `[1/7, 2/13)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[1/7, 2/13)`: floors `⌊13x⌋=1, ⌊9x⌋=1, ⌊5x⌋=0, ⌊11x⌋=1, ⌊4x⌋=0, ⌊2x⌋=0`. -/
theorem bits_p4_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 1 * p ≤ 7 * r) (hhi : 13 * r < 2 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 1) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 1) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 0) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 1) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 0) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p4_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 1 * p ≤ 7 * (n % p)) (hhi : 13 * (n % p) < 2 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p4_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece4 {x : ℚ} (h1 : 1 / 7 ≤ x) (h2 : x < 2 / 13) : phiT x = 2 := by
  have h := phiT_of_mem (a := 1 / 7) (b := 2 / 13) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece4_res {n p : ℕ} (hp : 0 < p) (hlo : 1 * p ≤ 7 * (n % p))
    (hhi : 13 * (n % p) < 2 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece4 ?_ ?_
  · have h := (fract_ge_iff n p 1 7 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 2 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 4 `[1/7, 2/13)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece4_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 1 * p ≤ 7 * (n % p))
    (hhi : 13 * (n % p) < 2 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece4_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p4_1 hp0 (by omega) (by omega)) t


/-! ## Piece 5: `[2/13, 2/11)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[2/13, 2/11)`: floors `⌊13x⌋=2, ⌊9x⌋=1, ⌊5x⌋=0, ⌊11x⌋=1, ⌊4x⌋=0, ⌊2x⌋=0`. -/
theorem bits_p5_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 2 * p ≤ 13 * r) (hhi : 11 * r < 2 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 2) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 1) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 0) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 1) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 0) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p5_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 2 * p ≤ 13 * (n % p)) (hhi : 11 * (n % p) < 2 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p5_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece5 {x : ℚ} (h1 : 2 / 13 ≤ x) (h2 : x < 2 / 11) : phiT x = 1 := by
  have h := phiT_of_mem (a := 2 / 13) (b := 2 / 11) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece5_res {n p : ℕ} (hp : 0 < p) (hlo : 2 * p ≤ 13 * (n % p))
    (hhi : 11 * (n % p) < 2 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece5 ?_ ?_
  · have h := (fract_ge_iff n p 2 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 2 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 5 `[2/13, 2/11)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece5_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 2 * p ≤ 13 * (n % p))
    (hhi : 11 * (n % p) < 2 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece5_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p5_1 hp0 (by omega) (by omega)) t


/-! ## Piece 6: `[2/11, 1/5)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[2/11, 1/5)`: floors `⌊13x⌋=2, ⌊9x⌋=1, ⌊5x⌋=0, ⌊11x⌋=2, ⌊4x⌋=0, ⌊2x⌋=0`. -/
theorem bits_p6_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 2 * p ≤ 11 * r) (hhi : 5 * r < 1 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 2) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 1) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 0) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 2) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 0) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p6_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 2 * p ≤ 11 * (n % p)) (hhi : 5 * (n % p) < 1 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p6_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece6 {x : ℚ} (h1 : 2 / 11 ≤ x) (h2 : x < 1 / 5) : phiT x = 2 := by
  have h := phiT_of_mem (a := 2 / 11) (b := 1 / 5) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece6_res {n p : ℕ} (hp : 0 < p) (hlo : 2 * p ≤ 11 * (n % p))
    (hhi : 5 * (n % p) < 1 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece6 ?_ ?_
  · have h := (fract_ge_iff n p 2 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 1 5 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 6 `[2/11, 1/5)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece6_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 2 * p ≤ 11 * (n % p))
    (hhi : 5 * (n % p) < 1 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece6_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p6_1 hp0 (by omega) (by omega)) t


/-! ## Piece 8: `[3/11, 4/13)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[3/11, 4/13)`: floors `⌊13x⌋=3, ⌊9x⌋=2, ⌊5x⌋=1, ⌊11x⌋=3, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p8_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 3 * p ≤ 11 * r) (hhi : 13 * r < 4 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 3) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 2) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 1) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 3) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p8_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 3 * p ≤ 11 * (n % p)) (hhi : 13 * (n % p) < 4 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p8_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece8 {x : ℚ} (h1 : 3 / 11 ≤ x) (h2 : x < 4 / 13) : phiT x = 2 := by
  have h := phiT_of_mem (a := 3 / 11) (b := 4 / 13) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece8_res {n p : ℕ} (hp : 0 < p) (hlo : 3 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 4 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece8 ?_ ?_
  · have h := (fract_ge_iff n p 3 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 4 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 8 `[3/11, 4/13)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece8_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 3 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 4 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece8_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p8_1 hp0 (by omega) (by omega)) t


/-! ## Piece 9: `[4/13, 4/11)`, `φ̃ = 1`, 2 stratum(s) -/

/-- stratum `[4/13, 1/3)`: floors `⌊13x⌋=4, ⌊9x⌋=2, ⌊5x⌋=1, ⌊11x⌋=3, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p9_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 4 * p ≤ 13 * r) (hhi : 3 * r < 1 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 4) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 2) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 1) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 3) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p9_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 4 * p ≤ 13 * (n % p)) (hhi : 3 * (n % p) < 1 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p9_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[1/3, 4/11)`: floors `⌊13x⌋=4, ⌊9x⌋=3, ⌊5x⌋=1, ⌊11x⌋=3, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p9_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 1 * p ≤ 3 * r) (hhi : 11 * r < 4 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 4) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 3) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 1) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 3) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p9_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 1 * p ≤ 3 * (n % p)) (hhi : 11 * (n % p) < 4 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p9_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece9 {x : ℚ} (h1 : 4 / 13 ≤ x) (h2 : x < 4 / 11) : phiT x = 1 := by
  have h := phiT_of_mem (a := 4 / 13) (b := 4 / 11) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece9_res {n p : ℕ} (hp : 0 < p) (hlo : 4 * p ≤ 13 * (n % p))
    (hhi : 11 * (n % p) < 4 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece9 ?_ ?_
  · have h := (fract_ge_iff n p 4 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 4 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 9 `[4/13, 4/11)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece9_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 4 * p ≤ 13 * (n % p))
    (hhi : 11 * (n % p) < 4 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece9_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (3 * (n % p)) (1 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p9_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p9_2 hp0 (by omega) (by omega)) t


/-! ## Piece 10: `[4/11, 5/13)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[4/11, 5/13)`: floors `⌊13x⌋=4, ⌊9x⌋=3, ⌊5x⌋=1, ⌊11x⌋=4, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p10_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 4 * p ≤ 11 * r) (hhi : 13 * r < 5 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 4) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 3) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 1) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 4) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p10_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 4 * p ≤ 11 * (n % p)) (hhi : 13 * (n % p) < 5 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p10_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece10 {x : ℚ} (h1 : 4 / 11 ≤ x) (h2 : x < 5 / 13) : phiT x = 2 := by
  have h := phiT_of_mem (a := 4 / 11) (b := 5 / 13) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece10_res {n p : ℕ} (hp : 0 < p) (hlo : 4 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 5 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece10 ?_ ?_
  · have h := (fract_ge_iff n p 4 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 5 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 10 `[4/11, 5/13)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece10_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 4 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 5 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece10_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p10_1 hp0 (by omega) (by omega)) t


/-! ## Piece 11: `[5/13, 2/5)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[5/13, 2/5)`: floors `⌊13x⌋=5, ⌊9x⌋=3, ⌊5x⌋=1, ⌊11x⌋=4, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p11_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 5 * p ≤ 13 * r) (hhi : 5 * r < 2 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 5) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 3) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 1) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 4) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p11_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 5 * p ≤ 13 * (n % p)) (hhi : 5 * (n % p) < 2 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p11_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece11 {x : ℚ} (h1 : 5 / 13 ≤ x) (h2 : x < 2 / 5) : phiT x = 1 := by
  have h := phiT_of_mem (a := 5 / 13) (b := 2 / 5) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece11_res {n p : ℕ} (hp : 0 < p) (hlo : 5 * p ≤ 13 * (n % p))
    (hhi : 5 * (n % p) < 2 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece11 ?_ ?_
  · have h := (fract_ge_iff n p 5 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 2 5 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 11 `[5/13, 2/5)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece11_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 5 * p ≤ 13 * (n % p))
    (hhi : 5 * (n % p) < 2 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece11_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p11_1 hp0 (by omega) (by omega)) t


/-! ## Piece 12: `[3/7, 5/11)`, `φ̃ = 1`, 2 stratum(s) -/

/-- stratum `[3/7, 4/9)`: floors `⌊13x⌋=5, ⌊9x⌋=3, ⌊5x⌋=2, ⌊11x⌋=4, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p12_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 3 * p ≤ 7 * r) (hhi : 9 * r < 4 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 5) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 3) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 2) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 4) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p12_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 3 * p ≤ 7 * (n % p)) (hhi : 9 * (n % p) < 4 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p12_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[4/9, 5/11)`: floors `⌊13x⌋=5, ⌊9x⌋=4, ⌊5x⌋=2, ⌊11x⌋=4, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p12_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 4 * p ≤ 9 * r) (hhi : 11 * r < 5 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 5) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 4) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 2) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 4) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p12_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 4 * p ≤ 9 * (n % p)) (hhi : 11 * (n % p) < 5 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p12_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece12 {x : ℚ} (h1 : 3 / 7 ≤ x) (h2 : x < 5 / 11) : phiT x = 1 := by
  have h := phiT_of_mem (a := 3 / 7) (b := 5 / 11) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece12_res {n p : ℕ} (hp : 0 < p) (hlo : 3 * p ≤ 7 * (n % p))
    (hhi : 11 * (n % p) < 5 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece12 ?_ ?_
  · have h := (fract_ge_iff n p 3 7 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 5 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 12 `[3/7, 5/11)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece12_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 3 * p ≤ 7 * (n % p))
    (hhi : 11 * (n % p) < 5 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece12_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (9 * (n % p)) (4 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p12_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p12_2 hp0 (by omega) (by omega)) t


/-! ## Piece 14: `[7/15, 8/17)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[7/15, 8/17)`: floors `⌊13x⌋=6, ⌊9x⌋=4, ⌊5x⌋=2, ⌊11x⌋=5, ⌊4x⌋=1, ⌊2x⌋=0`. -/
theorem bits_p14_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 7 * p ≤ 15 * r) (hhi : 17 * r < 8 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 6) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 4) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 2) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 5) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 1) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 0) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p14_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 7 * p ≤ 15 * (n % p)) (hhi : 17 * (n % p) < 8 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p14_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece14 {x : ℚ} (h1 : 7 / 15 ≤ x) (h2 : x < 8 / 17) : phiT x = 1 := by
  have h := phiT_of_mem (a := 7 / 15) (b := 8 / 17) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece14_res {n p : ℕ} (hp : 0 < p) (hlo : 7 * p ≤ 15 * (n % p))
    (hhi : 17 * (n % p) < 8 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece14 ?_ ?_
  · have h := (fract_ge_iff n p 7 15 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 8 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 14 `[7/15, 8/17)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece14_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 7 * p ≤ 15 * (n % p))
    (hhi : 17 * (n % p) < 8 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece14_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p14_1 hp0 (by omega) (by omega)) t


/-! ## Piece 15: `[8/15, 7/13)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[8/15, 7/13)`: floors `⌊13x⌋=6, ⌊9x⌋=4, ⌊5x⌋=2, ⌊11x⌋=5, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p15_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 8 * p ≤ 15 * r) (hhi : 13 * r < 7 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 6) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 4) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 2) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 5) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p15_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 8 * p ≤ 15 * (n % p)) (hhi : 13 * (n % p) < 7 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p15_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece15 {x : ℚ} (h1 : 8 / 15 ≤ x) (h2 : x < 7 / 13) : phiT x = 1 := by
  have h := phiT_of_mem (a := 8 / 15) (b := 7 / 13) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece15_res {n p : ℕ} (hp : 0 < p) (hlo : 8 * p ≤ 15 * (n % p))
    (hhi : 13 * (n % p) < 7 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece15 ?_ ?_
  · have h := (fract_ge_iff n p 8 15 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 7 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 15 `[8/15, 7/13)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece15_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 8 * p ≤ 15 * (n % p))
    (hhi : 13 * (n % p) < 7 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece15_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p15_1 hp0 (by omega) (by omega)) t


/-! ## Piece 17: `[9/16, 8/13)`, `φ̃ = 1`, 2 stratum(s) -/

/-- stratum `[9/16, 3/5)`: floors `⌊13x⌋=7, ⌊9x⌋=5, ⌊5x⌋=2, ⌊11x⌋=6, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p17_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 9 * p ≤ 16 * r) (hhi : 5 * r < 3 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 7) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 5) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 2) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 6) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p17_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 9 * p ≤ 16 * (n % p)) (hhi : 5 * (n % p) < 3 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p17_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[3/5, 8/13)`: floors `⌊13x⌋=7, ⌊9x⌋=5, ⌊5x⌋=3, ⌊11x⌋=6, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p17_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 3 * p ≤ 5 * r) (hhi : 13 * r < 8 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 7) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 5) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 6) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p17_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 3 * p ≤ 5 * (n % p)) (hhi : 13 * (n % p) < 8 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p17_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece17 {x : ℚ} (h1 : 9 / 16 ≤ x) (h2 : x < 8 / 13) : phiT x = 1 := by
  have h := phiT_of_mem (a := 9 / 16) (b := 8 / 13) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece17_res {n p : ℕ} (hp : 0 < p) (hlo : 9 * p ≤ 16 * (n % p))
    (hhi : 13 * (n % p) < 8 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece17 ?_ ?_
  · have h := (fract_ge_iff n p 9 16 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 8 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 17 `[9/16, 8/13)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece17_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 9 * p ≤ 16 * (n % p))
    (hhi : 13 * (n % p) < 8 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece17_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (5 * (n % p)) (3 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p17_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p17_2 hp0 (by omega) (by omega)) t


/-! ## Piece 18: `[7/11, 11/17)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[7/11, 11/17)`: floors `⌊13x⌋=8, ⌊9x⌋=5, ⌊5x⌋=3, ⌊11x⌋=7, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p18_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 7 * p ≤ 11 * r) (hhi : 17 * r < 11 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 8) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 5) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 7) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p18_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 7 * p ≤ 11 * (n % p)) (hhi : 17 * (n % p) < 11 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p18_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece18 {x : ℚ} (h1 : 7 / 11 ≤ x) (h2 : x < 11 / 17) : phiT x = 2 := by
  have h := phiT_of_mem (a := 7 / 11) (b := 11 / 17) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece18_res {n p : ℕ} (hp : 0 < p) (hlo : 7 * p ≤ 11 * (n % p))
    (hhi : 17 * (n % p) < 11 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece18 ?_ ?_
  · have h := (fract_ge_iff n p 7 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 11 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 18 `[7/11, 11/17)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece18_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 7 * p ≤ 11 * (n % p))
    (hhi : 17 * (n % p) < 11 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece18_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p18_1 hp0 (by omega) (by omega)) t


/-! ## Piece 19: `[11/17, 9/13)`, `φ̃ = 1`, 2 stratum(s) -/

/-- stratum `[11/17, 2/3)`: floors `⌊13x⌋=8, ⌊9x⌋=5, ⌊5x⌋=3, ⌊11x⌋=7, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p19_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 11 * p ≤ 17 * r) (hhi : 3 * r < 2 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 8) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 5) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 7) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p19_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 11 * p ≤ 17 * (n % p)) (hhi : 3 * (n % p) < 2 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p19_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[2/3, 9/13)`: floors `⌊13x⌋=8, ⌊9x⌋=6, ⌊5x⌋=3, ⌊11x⌋=7, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p19_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 2 * p ≤ 3 * r) (hhi : 13 * r < 9 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 8) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 6) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 7) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p19_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 2 * p ≤ 3 * (n % p)) (hhi : 13 * (n % p) < 9 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p19_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece19 {x : ℚ} (h1 : 11 / 17 ≤ x) (h2 : x < 9 / 13) : phiT x = 1 := by
  have h := phiT_of_mem (a := 11 / 17) (b := 9 / 13) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece19_res {n p : ℕ} (hp : 0 < p) (hlo : 11 * p ≤ 17 * (n % p))
    (hhi : 13 * (n % p) < 9 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece19 ?_ ?_
  · have h := (fract_ge_iff n p 11 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 9 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 19 `[11/17, 9/13)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece19_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 11 * p ≤ 17 * (n % p))
    (hhi : 13 * (n % p) < 9 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece19_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (3 * (n % p)) (2 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p19_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p19_2 hp0 (by omega) (by omega)) t


/-! ## Piece 20: `[5/7, 8/11)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[5/7, 8/11)`: floors `⌊13x⌋=9, ⌊9x⌋=6, ⌊5x⌋=3, ⌊11x⌋=7, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p20_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 5 * p ≤ 7 * r) (hhi : 11 * r < 8 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 9) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 6) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 7) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p20_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 5 * p ≤ 7 * (n % p)) (hhi : 11 * (n % p) < 8 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p20_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece20 {x : ℚ} (h1 : 5 / 7 ≤ x) (h2 : x < 8 / 11) : phiT x = 1 := by
  have h := phiT_of_mem (a := 5 / 7) (b := 8 / 11) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece20_res {n p : ℕ} (hp : 0 < p) (hlo : 5 * p ≤ 7 * (n % p))
    (hhi : 11 * (n % p) < 8 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece20 ?_ ?_
  · have h := (fract_ge_iff n p 5 7 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 8 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 20 `[5/7, 8/11)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece20_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 5 * p ≤ 7 * (n % p))
    (hhi : 11 * (n % p) < 8 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece20_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p20_1 hp0 (by omega) (by omega)) t


/-! ## Piece 21: `[8/11, 10/13)`, `φ̃ = 2`, 2 stratum(s) -/

/-- stratum `[8/11, 3/4)`: floors `⌊13x⌋=9, ⌊9x⌋=6, ⌊5x⌋=3, ⌊11x⌋=8, ⌊4x⌋=2, ⌊2x⌋=1`. -/
theorem bits_p21_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 8 * p ≤ 11 * r) (hhi : 4 * r < 3 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 9) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 6) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 8) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 2) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p21_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 8 * p ≤ 11 * (n % p)) (hhi : 4 * (n % p) < 3 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p21_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[3/4, 10/13)`: floors `⌊13x⌋=9, ⌊9x⌋=6, ⌊5x⌋=3, ⌊11x⌋=8, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p21_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 3 * p ≤ 4 * r) (hhi : 13 * r < 10 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 9) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 6) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 8) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p21_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 3 * p ≤ 4 * (n % p)) (hhi : 13 * (n % p) < 10 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p21_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece21 {x : ℚ} (h1 : 8 / 11 ≤ x) (h2 : x < 10 / 13) : phiT x = 2 := by
  have h := phiT_of_mem (a := 8 / 11) (b := 10 / 13) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece21_res {n p : ℕ} (hp : 0 < p) (hlo : 8 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 10 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece21 ?_ ?_
  · have h := (fract_ge_iff n p 8 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 10 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 21 `[8/11, 10/13)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece21_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 8 * p ≤ 11 * (n % p))
    (hhi : 13 * (n % p) < 10 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece21_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (4 * (n % p)) (3 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p21_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p21_2 hp0 (by omega) (by omega)) t


/-! ## Piece 22: `[10/13, 4/5)`, `φ̃ = 1`, 2 stratum(s) -/

/-- stratum `[10/13, 7/9)`: floors `⌊13x⌋=10, ⌊9x⌋=6, ⌊5x⌋=3, ⌊11x⌋=8, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p22_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 10 * p ≤ 13 * r) (hhi : 9 * r < 7 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 10) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 6) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 8) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p22_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 10 * p ≤ 13 * (n % p)) (hhi : 9 * (n % p) < 7 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p22_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[7/9, 4/5)`: floors `⌊13x⌋=10, ⌊9x⌋=7, ⌊5x⌋=3, ⌊11x⌋=8, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p22_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 7 * p ≤ 9 * r) (hhi : 5 * r < 4 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 10) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 7) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 3) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 8) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p22_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 7 * p ≤ 9 * (n % p)) (hhi : 5 * (n % p) < 4 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p22_2 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece22 {x : ℚ} (h1 : 10 / 13 ≤ x) (h2 : x < 4 / 5) : phiT x = 1 := by
  have h := phiT_of_mem (a := 10 / 13) (b := 4 / 5) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece22_res {n p : ℕ} (hp : 0 < p) (hlo : 10 * p ≤ 13 * (n % p))
    (hhi : 5 * (n % p) < 4 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece22 ?_ ?_
  · have h := (fract_ge_iff n p 10 13 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 4 5 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 22 `[10/13, 4/5)` for the harmonic side**, termwise on its 2 stratum(s). -/
theorem piece22_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 10 * p ≤ 13 * (n % p))
    (hhi : 5 * (n % p) < 4 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece22_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (9 * (n % p)) (7 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p22_1 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p22_2 hp0 (by omega) (by omega)) t


/-! ## Piece 23: `[9/11, 14/17)`, `φ̃ = 2`, 1 stratum(s) -/

/-- stratum `[9/11, 14/17)`: floors `⌊13x⌋=10, ⌊9x⌋=7, ⌊5x⌋=4, ⌊11x⌋=9, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p23_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 9 * p ≤ 11 * r) (hhi : 17 * r < 14 * p) : 2 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 10) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 7) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 4) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 9) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p23_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 9 * p ≤ 11 * (n % p)) (hhi : 17 * (n % p) < 14 * p) : NoShort p n 2 :=
  noShort_of_bits hp fun _ hu => bits_p23_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece23 {x : ℚ} (h1 : 9 / 11 ≤ x) (h2 : x < 14 / 17) : phiT x = 2 := by
  have h := phiT_of_mem (a := 9 / 11) (b := 14 / 17) (v := 2) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece23_res {n p : ℕ} (hp : 0 < p) (hlo : 9 * p ≤ 11 * (n % p))
    (hhi : 17 * (n % p) < 14 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 2 := by
  refine phiT_piece23 ?_ ?_
  · have h := (fract_ge_iff n p 9 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 14 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 23 `[9/11, 14/17)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece23_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 9 * p ≤ 11 * (n % p))
    (hhi : 17 * (n % p) < 14 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece23_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p23_1 hp0 (by omega) (by omega)) t


/-! ## Piece 24: `[14/17, 10/11)`, `φ̃ = 1`, 3 stratum(s) -/

/-- stratum `[14/17, 11/13)`: floors `⌊13x⌋=10, ⌊9x⌋=7, ⌊5x⌋=4, ⌊11x⌋=9, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p24_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 14 * p ≤ 17 * r) (hhi : 13 * r < 11 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 10) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 7) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 4) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 9) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p24_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 14 * p ≤ 17 * (n % p)) (hhi : 13 * (n % p) < 11 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p24_1 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[11/13, 8/9)`: floors `⌊13x⌋=11, ⌊9x⌋=7, ⌊5x⌋=4, ⌊11x⌋=9, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p24_2 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 11 * p ≤ 13 * r) (hhi : 9 * r < 8 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 11) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 7) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 4) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 9) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p24_2 {n p : ℕ} (hp : 0 < p)
    (hlo : 11 * p ≤ 13 * (n % p)) (hhi : 9 * (n % p) < 8 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p24_2 hu (Nat.mod_lt _ hp) hlo hhi

/-- stratum `[8/9, 10/11)`: floors `⌊13x⌋=11, ⌊9x⌋=8, ⌊5x⌋=4, ⌊11x⌋=9, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p24_3 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 8 * p ≤ 9 * r) (hhi : 11 * r < 10 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 11) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 8) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 4) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 9) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p24_3 {n p : ℕ} (hp : 0 < p)
    (hlo : 8 * p ≤ 9 * (n % p)) (hhi : 11 * (n % p) < 10 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p24_3 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece24 {x : ℚ} (h1 : 14 / 17 ≤ x) (h2 : x < 10 / 11) : phiT x = 1 := by
  have h := phiT_of_mem (a := 14 / 17) (b := 10 / 11) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece24_res {n p : ℕ} (hp : 0 < p) (hlo : 14 * p ≤ 17 * (n % p))
    (hhi : 11 * (n % p) < 10 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece24 ?_ ?_
  · have h := (fract_ge_iff n p 14 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 10 11 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 24 `[14/17, 10/11)` for the harmonic side**, termwise on its 3 stratum(s). -/
theorem piece24_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 14 * p ≤ 17 * (n % p))
    (hhi : 11 * (n % p) < 10 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece24_res hp0 hlo hhi]
  rcases Nat.lt_or_ge (13 * (n % p)) (11 * p) with h1 | h1
  · exact blockSum_dvd_of_noShort hp (noShort_p24_1 hp0 (by omega) (by omega)) t
  rcases Nat.lt_or_ge (9 * (n % p)) (8 * p) with h2 | h2
  · exact blockSum_dvd_of_noShort hp (noShort_p24_2 hp0 (by omega) (by omega)) t
  exact blockSum_dvd_of_noShort hp (noShort_p24_3 hp0 (by omega) (by omega)) t


/-! ## Piece 26: `[14/15, 16/17)`, `φ̃ = 1`, 1 stratum(s) -/

/-- stratum `[14/15, 16/17)`: floors `⌊13x⌋=12, ⌊9x⌋=8, ⌊5x⌋=4, ⌊11x⌋=10, ⌊4x⌋=3, ⌊2x⌋=1`. -/
theorem bits_p26_1 {p r u : ℕ} (hu : u < p) (hr : r < p)
    (hlo : 14 * p ≤ 15 * r) (hhi : 17 * r < 16 * p) : 1 ≤ bitsR p r u := by
  have hp : 0 < p := by omega
  obtain ⟨A, hA, hA1, hA2⟩ := residue_spec (q := 12) (a := 13 * r) hp (by omega) (by omega)
  obtain ⟨B, hB, hB1, hB2⟩ := residue_spec (q := 8) (a := 9 * r) hp (by omega) (by omega)
  obtain ⟨C, hC, hC1, hC2⟩ := residue_spec (q := 4) (a := 5 * r) hp (by omega) (by omega)
  obtain ⟨E, hE, hE1, hE2⟩ := residue_spec (q := 10) (a := 11 * r) hp (by omega) (by omega)
  obtain ⟨D, hD, hD1, hD2⟩ := residue_spec (q := 3) (a := 4 * r) hp (by omega) (by omega)
  obtain ⟨F, hF, hF1, hF2⟩ := residue_spec (q := 1) (a := 2 * r) hp (by omega) (by omega)
  unfold bitsR
  rw [bit1_abstract hu hA hD, bit2_abstract hu hB hF, bit3_abstract hu hC,
    bit4_abstract hu hr hE]
  split_ifs <;> omega

theorem noShort_p26_1 {n p : ℕ} (hp : 0 < p)
    (hlo : 14 * p ≤ 15 * (n % p)) (hhi : 17 * (n % p) < 16 * p) : NoShort p n 1 :=
  noShort_of_bits hp fun _ hu => bits_p26_1 hu (Nat.mod_lt _ hp) hlo hhi

theorem phiT_piece26 {x : ℚ} (h1 : 14 / 15 ≤ x) (h2 : x < 16 / 17) : phiT x = 1 := by
  have h := phiT_of_mem (a := 14 / 15) (b := 16 / 17) (v := 1) (by decide +kernel) h1 h2
  exact h

theorem phiT_piece26_res {n p : ℕ} (hp : 0 < p) (hlo : 14 * p ≤ 15 * (n % p))
    (hhi : 17 * (n % p) < 16 * p) : phiT (Int.fract ((n : ℚ) / (p : ℚ))) = 1 := by
  refine phiT_piece26 ?_ ?_
  · have h := (fract_ge_iff n p 14 15 hp (by norm_num)).2 (by omega)
    exact_mod_cast h
  · have h := (fract_lt_iff n p 16 17 hp (by norm_num)).2 (by omega)
    exact_mod_cast h

/-- **Piece 26 `[14/15, 16/17)` for the harmonic side**, termwise on its 1 stratum(s). -/
theorem piece26_blocks {p n : ℕ} (hp : p ∈ phiWindow n) (hlo : 14 * p ≤ 15 * (n % p))
    (hhi : 17 * (n % p) < 16 * p) (t : ℕ) :
    (p : ℤ) ^ (phiT (Int.fract ((n : ℚ) / (p : ℚ)))) ∣ blockSum n p t := by
  have hp0 := (prime_of_mem_phiWindow hp).pos
  rw [phiT_piece26_res hp0 hlo hhi]
  exact blockSum_dvd_of_noShort hp (noShort_p26_1 hp0 (by omega) (by omega)) t


/-! ## Non-vacuity: a real window cell on the first run-free piece -/

/-- `n = 2, p = 29`: `2/29 ∈ [1/15, 1/13)`, `29 ≤ 30`, `29² > 53`. -/
theorem witness_2_29 : 29 ∈ phiWindow 2 ∧ 1 * 29 ≤ 15 * (2 % 29) ∧ 13 * (2 % 29) < 1 * 29 := by
  refine ⟨by decide +kernel, by decide, by decide⟩

end Zeta2PtpRunFree

#print axioms Zeta2PtpRunFree.bits_p1_1
#check @Zeta2PtpRunFree.bits_p1_1
#print axioms Zeta2PtpRunFree.piece1_blocks
#check @Zeta2PtpRunFree.piece1_blocks
#print axioms Zeta2PtpRunFree.bits_p3_1
#check @Zeta2PtpRunFree.bits_p3_1
#print axioms Zeta2PtpRunFree.piece3_blocks
#check @Zeta2PtpRunFree.piece3_blocks
#print axioms Zeta2PtpRunFree.bits_p4_1
#check @Zeta2PtpRunFree.bits_p4_1
#print axioms Zeta2PtpRunFree.piece4_blocks
#check @Zeta2PtpRunFree.piece4_blocks
#print axioms Zeta2PtpRunFree.bits_p5_1
#check @Zeta2PtpRunFree.bits_p5_1
#print axioms Zeta2PtpRunFree.piece5_blocks
#check @Zeta2PtpRunFree.piece5_blocks
#print axioms Zeta2PtpRunFree.bits_p6_1
#check @Zeta2PtpRunFree.bits_p6_1
#print axioms Zeta2PtpRunFree.piece6_blocks
#check @Zeta2PtpRunFree.piece6_blocks
#print axioms Zeta2PtpRunFree.bits_p8_1
#check @Zeta2PtpRunFree.bits_p8_1
#print axioms Zeta2PtpRunFree.piece8_blocks
#check @Zeta2PtpRunFree.piece8_blocks
#print axioms Zeta2PtpRunFree.bits_p9_1
#check @Zeta2PtpRunFree.bits_p9_1
#print axioms Zeta2PtpRunFree.bits_p9_2
#check @Zeta2PtpRunFree.bits_p9_2
#print axioms Zeta2PtpRunFree.piece9_blocks
#check @Zeta2PtpRunFree.piece9_blocks
#print axioms Zeta2PtpRunFree.bits_p10_1
#check @Zeta2PtpRunFree.bits_p10_1
#print axioms Zeta2PtpRunFree.piece10_blocks
#check @Zeta2PtpRunFree.piece10_blocks
#print axioms Zeta2PtpRunFree.bits_p11_1
#check @Zeta2PtpRunFree.bits_p11_1
#print axioms Zeta2PtpRunFree.piece11_blocks
#check @Zeta2PtpRunFree.piece11_blocks
#print axioms Zeta2PtpRunFree.bits_p12_1
#check @Zeta2PtpRunFree.bits_p12_1
#print axioms Zeta2PtpRunFree.bits_p12_2
#check @Zeta2PtpRunFree.bits_p12_2
#print axioms Zeta2PtpRunFree.piece12_blocks
#check @Zeta2PtpRunFree.piece12_blocks
#print axioms Zeta2PtpRunFree.bits_p14_1
#check @Zeta2PtpRunFree.bits_p14_1
#print axioms Zeta2PtpRunFree.piece14_blocks
#check @Zeta2PtpRunFree.piece14_blocks
#print axioms Zeta2PtpRunFree.bits_p15_1
#check @Zeta2PtpRunFree.bits_p15_1
#print axioms Zeta2PtpRunFree.piece15_blocks
#check @Zeta2PtpRunFree.piece15_blocks
#print axioms Zeta2PtpRunFree.bits_p17_1
#check @Zeta2PtpRunFree.bits_p17_1
#print axioms Zeta2PtpRunFree.bits_p17_2
#check @Zeta2PtpRunFree.bits_p17_2
#print axioms Zeta2PtpRunFree.piece17_blocks
#check @Zeta2PtpRunFree.piece17_blocks
#print axioms Zeta2PtpRunFree.bits_p18_1
#check @Zeta2PtpRunFree.bits_p18_1
#print axioms Zeta2PtpRunFree.piece18_blocks
#check @Zeta2PtpRunFree.piece18_blocks
#print axioms Zeta2PtpRunFree.bits_p19_1
#check @Zeta2PtpRunFree.bits_p19_1
#print axioms Zeta2PtpRunFree.bits_p19_2
#check @Zeta2PtpRunFree.bits_p19_2
#print axioms Zeta2PtpRunFree.piece19_blocks
#check @Zeta2PtpRunFree.piece19_blocks
#print axioms Zeta2PtpRunFree.bits_p20_1
#check @Zeta2PtpRunFree.bits_p20_1
#print axioms Zeta2PtpRunFree.piece20_blocks
#check @Zeta2PtpRunFree.piece20_blocks
#print axioms Zeta2PtpRunFree.bits_p21_1
#check @Zeta2PtpRunFree.bits_p21_1
#print axioms Zeta2PtpRunFree.bits_p21_2
#check @Zeta2PtpRunFree.bits_p21_2
#print axioms Zeta2PtpRunFree.piece21_blocks
#check @Zeta2PtpRunFree.piece21_blocks
#print axioms Zeta2PtpRunFree.bits_p22_1
#check @Zeta2PtpRunFree.bits_p22_1
#print axioms Zeta2PtpRunFree.bits_p22_2
#check @Zeta2PtpRunFree.bits_p22_2
#print axioms Zeta2PtpRunFree.piece22_blocks
#check @Zeta2PtpRunFree.piece22_blocks
#print axioms Zeta2PtpRunFree.bits_p23_1
#check @Zeta2PtpRunFree.bits_p23_1
#print axioms Zeta2PtpRunFree.piece23_blocks
#check @Zeta2PtpRunFree.piece23_blocks
#print axioms Zeta2PtpRunFree.bits_p24_1
#check @Zeta2PtpRunFree.bits_p24_1
#print axioms Zeta2PtpRunFree.bits_p24_2
#check @Zeta2PtpRunFree.bits_p24_2
#print axioms Zeta2PtpRunFree.bits_p24_3
#check @Zeta2PtpRunFree.bits_p24_3
#print axioms Zeta2PtpRunFree.piece24_blocks
#check @Zeta2PtpRunFree.piece24_blocks
#print axioms Zeta2PtpRunFree.bits_p26_1
#check @Zeta2PtpRunFree.bits_p26_1
#print axioms Zeta2PtpRunFree.piece26_blocks
#check @Zeta2PtpRunFree.piece26_blocks
#print axioms Zeta2PtpRunFree.witness_2_29
#check @Zeta2PtpRunFree.witness_2_29
